import type { SpecializedCopyCatalog, SpecializedProductCopy } from '../specialized/types'

const HOME_BUYER_COPY_EN: SpecializedCopyCatalog = {
  questions: {
    credit_profile: 'What credit-score range do you believe you are in, and when did you last review your credit?',
    credit_risk_flags: 'Which credit-risk items, if any, apply to you right now?',
    income_employment: 'How would you describe your household income, work type, and how long that income has been stable?',
    debt_dti_readiness: 'How heavy do monthly debts feel, and where do you estimate your debt-to-income readiness?',
    savings_reserves: 'About how much liquid savings do you have, and how many months of emergency reserves?',
    cash_flow_housing: 'How much of your income goes to housing now, and what is left after regular bills?',
    down_payment_readiness: 'About what share of your target down payment is saved, and is gift or assistance available?',
    documentation_readiness: 'Which purchase documents do you already have ready?',
    purchase_situation: 'Are you a first-time or repeat buyer, and what is the intended occupancy and current housing situation?',
    purchase_timeline: 'When do you hope to buy, and how prepared do you feel today?',
  },
  helpers: {
    credit_profile:
      'This range is self-reported. It is not a verified credit score and is not a FICO®, VantageScore®, or bureau score. You do not need to upload a report.',
    credit_risk_flags:
      'Select every item that applies. Choose None if none apply. Choose Not sure if you do not know. Do not enter account numbers, lender logins, or documents.',
    income_employment:
      'Use bands and your best estimate. This measures income stability for readiness, not an underwriting decision.',
    debt_dti_readiness:
      'Use broad bands only. This does not calculate a precise debt-to-income ratio from your other answers.',
    savings_reserves: 'An estimate is enough. Do not enter account numbers or upload statements.',
    cash_flow_housing: 'Think about typical months, not a single unusual bill cycle.',
    down_payment_readiness:
      'Estimate the percent of your target down payment already saved. Gift or assistance is optional context, not a qualification.',
    documentation_readiness:
      'Checklist only. Do not upload files. Tax documents apply if they are part of how you report income.',
    purchase_situation: 'These answers describe your situation. They do not change lending eligibility.',
    purchase_timeline: 'Timing and confidence measure preparation only. A near-term date is not an approval clock.',
  },
  fields: {
    self_reported_score_range: 'Self-reported credit-score range',
    last_reviewed: 'When did you last review your credit reports?',
    credit_risk_flags: 'Credit-risk items',
    household_income_band: 'Household income band',
    employment_income_type: 'Employment or income type',
    tenure_stability: 'How long has this income been stable?',
    monthly_debt_burden: 'Monthly debt burden',
    estimated_dti_readiness: 'Self-estimated debt-to-income readiness',
    liquid_savings_band: 'Liquid savings band',
    emergency_reserve_months: 'Emergency reserve months',
    housing_cost_burden: 'Current housing-cost burden',
    cash_flow_cushion: 'Monthly cash-flow cushion after regular bills',
    down_payment_saved_pct: 'Approximate percent of target down payment saved',
    gift_assistance_availability: 'Gift or down-payment assistance availability',
    documentation_ready: 'Documents already ready',
    buyer_history: 'First-time or repeat buyer',
    intended_occupancy: 'Intended occupancy',
    current_housing: 'Current housing situation',
    target_timing: 'Target purchase timing',
    readiness_confidence: 'How prepared do you feel today?',
  },
  answers: {
    'self_reported_score_range.740_plus': '740+',
    'self_reported_score_range.700_739': '700–739',
    'self_reported_score_range.660_699': '660–699',
    'self_reported_score_range.620_659': '620–659',
    'self_reported_score_range.580_619': '580–619',
    'self_reported_score_range.below_580': 'Below 580',
    'self_reported_score_range.not_sure': 'Not sure',
    'last_reviewed.last_30_days': 'In the last 30 days',
    'last_reviewed.last_6_months': 'In the last 6 months',
    'last_reviewed.last_year': 'In the last year',
    'last_reviewed.more_than_year': 'More than a year ago',
    'last_reviewed.never': 'Never',
    'last_reviewed.not_sure': 'Not sure',
    'credit_risk_flags.late_or_delinquent': 'Late payments or current delinquency',
    'credit_risk_flags.collections_charge_offs': 'Collections or charge-offs',
    'credit_risk_flags.bankruptcy_foreclosure': 'Bankruptcy or foreclosure',
    'credit_risk_flags.none': 'None',
    'credit_risk_flags.not_sure': 'Not sure',
    'household_income_band.under_50k': 'Under $50,000',
    'household_income_band.50_75k': '$50,000–$74,999',
    'household_income_band.75_100k': '$75,000–$99,999',
    'household_income_band.100_150k': '$100,000–$149,999',
    'household_income_band.150k_plus': '$150,000+',
    'household_income_band.not_sure': 'Not sure',
    'employment_income_type.w2': 'W-2 / traditional employment',
    'employment_income_type.self_employed': 'Self-employed',
    'employment_income_type.contract_gig': 'Contract or gig income',
    'employment_income_type.mixed': 'Mixed income sources',
    'employment_income_type.retired_fixed': 'Retired or fixed income',
    'employment_income_type.not_working': 'Not currently working',
    'employment_income_type.not_sure': 'Not sure',
    'tenure_stability.under_1_year': 'Less than 1 year',
    'tenure_stability.1_2_years': '1–2 years',
    'tenure_stability.2_plus_years': '2+ years',
    'tenure_stability.not_sure': 'Not sure',
    'monthly_debt_burden.comfortable': 'Comfortable',
    'monthly_debt_burden.stretching': 'Stretching',
    'monthly_debt_burden.difficult': 'Difficult',
    'monthly_debt_burden.not_sure': 'Not sure',
    'estimated_dti_readiness.under_36': 'Under 36%',
    'estimated_dti_readiness.36_43': 'About 36–43%',
    'estimated_dti_readiness.43_50': 'About 43–50%',
    'estimated_dti_readiness.over_50': 'Over 50%',
    'estimated_dti_readiness.not_sure': 'Not sure',
    'liquid_savings_band.under_2k': 'Under $2,000',
    'liquid_savings_band.2_10k': '$2,000–$9,999',
    'liquid_savings_band.10_25k': '$10,000–$24,999',
    'liquid_savings_band.25_50k': '$25,000–$49,999',
    'liquid_savings_band.50k_plus': '$50,000+',
    'liquid_savings_band.not_sure': 'Not sure',
    'emergency_reserve_months.under_1': 'Less than 1 month',
    'emergency_reserve_months.1_3': '1–3 months',
    'emergency_reserve_months.3_6': '3–6 months',
    'emergency_reserve_months.6_plus': '6+ months',
    'emergency_reserve_months.not_sure': 'Not sure',
    'housing_cost_burden.under_30': 'Under 30% of income',
    'housing_cost_burden.30_40': 'About 30–40%',
    'housing_cost_burden.40_50': 'About 40–50%',
    'housing_cost_burden.over_50': 'Over 50%',
    'housing_cost_burden.not_sure': 'Not sure',
    'cash_flow_cushion.leftover_comfortable': 'Comfortable amount left',
    'cash_flow_cushion.leftover_tight': 'Tight leftover',
    'cash_flow_cushion.none_or_negative': 'Little or nothing left',
    'cash_flow_cushion.not_sure': 'Not sure',
    'down_payment_saved_pct.none': 'None saved yet',
    'down_payment_saved_pct.under_5': 'Under 5% of target',
    'down_payment_saved_pct.5_10': 'About 5–10%',
    'down_payment_saved_pct.10_20': 'About 10–20%',
    'down_payment_saved_pct.20_plus': '20% or more of target',
    'down_payment_saved_pct.not_sure': 'Not sure',
    'gift_assistance_availability.available': 'Gift or assistance is available',
    'gift_assistance_availability.possible': 'Gift or assistance may be possible',
    'gift_assistance_availability.none': 'No gift or assistance path',
    'gift_assistance_availability.not_sure': 'Not sure',
    'documentation_ready.income_docs': 'Income documents',
    'documentation_ready.bank_statements': 'Bank statements',
    'documentation_ready.tax_docs': 'Tax documents, if applicable',
    'documentation_ready.government_id': 'Government ID',
    'documentation_ready.none': 'None ready yet',
    'documentation_ready.not_sure': 'Not sure',
    'buyer_history.first_time': 'First-time buyer',
    'buyer_history.repeat': 'Repeat buyer',
    'intended_occupancy.primary': 'Primary residence',
    'intended_occupancy.second_home': 'Second home',
    'intended_occupancy.investment': 'Investment property',
    'current_housing.renting': 'Renting',
    'current_housing.own': 'Already own a home',
    'current_housing.living_with_family': 'Living with family',
    'current_housing.other': 'Other',
    'target_timing.0_3_months': 'In the next 0–3 months',
    'target_timing.3_6_months': 'In 3–6 months',
    'target_timing.6_12_months': 'In 6–12 months',
    'target_timing.12_plus': 'More than 12 months',
    'target_timing.exploring': 'Just exploring',
    'target_timing.not_sure': 'Not sure',
    'readiness_confidence.very_ready': 'I feel strongly prepared',
    'readiness_confidence.somewhat_ready': 'I feel almost prepared',
    'readiness_confidence.early': 'I am still building readiness',
    'readiness_confidence.not_sure': 'Not sure',
  },
  placeholders: {
    select: 'Select an option',
  },
  validation: {
    required: 'This field is required.',
    contact_required: 'Complete your name, email, and phone.',
  },
  ui: {
    welcomeTitle: 'Start your Home Buyer Report Card',
    welcomeBody:
      'Contact and consent come first. Ten diagnostic questions then measure purchase preparation. This is a readiness review, not a lending decision.',
    welcomeNote:
      'We never collect Social Security numbers, dates of birth, credit-bureau logins, lender credentials, account numbers, or document uploads.',
    back: 'Back',
    continue: 'Continue',
    viewResults: 'View my Home Buyer Report Card',
    contactTitle: 'Contact and acknowledgments',
  },
  results: {
    score: 'Home Buyer Report Card Score',
    grade: 'Grade',
    status: 'Readiness status',
    categories: 'Category scores',
    strengths: 'Strengths',
    barriers: 'Barriers',
    nextActions: 'Prioritized next actions',
    flags: 'Hard-risk flags',
    unavailable: 'Your Home Buyer Report Card results are not available yet.',
    disclaimer:
      'This Home Buyer Report Card Score is a Valtoris educational readiness assessment based on the answers you provided. It measures preparation only. It is not a mortgage decision, approval, or prequalification, and it does not calculate a precise debt-to-income ratio.',
    'status.strongly_prepared': 'Strongly prepared',
    'status.almost_prepared': 'Almost prepared',
    'status.building_readiness': 'Building readiness',
    'status.early_stage': 'Early-stage readiness',
    'status.significant_barriers': 'Significant barriers',
    'category.credit_readiness': 'Credit Readiness',
    'category.income_employment': 'Income & Employment Stability',
    'category.debt_dti_readiness': 'Debt / DTI Readiness',
    'category.savings_reserves': 'Savings & Reserves',
    'category.cash_flow_housing': 'Cash Flow / Housing Affordability',
    'category.down_payment_readiness': 'Down Payment Readiness',
    'category.documentation_readiness': 'Documentation Readiness',
    'category.purchase_timeline': 'Purchase Timeline / Overall Readiness',
    'flag.immediate_review': 'Immediate Review',
    'flag.high_priority': 'High Priority',
    'flag.review_recommended': 'Review Recommended',
    'insight.flag_serious_delinquency.title': 'Recent serious delinquency was reported',
    'insight.flag_serious_delinquency.body':
      'You reported late payments or current delinquency. This is a preparation barrier to review, not a lending decision.',
    'insight.flag_derogatory_credit.title': 'A significant derogatory credit event was reported',
    'insight.flag_derogatory_credit.body':
      'You reported collections, charge-offs, bankruptcy, or foreclosure. These items should be reviewed against your actual reports.',
    'insight.flag_unstable_income.title': 'Income or employment looks unstable',
    'insight.flag_unstable_income.body':
      'You reported no current work or very short contract/gig tenure. Stable income documentation is a common readiness step.',
    'insight.flag_high_debt_burden.title': 'Monthly debt burden looks very high',
    'insight.flag_high_debt_burden.body':
      'You reported a difficult debt load or a self-estimated debt-to-income band over 50%. This uses bands only and is not a precise DTI calculation.',
    'insight.flag_no_savings.title': 'Little or no savings and reserves were reported',
    'insight.flag_no_savings.body':
      'You reported very low liquid savings and less than one month of reserves. Building a buffer is a preparation priority.',
    'insight.flag_no_down_payment_path.title': 'No clear down-payment path was reported',
    'insight.flag_no_down_payment_path.body':
      'You reported little or no down-payment savings and no gift or assistance path. This is a readiness gap, not a denial.',
    'insight.flag_near_term_gaps.title': 'A near-term timeline sits next to major readiness gaps',
    'insight.flag_near_term_gaps.body':
      'You hope to buy soon while several preparation areas still need work. The timeline itself is not a qualification clock.',
    'insight.flag_missing_core_docs.title': 'Core documents are not ready',
    'insight.flag_missing_core_docs.body':
      'Income documents, bank statements, or a government ID still appear missing. This is a checklist only — do not upload files here.',
    'insight.category.credit_readiness.title': 'Credit preparation can be strengthened',
    'insight.category.credit_readiness.body':
      'Your self-reported credit range, last review, or risk flags leave room to improve credit preparation.',
    'insight.category.income_employment.title': 'Income and employment stability can be strengthened',
    'insight.category.income_employment.body':
      'Household income band, work type, or tenure still leave preparation work.',
    'insight.category.debt_dti_readiness.title': 'Debt readiness can be strengthened',
    'insight.category.debt_dti_readiness.body':
      'Your reported monthly burden or estimated DTI band is a preparation area, not a calculated ratio.',
    'insight.category.savings_reserves.title': 'Savings and reserves can be strengthened',
    'insight.category.savings_reserves.body':
      'Liquid savings or emergency months are still building toward a more prepared reserve picture.',
    'insight.category.cash_flow_housing.title': 'Cash-flow and housing-cost room can be strengthened',
    'insight.category.cash_flow_housing.body':
      'Current housing-cost burden or leftover cash flow still leaves limited monthly room.',
    'insight.category.down_payment_readiness.title': 'Down-payment preparation can be strengthened',
    'insight.category.down_payment_readiness.body':
      'The share of your target already saved, or gift/assistance availability, still needs work.',
    'insight.category.documentation_readiness.title': 'Document readiness can be strengthened',
    'insight.category.documentation_readiness.body':
      'Gathering income, bank, tax if applicable, and ID documents is a practical next checklist step.',
    'insight.category.purchase_timeline.title': 'Timeline and overall readiness can be aligned',
    'insight.category.purchase_timeline.body':
      'Target timing and how prepared you feel today should be reviewed together as a preparation plan.',
  },
}

const HOME_BUYER_COPY_ES: SpecializedCopyCatalog = {
  questions: {
    credit_profile:
      '¿En qué rango de puntaje de crédito cree que está y cuándo revisó su crédito por última vez?',
    credit_risk_flags: '¿Qué elementos de riesgo crediticio, si alguno, le aplican ahora?',
    income_employment:
      '¿Cómo describiría el ingreso del hogar, el tipo de trabajo y cuánto tiempo ha sido estable ese ingreso?',
    debt_dti_readiness:
      '¿Qué tan pesadas se sienten las deudas mensuales y dónde estima su preparación de deuda sobre ingreso?',
    savings_reserves: '¿Aproximadamente cuánto ahorro líquido tiene y cuántos meses de reserva de emergencia?',
    cash_flow_housing: '¿Qué parte de su ingreso va a vivienda ahora y qué le queda después de las cuentas regulares?',
    down_payment_readiness:
      '¿Aproximadamente qué parte de su enganche objetivo ya ahorró y hay un regalo o asistencia disponible?',
    documentation_readiness: '¿Qué documentos de compra ya tiene listos?',
    purchase_situation:
      '¿Es comprador por primera vez o repetido, y cuál es la ocupación prevista y su situación de vivienda actual?',
    purchase_timeline: '¿Cuándo espera comprar y qué tan preparado se siente hoy?',
  },
  helpers: {
    credit_profile:
      'Este rango lo informa usted. No es un puntaje de crédito verificado ni un puntaje FICO®, VantageScore® o de una agencia. No necesita subir un reporte.',
    credit_risk_flags:
      'Seleccione cada elemento que aplique. Elija Ninguna si no aplica ninguno. Elija No lo sé si no sabe. No escriba números de cuenta, accesos de prestamista ni documentos.',
    income_employment:
      'Use rangos y su mejor estimación. Esto mide estabilidad de ingresos para preparación, no una decisión de suscripción.',
    debt_dti_readiness:
      'Use solo rangos amplios. Esto no calcula un ratio preciso de deuda sobre ingreso a partir de sus otras respuestas.',
    savings_reserves: 'Una estimación es suficiente. No escriba números de cuenta ni suba estados de cuenta.',
    cash_flow_housing: 'Piense en meses típicos, no en un ciclo de facturas inusual.',
    down_payment_readiness:
      'Estime el porcentaje de su enganche objetivo ya ahorrado. Un regalo o asistencia es contexto opcional, no una calificación.',
    documentation_readiness:
      'Solo una lista. No suba archivos. Los documentos de impuestos aplican si forman parte de cómo reporta ingresos.',
    purchase_situation: 'Estas respuestas describen su situación. No cambian la elegibilidad de un préstamo.',
    purchase_timeline:
      'El plazo y la confianza miden solo la preparación. Una fecha cercana no es un reloj de aprobación.',
  },
  fields: {
    self_reported_score_range: 'Rango de puntaje de crédito que usted informa',
    last_reviewed: '¿Cuándo revisó por última vez sus reportes de crédito?',
    credit_risk_flags: 'Elementos de riesgo crediticio',
    household_income_band: 'Rango de ingreso del hogar',
    employment_income_type: 'Tipo de empleo o ingreso',
    tenure_stability: '¿Cuánto tiempo ha sido estable este ingreso?',
    monthly_debt_burden: 'Carga mensual de deudas',
    estimated_dti_readiness: 'Preparación de deuda sobre ingreso que usted estima',
    liquid_savings_band: 'Rango de ahorro líquido',
    emergency_reserve_months: 'Meses de reserva de emergencia',
    housing_cost_burden: 'Carga actual del costo de vivienda',
    cash_flow_cushion: 'Margen mensual de efectivo después de las cuentas regulares',
    down_payment_saved_pct: 'Porcentaje aproximado del enganche objetivo ya ahorrado',
    gift_assistance_availability: 'Disponibilidad de regalo o asistencia para el enganche',
    documentation_ready: 'Documentos ya listos',
    buyer_history: 'Comprador por primera vez o repetido',
    intended_occupancy: 'Ocupación prevista',
    current_housing: 'Situación actual de vivienda',
    target_timing: 'Plazo objetivo de compra',
    readiness_confidence: '¿Qué tan preparado se siente hoy?',
  },
  answers: {
    'self_reported_score_range.740_plus': '740+',
    'self_reported_score_range.700_739': '700–739',
    'self_reported_score_range.660_699': '660–699',
    'self_reported_score_range.620_659': '620–659',
    'self_reported_score_range.580_619': '580–619',
    'self_reported_score_range.below_580': 'Menos de 580',
    'self_reported_score_range.not_sure': 'No lo sé',
    'last_reviewed.last_30_days': 'En los últimos 30 días',
    'last_reviewed.last_6_months': 'En los últimos 6 meses',
    'last_reviewed.last_year': 'En el último año',
    'last_reviewed.more_than_year': 'Hace más de un año',
    'last_reviewed.never': 'Nunca',
    'last_reviewed.not_sure': 'No lo sé',
    'credit_risk_flags.late_or_delinquent': 'Pagos atrasados o morosidad actual',
    'credit_risk_flags.collections_charge_offs': 'Cobranzas o cuentas dadas de baja',
    'credit_risk_flags.bankruptcy_foreclosure': 'Quiebra o ejecución hipotecaria',
    'credit_risk_flags.none': 'Ninguna',
    'credit_risk_flags.not_sure': 'No lo sé',
    'household_income_band.under_50k': 'Menos de $50,000',
    'household_income_band.50_75k': '$50,000–$74,999',
    'household_income_band.75_100k': '$75,000–$99,999',
    'household_income_band.100_150k': '$100,000–$149,999',
    'household_income_band.150k_plus': '$150,000+',
    'household_income_band.not_sure': 'No lo sé',
    'employment_income_type.w2': 'W-2 / empleo tradicional',
    'employment_income_type.self_employed': 'Trabajador independiente',
    'employment_income_type.contract_gig': 'Ingreso por contrato o trabajo ocasional',
    'employment_income_type.mixed': 'Fuentes de ingreso mixtas',
    'employment_income_type.retired_fixed': 'Jubilado o ingreso fijo',
    'employment_income_type.not_working': 'Sin trabajo actualmente',
    'employment_income_type.not_sure': 'No lo sé',
    'tenure_stability.under_1_year': 'Menos de 1 año',
    'tenure_stability.1_2_years': '1–2 años',
    'tenure_stability.2_plus_years': '2+ años',
    'tenure_stability.not_sure': 'No lo sé',
    'monthly_debt_burden.comfortable': 'Cómoda',
    'monthly_debt_burden.stretching': 'Ajustada',
    'monthly_debt_burden.difficult': 'Difícil',
    'monthly_debt_burden.not_sure': 'No lo sé',
    'estimated_dti_readiness.under_36': 'Menos del 36%',
    'estimated_dti_readiness.36_43': 'Aproximadamente 36–43%',
    'estimated_dti_readiness.43_50': 'Aproximadamente 43–50%',
    'estimated_dti_readiness.over_50': 'Más del 50%',
    'estimated_dti_readiness.not_sure': 'No lo sé',
    'liquid_savings_band.under_2k': 'Menos de $2,000',
    'liquid_savings_band.2_10k': '$2,000–$9,999',
    'liquid_savings_band.10_25k': '$10,000–$24,999',
    'liquid_savings_band.25_50k': '$25,000–$49,999',
    'liquid_savings_band.50k_plus': '$50,000+',
    'liquid_savings_band.not_sure': 'No lo sé',
    'emergency_reserve_months.under_1': 'Menos de 1 mes',
    'emergency_reserve_months.1_3': '1–3 meses',
    'emergency_reserve_months.3_6': '3–6 meses',
    'emergency_reserve_months.6_plus': '6+ meses',
    'emergency_reserve_months.not_sure': 'No lo sé',
    'housing_cost_burden.under_30': 'Menos del 30% del ingreso',
    'housing_cost_burden.30_40': 'Aproximadamente 30–40%',
    'housing_cost_burden.40_50': 'Aproximadamente 40–50%',
    'housing_cost_burden.over_50': 'Más del 50%',
    'housing_cost_burden.not_sure': 'No lo sé',
    'cash_flow_cushion.leftover_comfortable': 'Queda un margen cómodo',
    'cash_flow_cushion.leftover_tight': 'Queda un margen ajustado',
    'cash_flow_cushion.none_or_negative': 'Queda poco o nada',
    'cash_flow_cushion.not_sure': 'No lo sé',
    'down_payment_saved_pct.none': 'Aún no he ahorrado',
    'down_payment_saved_pct.under_5': 'Menos del 5% del objetivo',
    'down_payment_saved_pct.5_10': 'Aproximadamente 5–10%',
    'down_payment_saved_pct.10_20': 'Aproximadamente 10–20%',
    'down_payment_saved_pct.20_plus': '20% o más del objetivo',
    'down_payment_saved_pct.not_sure': 'No lo sé',
    'gift_assistance_availability.available': 'Hay un regalo o asistencia disponible',
    'gift_assistance_availability.possible': 'Un regalo o asistencia podría ser posible',
    'gift_assistance_availability.none': 'No hay ruta de regalo ni asistencia',
    'gift_assistance_availability.not_sure': 'No lo sé',
    'documentation_ready.income_docs': 'Documentos de ingresos',
    'documentation_ready.bank_statements': 'Estados de cuenta bancarios',
    'documentation_ready.tax_docs': 'Documentos de impuestos, si aplican',
    'documentation_ready.government_id': 'Identificación oficial',
    'documentation_ready.none': 'Ninguno listo todavía',
    'documentation_ready.not_sure': 'No lo sé',
    'buyer_history.first_time': 'Comprador por primera vez',
    'buyer_history.repeat': 'Comprador repetido',
    'intended_occupancy.primary': 'Residencia principal',
    'intended_occupancy.second_home': 'Segunda vivienda',
    'intended_occupancy.investment': 'Propiedad de inversión',
    'current_housing.renting': 'Alquilo',
    'current_housing.own': 'Ya soy dueño de una vivienda',
    'current_housing.living_with_family': 'Vivo con familiares',
    'current_housing.other': 'Otra',
    'target_timing.0_3_months': 'En los próximos 0–3 meses',
    'target_timing.3_6_months': 'En 3–6 meses',
    'target_timing.6_12_months': 'En 6–12 meses',
    'target_timing.12_plus': 'Más de 12 meses',
    'target_timing.exploring': 'Solo estoy explorando',
    'target_timing.not_sure': 'No lo sé',
    'readiness_confidence.very_ready': 'Me siento muy preparado',
    'readiness_confidence.somewhat_ready': 'Me siento casi preparado',
    'readiness_confidence.early': 'Todavía estoy construyendo preparación',
    'readiness_confidence.not_sure': 'No lo sé',
  },
  placeholders: {
    select: 'Seleccione una opción',
  },
  validation: {
    required: 'Este campo es obligatorio.',
    contact_required: 'Complete su nombre, correo electrónico y teléfono.',
  },
  ui: {
    welcomeTitle: 'Comience su Reporte para Compradores de Vivienda',
    welcomeBody:
      'El contacto y el consentimiento van primero. Diez preguntas de diagnóstico miden después la preparación para comprar. Esto es una revisión de preparación, no una decisión de préstamo.',
    welcomeNote:
      'Nunca pedimos número de Seguro Social, fecha de nacimiento, accesos a agencias de crédito, credenciales de prestamistas, números de cuenta ni documentos subidos.',
    back: 'Atrás',
    continue: 'Continuar',
    viewResults: 'Ver mi Reporte para Compradores de Vivienda',
    contactTitle: 'Contacto y reconocimientos',
  },
  results: {
    score: 'Puntaje del Reporte para Compradores de Vivienda',
    grade: 'Calificación',
    status: 'Estado de preparación',
    categories: 'Puntajes por categoría',
    strengths: 'Fortalezas',
    barriers: 'Barreras',
    nextActions: 'Próximas acciones priorizadas',
    flags: 'Indicadores de riesgo alto',
    unavailable: 'Los resultados de su Reporte para Compradores de Vivienda aún no están disponibles.',
    disclaimer:
      'Este puntaje es una evaluación educativa de preparación de Valtoris basada en las respuestas que usted dio. Mide solo la preparación. No es una decisión hipotecaria, una aprobación ni una precalificación, y no calcula un ratio preciso de deuda sobre ingreso.',
    'status.strongly_prepared': 'Muy preparado',
    'status.almost_prepared': 'Casi preparado',
    'status.building_readiness': 'Construyendo preparación',
    'status.early_stage': 'Preparación en etapa inicial',
    'status.significant_barriers': 'Barreras significativas',
    'category.credit_readiness': 'Preparación crediticia',
    'category.income_employment': 'Estabilidad de ingresos y empleo',
    'category.debt_dti_readiness': 'Preparación de deuda / DTI',
    'category.savings_reserves': 'Ahorros y reservas',
    'category.cash_flow_housing': 'Flujo de efectivo / asequibilidad de vivienda',
    'category.down_payment_readiness': 'Preparación del enganche',
    'category.documentation_readiness': 'Preparación de documentos',
    'category.purchase_timeline': 'Plazo de compra / preparación general',
    'flag.immediate_review': 'Revisión inmediata',
    'flag.high_priority': 'Alta prioridad',
    'flag.review_recommended': 'Revisión recomendada',
    'insight.flag_serious_delinquency.title': 'Se informó morosidad reciente seria',
    'insight.flag_serious_delinquency.body':
      'Usted indicó pagos atrasados o morosidad actual. Esto es una barrera de preparación para revisar, no una decisión de préstamo.',
    'insight.flag_derogatory_credit.title': 'Se informó un evento crediticio negativo significativo',
    'insight.flag_derogatory_credit.body':
      'Usted indicó cobranzas, cuentas dadas de baja, quiebra o ejecución hipotecaria. Estos elementos deben revisarse frente a sus reportes reales.',
    'insight.flag_unstable_income.title': 'El ingreso o el empleo parece inestable',
    'insight.flag_unstable_income.body':
      'Usted indicó que no trabaja ahora o que su ingreso por contrato es muy reciente. Documentar un ingreso estable es un paso común de preparación.',
    'insight.flag_high_debt_burden.title': 'La carga mensual de deudas parece muy alta',
    'insight.flag_high_debt_burden.body':
      'Usted indicó una carga difícil o un rango estimado de deuda sobre ingreso de más del 50%. Esto usa solo rangos y no es un cálculo preciso de DTI.',
    'insight.flag_no_savings.title': 'Se informó poco o ningún ahorro y reserva',
    'insight.flag_no_savings.body':
      'Usted indicó un ahorro líquido muy bajo y menos de un mes de reserva. Construir un colchón es una prioridad de preparación.',
    'insight.flag_no_down_payment_path.title': 'No se informó una ruta clara de enganche',
    'insight.flag_no_down_payment_path.body':
      'Usted indicó poco o ningún ahorro para el enganche y ninguna ruta de regalo o asistencia. Esto es una brecha de preparación, no una negación.',
    'insight.flag_near_term_gaps.title': 'Un plazo cercano coincide con brechas importantes de preparación',
    'insight.flag_near_term_gaps.body':
      'Espera comprar pronto mientras varias áreas de preparación todavía necesitan trabajo. El plazo en sí no es un reloj de calificación.',
    'insight.flag_missing_core_docs.title': 'Los documentos básicos no están listos',
    'insight.flag_missing_core_docs.body':
      'Todavía parecen faltar documentos de ingresos, estados de cuenta o una identificación oficial. Esto es solo una lista: no suba archivos aquí.',
    'insight.category.credit_readiness.title': 'La preparación crediticia se puede fortalecer',
    'insight.category.credit_readiness.body':
      'El rango de crédito que usted informa, la última revisión o las banderas de riesgo dejan espacio para mejorar la preparación.',
    'insight.category.income_employment.title': 'La estabilidad de ingresos y empleo se puede fortalecer',
    'insight.category.income_employment.body':
      'El rango de ingreso del hogar, el tipo de trabajo o la antigüedad todavía dejan trabajo de preparación.',
    'insight.category.debt_dti_readiness.title': 'La preparación de deuda se puede fortalecer',
    'insight.category.debt_dti_readiness.body':
      'La carga mensual o el rango estimado de DTI que indicó es un área de preparación, no un ratio calculado.',
    'insight.category.savings_reserves.title': 'Los ahorros y reservas se pueden fortalecer',
    'insight.category.savings_reserves.body':
      'El ahorro líquido o los meses de emergencia todavía se están construyendo hacia una reserva más preparada.',
    'insight.category.cash_flow_housing.title': 'El flujo de efectivo y el costo de vivienda se pueden fortalecer',
    'insight.category.cash_flow_housing.body':
      'La carga actual de vivienda o el efectivo que queda todavía deja un margen mensual limitado.',
    'insight.category.down_payment_readiness.title': 'La preparación del enganche se puede fortalecer',
    'insight.category.down_payment_readiness.body':
      'La parte del objetivo ya ahorrada, o la disponibilidad de regalo o asistencia, todavía necesita trabajo.',
    'insight.category.documentation_readiness.title': 'La preparación de documentos se puede fortalecer',
    'insight.category.documentation_readiness.body':
      'Reunir ingresos, banco, impuestos si aplican e identificación es un siguiente paso práctico de la lista.',
    'insight.category.purchase_timeline.title': 'El plazo y la preparación general se pueden alinear',
    'insight.category.purchase_timeline.body':
      'El plazo objetivo y qué tan preparado se siente hoy deben revisarse juntos como un plan de preparación.',
  },
}

export const homeBuyerCopy: SpecializedProductCopy = {
  en: HOME_BUYER_COPY_EN,
  es: HOME_BUYER_COPY_ES,
}
