export const RECRUIT_STAGES = ['recruit', 'licensing', 'eo', 'contracting', 'carrier_appointments', 'ready_to_write', 'active_agent', 'paused', 'withdrawn'] as const
export type RecruitStage = typeof RECRUIT_STAGES[number]
export const stageLabel = (stage: string) => ({ recruit: 'Recruit', licensing: 'Licensing', eo: 'E&O', contracting: 'Contracting', carrier_appointments: 'Carrier Appointments', ready_to_write: 'Ready to Write', active_agent: 'Active Agent', paused: 'Paused', withdrawn: 'Withdrawn' }[stage] ?? stage)
export type Recruit = { id: string; full_name: string; email: string; phone: string | null; advisor_profile_id: string | null; assigned_advisor_id: string | null; stage: RecruitStage; next_action: string | null; next_action_due_on: string | null; is_archived: boolean; revision: number; updated_at: string }
export type Credential = { id: string; recruit_id: string; kind: 'license' | 'eo'; state: string | null; authority_scope: string | null; provider_reference: string; effective_on: string | null; expires_on: string | null; no_expiration: boolean; status: 'reported' | 'verified' | 'revoked'; evidence_reference: string | null; verified_at: string | null }
export type CarrierReview = { id: string; recruit_id: string; carrier_id: string; state: string; authority_scope: string; contract_status: string; contract_effective_on: string | null; contract_expires_on: string | null; contract_no_expiration: boolean; contract_evidence: string | null; appointment_status: string; appointment_effective_on: string | null; appointment_expires_on: string | null; appointment_no_expiration: boolean; appointment_evidence: string | null; reviewed_at: string | null }
export type Readiness = { id: string; carrier_name: string; state: string; authority_scope: string; ready: boolean }
export type History = { id: string; action: string; reason: string; occurred_at: string; before_data: Record<string, unknown> | null; after_data: Record<string, unknown> }
export type Option = { id: string; name: string; email?: string }
