/**
 * Pure vCard 3.0 builders for published advisor card fields.
 * Download-only — no CRM side effects, no analytics writes.
 */

import type {
  IdentitySurfacePublicDto,
  VCardBuildInput,
  VCardBuildResult,
} from './types.js'
import { normalizePublicHref } from './urls.js'

const CRLF = '\r\n'
const MAX_ADDITIONAL_URLS = 12

/**
 * Escape text values per vCard 3.0 (backslash, semicolon, comma, newlines).
 */
export function escapeVCardText(value: string): string {
  return value
    .replace(/\\/g, '\\\\')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '')
    .replace(/;/g, '\\;')
    .replace(/,/g, '\\,')
}

/**
 * Sanitize a download filename; always ends with .vcf
 * Example: "Luis Perez" → "Luis-Perez.vcf"
 */
export function sanitizeVCardFilename(displayName: string): string {
  const base = displayName
    .normalize('NFKD')
    .replace(/[^\w\s-]+/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .slice(0, 80)
  const safe = base.length > 0 ? base : 'contact'
  return `${safe}.vcf`
}

/**
 * Resolve an absolute public card URL for NOTE / URL fields.
 * Accepts an origin (https://host) plus a site-relative card path.
 */
export function buildAbsolutePublicCardUrl(
  origin: string,
  cardUrl: string,
): string | null {
  const trimmedOrigin = origin.trim().replace(/\/+$/, '')
  const path = cardUrl.trim()
  if (!trimmedOrigin || !path.startsWith('/') || path.startsWith('//')) return null
  try {
    const absolute = new URL(path, `${trimmedOrigin}/`)
    if (absolute.protocol !== 'https:' && absolute.protocol !== 'http:') return null
    return absolute.toString()
  } catch {
    return null
  }
}

export function buildVCardNote(absoluteCardUrl: string): string {
  return `Generated by Valtoris Financial\n\nConnect:\n${absoluteCardUrl}`
}

function splitDisplayName(input: VCardBuildInput): { family: string; given: string } {
  const given = (input.firstName ?? '').trim()
  const family = (input.lastName ?? '').trim()
  if (given || family) {
    return { family, given }
  }

  const parts = input.displayName.trim().split(/\s+/).filter(Boolean)
  if (parts.length === 0) return { family: '', given: '' }
  if (parts.length === 1) return { family: '', given: parts[0]! }
  return {
    given: parts[0]!,
    family: parts.slice(1).join(' '),
  }
}

/**
 * Accept absolute http(s) URLs for vCard URL fields.
 * Relative paths are rejected here — callers must absolutize first.
 */
function normalizeVCardUrl(value: unknown): string | null {
  if (typeof value !== 'string') return null
  const trimmed = value.trim()
  if (!trimmed || trimmed.length > 500) return null

  const asPublic = normalizePublicHref(trimmed)
  if (asPublic?.startsWith('https://')) return asPublic

  try {
    const parsed = new URL(trimmed)
    if (parsed.protocol === 'https:' || parsed.protocol === 'http:') {
      return parsed.toString()
    }
  } catch {
    return null
  }
  return null
}

function pushUniqueUrl(target: string[], candidate: string | null | undefined): void {
  const normalized = normalizeVCardUrl(candidate)
  if (!normalized) return
  if (target.includes(normalized)) return
  target.push(normalized)
}

function toAbsolutePublicUrl(
  value: string | null | undefined,
  origin: string,
): string | null {
  if (!value?.trim()) return null
  const trimmed = value.trim()
  if (trimmed.startsWith('/') && !trimmed.startsWith('//')) {
    return buildAbsolutePublicCardUrl(origin, trimmed)
  }
  return normalizeVCardUrl(trimmed)
}

/**
 * Build a vCard 3.0 document from allowlisted published fields only.
 * Omits address by default. Does not create leads, households, or activities.
 */
export function buildVCard(input: VCardBuildInput): VCardBuildResult {
  const displayName = input.displayName.trim()
  const { family, given } = splitDisplayName(input)
  const lines: string[] = [
    'BEGIN:VCARD',
    'VERSION:3.0',
    'PRODID:-//Valtoris Financial//Digital Identity//EN',
    `FN:${escapeVCardText(displayName)}`,
    `N:${escapeVCardText(family)};${escapeVCardText(given)};;;`,
  ]

  const org = input.organization?.trim()
  if (org) lines.push(`ORG:${escapeVCardText(org)}`)

  const title = input.title?.trim()
  if (title) lines.push(`TITLE:${escapeVCardText(title)}`)

  const phone = input.phone?.trim()
  if (phone) lines.push(`TEL;TYPE=CELL,VOICE:${escapeVCardText(phone)}`)

  const email = input.email?.trim()
  if (email) lines.push(`EMAIL;TYPE=INTERNET,WORK:${escapeVCardText(email)}`)

  const urls: string[] = []
  pushUniqueUrl(urls, input.url)
  for (const extra of input.additionalUrls ?? []) {
    if (urls.length >= MAX_ADDITIONAL_URLS + 1) break
    pushUniqueUrl(urls, extra)
  }
  for (const url of urls) {
    lines.push(`URL:${escapeVCardText(url)}`)
  }

  const note = input.note?.trim()
  if (note) lines.push(`NOTE:${escapeVCardText(note)}`)

  const photoUrl = input.photoUrl?.trim()
  if (photoUrl && /^https:\/\//i.test(photoUrl)) {
    // URI photo reference only — never embed private binary blobs here.
    lines.push(`PHOTO;VALUE=URI:${escapeVCardText(photoUrl)}`)
  }

  lines.push('END:VCARD')

  return {
    body: `${lines.join(CRLF)}${CRLF}`,
    filename: sanitizeVCardFilename(displayName || 'contact'),
    createsCrmRecord: false,
  }
}

/**
 * Map a published public DTO into a downloadable vCard.
 * Honors DTO visibility (null phone/email are omitted — never reconstructed).
 */
export function buildVCardFromPublicDto(
  card: IdentitySurfacePublicDto,
  options: { absoluteCardUrl: string; origin?: string },
): VCardBuildResult {
  const absoluteCardUrl = options.absoluteCardUrl.trim()
  const origin =
    options.origin?.trim().replace(/\/+$/, '') ||
    (() => {
      try {
        return new URL(absoluteCardUrl).origin
      } catch {
        return ''
      }
    })()

  const additionalUrls: string[] = []
  pushUniqueUrl(additionalUrls, toAbsolutePublicUrl(card.website, origin))
  pushUniqueUrl(additionalUrls, toAbsolutePublicUrl(card.calendlyUrl, origin))
  for (const link of card.socialLinks) {
    pushUniqueUrl(additionalUrls, toAbsolutePublicUrl(link.url, origin))
  }

  // Primary URL is the public card; do not also duplicate it in additionalUrls.
  const extras = additionalUrls.filter((url) => url !== absoluteCardUrl)

  return buildVCard({
    displayName: card.displayName,
    organization: card.approvedCompany,
    title: card.approvedTitle,
    phone: card.phone,
    email: card.email,
    url: absoluteCardUrl,
    additionalUrls: extras,
    note: buildVCardNote(absoluteCardUrl),
    photoUrl: card.headshotUrl,
  })
}

/** Documented no-op contract for vCard generation. */
export function vCardGenerationSideEffects(): {
  writesAnalytics: false
  createsLead: false
  createsHousehold: false
  createsTask: false
  createsActivity: false
  createsCase: false
  createsCrmRecord: false
} {
  return {
    writesAnalytics: false,
    createsLead: false,
    createsHousehold: false,
    createsTask: false,
    createsActivity: false,
    createsCase: false,
    createsCrmRecord: false,
  }
}
