import {emptyIntakeRow,validateIntakeStructure,type IntakeAnswers,type IntakeField,type IntakeSection} from './studentLoanSchema'
const f=(id:string,label:string,kind:IntakeField['kind']='text',required=false):IntakeField=>({id,label,kind,required})
const choice=(id:string,label:string,options:readonly string[],required=false):IntakeField=>({id,label,kind:'select',options,required})
const yesNo=['Yes','No','Not sure']
const section=(id:string,title:string,fields:IntakeField[],repeatable=false,description='Record client-confirmed facts. Leave unknown amounts blank; enter zero only when confirmed.'):IntakeSection=>({id,title,fields,repeatable,description})
const client=section('client','Client and request',[f('firstName','Legal first name','text',true),f('lastName','Legal last name','text',true),f('email','Email','email'),f('phone','Phone'),f('state','State of residence','text',true),f('goal','What would you like help with?','multiline',true),choice('confirmed','Client details and requested service confirmed?',['Yes','Not yet'],true)])
const review=section('review','Next steps',[f('nextStep','Agreed next step','multiline',true),f('owner','Person responsible','text',true),f('dueDate','Follow-up date','date'),f('missing','Missing information or documents','multiline'),choice('confirmed','Review confirmed with the client?',['Yes','Not yet'],true)],false,'This intake records the request. It does not submit an application, bind coverage, authorize a credit dispute, prepare legal documents, or determine eligibility.')
export const ADDITIONAL_SERVICE_CONTRACTS = {
 credit_repair:{label:'Credit Repair',sections:[client,
  section('goals','Credit goals',[choice('purpose','Primary goal',['Improve report accuracy','Prepare for a home purchase','Prepare for financing','Review collections','General review'],true),f('targetDate','Target date','date'),choice('reportAccess','Can the client access their credit reports?',yesNo,true),f('reportDate','Report date, if available','date'),choice('identityTheft','Client reports possible identity theft?',yesNo),f('priorHelp','Prior credit-repair or dispute work','multiline')]),
  section('items','Items to review',[f('bureau','Bureau','text',true),f('creditor','Creditor or collector','text',true),f('reference','Masked reference only (last four digits)'),choice('issue','Reported issue',['Incorrect identity','Balance or payment history','Duplicate item','Account not recognized','Collection','Other','Not sure'],true),f('balance','Reported balance ($)','money'),f('clientAccount','Client’s explanation of the concern','multiline',true),f('evidence','Evidence available and date','multiline'),f('priorDispute','Prior dispute date and outcome','multiline')],true),
  section('readiness','Engagement readiness',[choice('agreement','Service agreement status',['Not discussed','Pending','Signed separately','Declined'],true),f('agreementReference','Non-sensitive agreement reference'),f('urgentNotice','Any urgent notice or deadline','multiline')]),review]},
 retirement:{label:'Retirement / Annuities',sections:[client,
  section('plan','Retirement goals',[f('retirementDate','Target retirement date','date'),f('monthlySpending','Expected monthly spending ($)','money'),f('guaranteedIncome','Expected monthly guaranteed income ($)','money'),f('incomeStart','Desired income start date','date'),choice('priority','Primary priority',['Income','Growth','Principal protection','Legacy','Review existing contracts','Not sure'],true),f('liquidity','Expected near-term cash needs and timing','multiline',true),choice('risk','Client-described tolerance for loss',['None','Low','Moderate','High','Not yet discussed'],true)]),
  section('accounts','Accounts and existing contracts',[f('owner','Account owner','text',true),f('provider','Provider','text',true),choice('type','Account type',['IRA','Roth IRA','Employer plan','Annuity','Taxable account','Other'],true),f('balance','Current value ($)','money'),f('asOf','Value as of','date'),f('contribution','Annual contribution ($)','money'),f('surrender','Surrender period, charges, or restrictions','multiline'),f('beneficiaries','Beneficiary review status')],true),
  section('annuity','Annuity review',[f('funding','Proposed funding source (no account numbers)'),f('deposit','Proposed deposit ($)','money'),choice('replacement','Would an existing contract be replaced?',yesNo),f('timeHorizon','Time horizon and expected access needs','multiline'),f('constraints','Client concerns and questions','multiline')]),review]},
 wills_trusts:{label:'Wills & Trusts',sections:[client,
  section('estate','Planning request',[choice('documents','Requested review',['Will','Trust','Will and trust','Powers of attorney','Existing plan review','Not sure'],true),choice('existing','Existing estate documents?',yesNo,true),f('documentDate','Existing plan date','date'),f('family','Family circumstances relevant to planning','multiline'),f('goals','Distribution goals and special concerns','multiline',true),f('attorney','Existing attorney or requested professional handoff')]),
  section('people','Proposed decision-makers',[f('name','Name','text',true),choice('role','Proposed role',['Executor','Trustee','Guardian','Financial agent','Healthcare agent','Beneficiary','Other'],true),f('relationship','Relationship'),f('alternate','Alternate person')],true),
  section('assets','Asset categories',[choice('type','Asset type',['Home or real estate','Business interest','Retirement account','Insurance','Bank or investment account','Other'],true),f('ownership','Owner and ownership form'),f('value','Approximate value ($)','money'),f('designation','Existing beneficiary or transfer designation')],true),review]},
 pc:{label:'Property & Casualty',sections:[client,
  section('coverage','Coverage request',[choice('type','Coverage needed',['Auto','Home','Commercial','Multiple lines','Other'],true),f('effectiveDate','Desired effective date','date'),f('currentCarrier','Current carrier'),f('renewalDate','Current renewal date','date'),f('coverageConcerns','Coverage gaps or concerns','multiline',true),f('quoteReference','Existing CRM quote request date or reference'),f('locations','Relevant properties, vehicles, or business locations','multiline'),f('handoff','Quote documents needed and next action','multiline')],false,'Use the household Insurance quote requests panel for the existing detailed Auto, Home, and Commercial quote forms and submitted answers. This service intake does not create or submit a duplicate quote.'),review]},
 health:{label:'Health Insurance',sections:[client,
  section('coverage','Coverage needs',[choice('request','Requested coverage',['Individual or family','Employer options','Medicare review','Supplemental coverage','Other','Not sure'],true),f('effectiveDate','Desired effective date','date'),f('currentPlan','Current plan and renewal date'),f('lossDate','Coverage loss date, if applicable','date'),f('event','Enrollment event or deadline reported by client'),f('people','People needing coverage and relationships','multiline',true),f('budget','Monthly budget ($)','money'),f('preferences','Provider network and coverage preferences; no diagnoses or medication details','multiline')]),review]},
 tax_strategy:{label:'Tax Strategy',sections:[client,
  section('tax','Tax planning request',[f('taxYear','Tax year under review','number',true),choice('filing','Reported filing status',['Single','Married jointly','Married separately','Head of household','Other','Not sure'],true),f('incomeSources','Income source categories','multiline',true),f('business','Business or self-employment interests','multiline'),f('changes','Recent life, income, or ownership changes','multiline'),f('deadlines','Notices and deadlines (no taxpayer numbers)','multiline'),f('professional','Current tax professional'),f('documents','Documents available for secure professional handoff','multiline')]),review]},
 business:{label:'Business Services',sections:[client,
  section('business','Business request',[f('name','Business or proposed business name','text',true),f('state','State of operation','text',true),choice('stage','Current stage',['Planning','New business','Existing business','Acquisition or succession'],true),f('structure','Current or proposed entity structure'),f('owners','Owners, roles, and ownership percentages','multiline'),f('activity','Business activity','multiline',true),f('employees','Employee count','number'),f('priorities','Formation, protection, benefits, tax, or succession needs','multiline',true),f('professionals','Existing attorney, accountant, and insurance contacts','multiline')]),review]},
 home_buyer:{label:'Home Buyer Planning',sections:[client,
  section('purchase','Home purchase plans',[choice('stage','Purchase stage',['Exploring','Saving','Preapproval','Shopping','Under contract','Other'],true),f('targetDate','Target purchase date','date'),f('location','Target location','text',true),f('price','Target purchase price ($)','money'),f('cash','Cash available toward purchase ($)','money'),f('reserve','Desired cash reserve after closing ($)','money'),f('monthlyBudget','Comfortable monthly housing budget ($)','money'),f('lender','Lender or loan officer'),f('agent','Real estate agent'),f('concerns','Credit, debt, income, or timing concerns','multiline')]),review]},
} as const satisfies Record<string,{label:string;sections:readonly IntakeSection[]}>
export type AdditionalServiceId=keyof typeof ADDITIONAL_SERVICE_CONTRACTS
export function isAdditionalServiceId(id:string):id is AdditionalServiceId{return Object.prototype.hasOwnProperty.call(ADDITIONAL_SERVICE_CONTRACTS,id)}
export function emptyAdditionalIntake(id:AdditionalServiceId):IntakeAnswers{return {version:1,tracks:[id],sections:Object.fromEntries(ADDITIONAL_SERVICE_CONTRACTS[id].sections.map(s=>[s.id,s.repeatable?[]:[emptyIntakeRow(s)]]))}}
export function validateAdditionalIntake(id:AdditionalServiceId,raw:unknown,complete=false):string[]{
 const errors=validateIntakeStructure(raw,ADDITIONAL_SERVICE_CONTRACTS[id].sections,[id],complete)
 if(errors.length)return errors
 const a=raw as IntakeAnswers
 if(a.tracks.length!==1||a.tracks[0]!==id)return ['The service cannot be changed on an existing intake.']
 if(complete&&a.sections.review[0].confirmed!=='Yes')return ['Confirm the review with the client before completing.']
 return []
}
