import type { SpecializedCopyCatalog, SpecializedProductCopy } from '../specialized/types'

const CREDIT_COPY_EN: SpecializedCopyCatalog = {
  questions: {
    credit_goal: 'What is the main reason you want a credit review?',
    self_reported_score: 'What credit score range do you believe you are in, if you know?',
    report_review: 'When did you last review your credit reports, and do you believe anything is wrong?',
    payment_history: 'How have recent payments gone?',
    negative_items: 'Which negative items, if any, do you believe are on your reports?',
    utilization: 'About how much of your available revolving credit are you currently using?',
    credit_structure: 'How many open revolving accounts do you have, and about how old is the oldest?',
    recent_credit: 'Have you had recent hard inquiries or newly opened accounts?',
    financial_stability: 'How manageable are your minimum payments, and are any accounts past due?',
    urgency_actions: 'How soon do you want a review, and have you already tried credit help?',
  },
  helpers: {
    credit_goal: 'Choose the primary reason. This helps frame later review areas.',
    self_reported_score:
      'This is self-reported and is not your official Credit Report Card Score. It is not a FICO®, VantageScore®, or bureau score.',
    report_review:
      'Think about Experian, Equifax, and TransUnion if you have seen them. You do not need to upload a report.',
    payment_history: 'There is no penalty for answering honestly. Recent lates and current consistency stay together.',
    negative_items:
      'Select every item you believe applies. Choose None if you do not believe any apply. Do not enter creditor names or account numbers.',
    utilization: 'An estimate is enough. This does not calculate a bureau score impact.',
    credit_structure: 'Use your best estimate. Account numbers are never needed.',
    recent_credit: 'Hard inquiries are requests that can appear after new credit applications.',
    financial_stability: 'This is about current manageability, not a lending decision.',
    urgency_actions: 'Select every prior action that applies. Choose None if you have not tried any.',
    inaccuracy_belief:
      'Inaccurate, duplicated, outdated, or not-yours items are a review concern — not a promise that anything can be removed.',
  },
  fields: {
    credit_goal: 'Primary goal',
    self_reported_score: 'Self-reported score range',
    last_reviewed: 'When did you last review your credit reports?',
    inaccuracy_belief:
      'Do you believe anything on your reports may be inaccurate, duplicated, outdated, or not yours?',
    late_recent: 'Recent late-payment severity',
    payment_consistency: 'Current payment consistency',
    negative_items: 'Negative items',
    utilization: 'Approximate revolving utilization',
    open_revolving: 'Open revolving accounts',
    oldest_account: 'Oldest open account',
    hard_inquiries: 'Recent hard inquiries',
    new_accounts: 'Recently opened accounts',
    minimums: 'How manageable are your minimum payments?',
    current_status: 'Are any accounts currently past due?',
    urgency: 'How soon do you want a review?',
    prior_actions: 'Previous credit actions',
  },
  answers: {
    'credit_goal.buy_home': 'Buy a home',
    'credit_goal.vehicle': 'Finance or refinance a vehicle',
    'credit_goal.rent': 'Rent a home or apartment',
    'credit_goal.lower_rates': 'Qualify for better rates',
    'credit_goal.business_financing': 'Business financing',
    'credit_goal.rebuild_credit': 'Rebuild my credit',
    'credit_goal.general_health': 'Improve my overall credit health',
    'self_reported_score.740_plus': '740+',
    'self_reported_score.700_739': '700–739',
    'self_reported_score.660_699': '660–699',
    'self_reported_score.620_659': '620–659',
    'self_reported_score.580_619': '580–619',
    'self_reported_score.below_580': 'Below 580',
    'self_reported_score.not_sure': 'Not sure',
    'last_reviewed.last_30_days': 'In the last 30 days',
    'last_reviewed.last_6_months': 'In the last 6 months',
    'last_reviewed.last_year': 'In the last year',
    'last_reviewed.more_than_year': 'More than a year ago',
    'last_reviewed.never': 'Never',
    'last_reviewed.not_sure': 'Not sure',
    yes: 'Yes',
    no: 'No',
    not_sure: 'Not sure',
    'late_recent.none': 'None',
    'late_recent.30_days': 'About 30 days late',
    'late_recent.60_days': 'About 60 days late',
    'late_recent.90_plus': '90+ days late',
    'late_recent.not_sure': 'Not sure',
    'payment_consistency.on_time': 'On time',
    'payment_consistency.mostly_on_time': 'Mostly on time',
    'payment_consistency.missed_some': 'Missed some payments',
    'payment_consistency.currently_behind': 'Currently behind',
    'payment_consistency.not_sure': 'Not sure',
    'negative_items.collections': 'Collections',
    'negative_items.charge_offs': 'Charge-offs',
    'negative_items.repossession': 'Repossession',
    'negative_items.foreclosure': 'Foreclosure',
    'negative_items.bankruptcy': 'Bankruptcy',
    'negative_items.other_derogatory': 'Other derogatory items',
    'negative_items.none': 'None',
    'negative_items.not_sure': 'Not sure',
    'utilization.under_10': 'Under 10%',
    'utilization.10_30': '10–30%',
    'utilization.30_50': '30–50%',
    'utilization.50_75': '50–75%',
    'utilization.75_plus': '75%+',
    'utilization.maxed': 'Maxed out / near maxed',
    'utilization.not_sure': 'Not sure',
    'open_revolving.0': '0',
    'open_revolving.1_2': '1–2',
    'open_revolving.3_5': '3–5',
    'open_revolving.6_plus': '6+',
    'open_revolving.not_sure': 'Not sure',
    'oldest_account.under_2': 'Under 2 years',
    'oldest_account.2_5': '2–5 years',
    'oldest_account.5_10': '5–10 years',
    'oldest_account.10_plus': '10+ years',
    'oldest_account.not_sure': 'Not sure',
    'hard_inquiries.none': 'None',
    'hard_inquiries.1_2': '1–2',
    'hard_inquiries.3_5': '3–5',
    'hard_inquiries.6_plus': '6+',
    'hard_inquiries.not_sure': 'Not sure',
    'new_accounts.none': 'None',
    'new_accounts.one': 'One',
    'new_accounts.several': 'Several',
    'new_accounts.not_sure': 'Not sure',
    'minimums.comfortable': 'Comfortable',
    'minimums.sometimes_difficult': 'Sometimes difficult',
    'minimums.struggling': 'Struggling',
    'minimums.not_sure': 'Not sure',
    'current_status.current': 'No / current',
    'current_status.past_due': 'Yes / past due',
    'current_status.not_sure': 'Not sure',
    'urgency.asap': 'ASAP',
    'urgency.within_30_days': 'Within 30 days',
    'urgency.within_3_months': 'Within 3 months',
    'urgency.just_exploring': 'Just exploring',
    'prior_actions.self_disputes': 'Disputed items myself',
    'prior_actions.credit_counseling': 'Worked with credit counseling',
    'prior_actions.prior_repair_company': 'Worked with another credit repair company',
    'prior_actions.none': 'None',
    'prior_actions.not_sure': 'Not sure',
  },
  placeholders: {
    select: 'Select an option',
  },
  validation: {
    required: 'This field is required.',
    contact_required: 'Please complete your name, email, and phone number.',
  },
  ui: {
    welcomeTitle: 'Start Your Credit Report Card',
    welcomeBody:
      'Answer 10 focused questions about your credit profile and goals. Contact details come after the questions and are not part of the diagnostic.',
    welcomeNote:
      'We will never ask for your Social Security number, date of birth, bureau login, account numbers, or uploaded credit reports.',
    backToOverview: 'Back to Overview',
    back: 'Back',
    continue: 'Continue',
    viewResults: 'View My Credit Report Card',
    contactTitle: 'Contact & Acknowledgments',
    contactBody: 'Share how we can reach you. Required acknowledgments are marked with an asterisk.',
    firstName: 'First Name',
    lastName: 'Last Name',
    email: 'Email',
    phone: 'Phone',
    firstNamePlaceholder: 'First name',
    lastNamePlaceholder: 'Last name',
    emailPlaceholder: 'you@email.com',
    phonePlaceholder: '(555) 555-5555',
    consentIntro:
      'Your Credit Report Card is based on the information you shared. Required acknowledgments are marked with an asterisk.',
    ingestUnavailable:
      'Your answers were reviewed on this device. They were not sent to Valtoris CRM.',
    resultsUnavailable: 'Your Credit Report Card results are not available yet.',
    resultsLead:
      'Complete the Credit Report Card assessment to see your educational score, grade, and review areas.',
    backToLanding: 'Back to Credit Report Card',
    retake: 'Return to assessment',
    retakeCta: 'Retake Assessment',
    preparedFor: 'Prepared for',
    scoreOutOf: '{score} out of 100',
    nextStepSupport: 'Optional. This does not enroll you in credit-repair servicing or create a CRM Opportunity.',
    startCta: 'Get My Credit Report Card',
    productTitle: 'Credit Report Card',
    storageResultName: 'Credit Report Card',
    languageGroupLabel: 'Language',
    languageEnglish: 'English',
    languageSpanish: 'Español',
    stepIndicator: 'Step {current} of {total}',
    consentRequired: 'Please confirm the required acknowledgments before continuing.',
    consentHeading: 'Acknowledgments',
    consentStorage:
      'I understand that Valtoris will use the information I provide to calculate and store my {storageResultName} and related results.',
    consentStorageHint: 'Required acknowledgment to save and calculate your diagnostic.',
    consentStorageError:
      'Please acknowledge that your information will be used to calculate and store your diagnostic.',
    consentContact: 'I give Valtoris permission to contact me about my results and possible next steps.',
    consentEmailMarketing:
      'I agree to receive occasional marketing emails from Valtoris. I can unsubscribe at any time.',
    consentSms:
      'I agree to receive recurring marketing text messages from Valtoris at the number provided. Consent is not a condition of receiving my report. Message and data rates may apply. Reply STOP to opt out.',
    consentSmsPhoneNote: 'Add a phone number earlier in the assessment to enable this option.',
    consentPrivacyBefore: 'I acknowledge that I have reviewed the',
    consentPrivacyLink: 'Valtoris Privacy Policy',
    consentPrivacyAfter: '.',
    consentPrivacyHint: 'Required privacy acknowledgment. Opens the Privacy Policy in a new tab.',
    consentPrivacyError: 'Please review and acknowledge the Privacy Policy before continuing.',
    consentDisclaimer:
      'Results are educational estimates based on self-reported information. They are not a FICO® score, VantageScore®, bureau score, or lending decision, and they are not a guarantee that any item can be removed or that your score will increase.',
    consentHoneypot: 'Company website',
    landingEyebrow: 'VALTORIS CREDIT REPORT CARD',
    landingTitle: 'See What Areas of Your Credit Profile Deserve Attention',
    landingHero1:
      'Take the Valtoris Credit Report Card to organize self-reported payment, utilization, derogatory, and goal details.',
    landingHero2:
      'This is an educational diagnostic. It is not a FICO® score, VantageScore®, credit-bureau score, or lending approval.',
    landingHeroMicrocopy:
      'About 3–5 minutes. 10 diagnostic questions. No Social Security number. No bureau login. No cost to start.',
    landingReceiveHeading: "What You'll Receive",
    landingReceiveLead: 'What this specialized Report Card is designed to deliver.',
    landingReceiveScoreTitle: 'Credit Report Card Score',
    landingReceiveScoreDescription:
      'A Valtoris Credit Report Card Score — an educational 0–100 diagnostic based on your answers, not a bureau score.',
    landingReceiveFlagsTitle: 'Credit-Health Review Areas',
    landingReceiveFlagsDescription:
      'Meaningful areas that may deserve attention, based on your answers — without deletion or approval promises.',
    landingReceiveGoalTitle: 'Goal-Aligned Next Step',
    landingReceiveGoalDescription:
      'Your primary goal frames the later review. Completing this diagnostic does not create a CRM Opportunity.',
    landingReceiveSessionTitle: 'Optional Strategy Conversation',
    landingReceiveSessionDescription:
      'You can optionally review your answers with Valtoris later. This page does not sell credit-repair packages.',
    landingSampleHeading: 'Sample Report Preview',
    landingSampleLead: 'A structural look at later results. No fabricated score is shown.',
    landingSampleEyebrow: 'What you will see later',
    landingSampleTitle: 'Reserved result slots',
    landingSampleItem1: 'Credit Report Card Score and letter grade',
    landingSampleItem2: 'Category scores and critical review flags',
    landingSampleItem3: 'Up to three review areas and your primary goal',
    landingSampleItem4: 'An educational disclaimer and optional review next step',
    landingSampleMicrocopy: 'No sample score, letter grade, or points gained are invented on this page.',
    landingCategoriesHeading: 'What the 10 Questions Cover',
    landingCategoriesLead: 'Each group counts as one diagnostic question, including grouped follow-ups.',
    landingCategoryGoalTitle: 'Primary Goal',
    landingCategoryGoalDescription: 'Home, vehicle, rent, rates, business, rebuild, or general credit health.',
    landingCategoryScoreTitle: 'Self-Reported Range',
    landingCategoryScoreDescription:
      'A range you believe you are in, if you know. Context only — not an official score.',
    landingCategoryReviewTitle: 'Report Awareness',
    landingCategoryReviewDescription: 'When you last reviewed reports and whether anything looks inaccurate.',
    landingCategoryPaymentTitle: 'Payment Health',
    landingCategoryPaymentDescription: 'Recent late-payment severity and current payment consistency.',
    landingCategoryNegativeTitle: 'Negative Items',
    landingCategoryNegativeDescription:
      'Collections, charge-offs, and other derogatory items — without account numbers.',
    landingCategoryUtilizationTitle: 'Utilization and Structure',
    landingCategoryUtilizationDescription: 'Revolving use, open accounts, age, inquiries, and new accounts.',
    landingHowHeading: 'How It Works',
    landingHowLead: 'From 10 questions to a later scored report — without creating a CRM Opportunity automatically.',
    landingHow1Title: 'Answer 10 Questions',
    landingHow1Description:
      'Share self-reported credit details and your goal. Contact information is collected after the diagnostic.',
    landingHow2Title: 'Acknowledge Privacy',
    landingHow2Description: 'Required storage and privacy acknowledgments use the existing public consent controls.',
    landingHow3Title: 'See Your Results',
    landingHow3Description:
      'You receive a Credit Report Card Score, grade, flags, and up to three review areas based on your answers. This is educational, not a bureau score.',
    landingHow4Title: 'Optional Review',
    landingHow4Description:
      'A later conversation can review actual credit reports before any repair recommendation. No Opportunity is created automatically.',
    landingFaqHeading: 'Frequently Asked Questions',
    landingFaqLead: 'Straightforward answers before you begin.',
    landingFaq1: 'How long does the Credit Report Card take?',
    landingFaqA1: 'Most people finish the 10 diagnostic questions plus contact details in about 3–5 minutes.',
    landingFaq2: 'Will you ask for my Social Security number or bureau login?',
    landingFaqA2:
      'No. We never collect SSN, date of birth, bureau usernames or passwords, bank credentials, full account numbers, or report uploads.',
    landingFaq3: 'Is this my FICO or VantageScore?',
    landingFaqA3:
      'No. The reserved Credit Report Card Score is a Valtoris educational diagnostic based on your answers. It is not a FICO® score, VantageScore®, or any credit-bureau score.',
    landingFaq4: 'Will items be deleted or will my score go up?',
    landingFaqA4:
      'No. This diagnostic does not guarantee deletion, a score increase, approval, or a successful dispute. Accurate negative information may remain.',
    landingFaq5: 'Will someone contact me automatically?',
    landingFaqA5:
      'No automatic messages are sent from this foundation phase, and answers are not sent to CRM yet. Completing the questions does not enroll you in credit-repair servicing.',
    landingClosingTitle: 'Ready to Start Your Credit Report Card?',
    landingClosingCopy:
      'Answer 10 focused questions to see which areas of your credit profile may deserve attention.',
    landingClosingMicrocopy:
      'No bureau logins. No Social Security number. No deletion or score-increase promises.',
  },
  results: {
    score: 'Credit Report Card Score',
    grade: 'Grade',
    status: 'Status',
    categories: 'Category scores',
    flags: 'Critical review flags',
    topAreas: 'Top review areas',
    topAreas1: 'Top Area to Review',
    topAreas2: 'Top 2 Areas to Review',
    topAreas3: 'Top 3 Areas to Review',
    noReviewAreas: 'No immediate review areas were identified from your answers.',
    primaryGoal: 'Primary goal',
    bookingCta: 'Review My Results With Valtoris',
    reviewWithValtoris: 'Review My Results With Valtoris',
    unavailable: 'Your Credit Report Card results are not available yet.',
    disclaimer:
      'This Credit Report Card Score is a Valtoris educational assessment based on the answers you provided. It is not a FICO® score, VantageScore®, or any credit-bureau score, and it is not a lending decision. It does not guarantee that any item can be removed, that your score will increase, or that you will be approved for credit.',
    'status.strong': 'Strong',
    'status.solid': 'Solid',
    'status.review_recommended': 'Review Recommended',
    'status.needs_review': 'Needs Review',
    'status.high_priority': 'High Priority',
    'category.payment_history': 'Payment History',
    'category.negative_items': 'Negative Items',
    'category.utilization': 'Revolving Utilization',
    'category.financial_stability': 'Payment Manageability',
    'category.credit_structure': 'Credit Structure',
    'category.recent_credit': 'Recent Credit Activity',
    'category.report_review': 'Report Awareness',
    'category.self_reported_score': 'Self-Reported Range',
    'flag.immediate_review': 'Immediate Review',
    'flag.high_priority': 'High Priority',
    'flag.potential_opportunity': 'Potential Opportunity',
    'flag.review_recommended': 'Review Recommended',
    'review.flag_past_due.title': 'An account may currently be past due',
    'review.flag_past_due.body':
      'You reported that payments are currently behind or past due. This is a high-urgency review area based on your answers, not a lending decision.',
    'review.flag_severe_lates.title': 'Recent late payments deserve a closer look',
    'review.flag_severe_lates.body':
      'You reported a recent 60-day or 90+ day late payment. A review can help organize what to look at next on your actual reports.',
    'review.flag_recent_lates.title': 'Recent payment misses should be reviewed',
    'review.flag_recent_lates.body':
      'You reported a recent 30-day late payment or some missed payments. This flags the pattern for review.',
    'review.flag_severe_negatives.title': 'Serious negative items were reported',
    'review.flag_severe_negatives.body':
      'You reported repossession, foreclosure, or bankruptcy. These items deserve immediate review against your actual credit reports.',
    'review.flag_negative_items.title': 'Collections or charge-offs were reported',
    'review.flag_negative_items.body':
      'You reported collections or charge-offs. A review can help you understand which accounts to look at — without promising deletion or a score increase.',
    'review.flag_other_derogatory.title': 'Other derogatory items were reported',
    'review.flag_other_derogatory.body':
      'You reported other derogatory items. A review can help you identify what appears on your reports.',
    'review.flag_unknown_negatives.title': 'Negative-item status is unclear',
    'review.flag_unknown_negatives.body':
      'You are not sure whether negative items appear on your reports. Confirming that from the reports themselves is a useful next step.',
    'review.flag_high_utilization.title': 'Revolving utilization appears high',
    'review.flag_high_utilization.body':
      'You reported using a large share of available revolving credit. High utilization is a common review area and is not a bureau calculation.',
    'review.flag_elevated_utilization.title': 'Utilization may be elevated',
    'review.flag_elevated_utilization.body':
      'You reported revolving use in the 50–75% range. This is worth reviewing; it is not a predicted score change.',
    'review.flag_recent_applications.title': 'Recent applications or new accounts stand out',
    'review.flag_recent_applications.body':
      'You reported several hard inquiries or several recently opened accounts. Recent activity can be a useful review topic.',
    'review.flag_report_uncertainty.title': 'Credit-report awareness is limited',
    'review.flag_report_uncertainty.body':
      'You have not recently reviewed your credit reports, or you are not sure when you last did. Pulling your reports is a practical next step.',
    'review.flag_report_concern.title': 'A report-detail concern was noted',
    'review.flag_report_concern.body':
      'You believe something on your reports may need a closer look. This is a review opportunity, not a finding that any item is removable.',
    'review.flag_payment_strain.title': 'Minimum payments feel difficult',
    'review.flag_payment_strain.body':
      'You reported that minimum payments are currently a struggle. This is about manageability, not a lending decision.',
    'review.category.payment_history.title': 'Payment history should be reviewed',
    'review.category.payment_history.body':
      'Your reported late-payment or consistency details leave room for a closer look at payment history.',
    'review.category.negative_items.title': 'Negative items should be reviewed',
    'review.category.negative_items.body':
      'Your reported derogatory-item details should be checked against your actual reports.',
    'review.category.utilization.title': 'Utilization should be reviewed',
    'review.category.utilization.body':
      'Your reported revolving use leaves room to review balances relative to limits.',
    'review.category.financial_stability.title': 'Payment manageability should be reviewed',
    'review.category.financial_stability.body':
      'Your reported minimum-payment comfort or current status should be reviewed together.',
    'review.category.credit_structure.title': 'Account structure should be reviewed',
    'review.category.credit_structure.body':
      'Your mix of open revolving accounts or account age leaves room for a structural review.',
    'review.category.recent_credit.title': 'Recent credit activity should be reviewed',
    'review.category.recent_credit.body':
      'Recent inquiries or newly opened accounts should be reviewed against your reports.',
    'review.category.report_review.title': 'Report-review habits should be strengthened',
    'review.category.report_review.body':
      'More recent or more certain report review would make later recommendations more grounded.',
    'review.category.self_reported_score.title': 'Self-reported range is only context',
    'review.category.self_reported_score.body':
      'The range you reported is self-reported context only. It is not a FICO, Vantage, or bureau score.',
    'review.goal_timing.title': 'Your timing and goal should be reviewed together',
    'review.goal_timing.body':
      'You want a review soon for a time-sensitive goal. That timing is context for a conversation, not an approval or funding prediction.',
  },
}

export const creditCopy: SpecializedProductCopy = {
  en: CREDIT_COPY_EN,
  es: null,
}
