import type { SpecializedCopyCatalog, SpecializedProductCopy } from '../specialized/types'

const CREDIT_COPY_EN: SpecializedCopyCatalog = {
  questions: {
    credit_goal: 'What is the main reason you want a credit review?',
    self_reported_score: 'What credit score range do you believe you are in, if you know?',
    report_review: 'When did you last review your credit reports, and do you believe anything is wrong?',
    payment_history: 'How have recent payments gone?',
    negative_items: 'Which negative items, if any, do you believe are on your reports?',
    utilization: 'About how much of your available revolving credit are you currently using?',
    credit_structure: 'How many open revolving accounts do you have, and about how old is the oldest?',
    recent_credit: 'Have you had recent hard inquiries or newly opened accounts?',
    financial_stability: 'How manageable are your minimum payments, and are any accounts past due?',
    urgency_actions: 'How soon do you want a review, and have you already tried credit help?',
  },
  helpers: {
    credit_goal: 'Choose the primary reason. This helps frame later review areas.',
    self_reported_score:
      'This is self-reported and is not your official Credit Report Card Score. It is not a FICO®, VantageScore®, or bureau score.',
    report_review:
      'Think about Experian, Equifax, and TransUnion if you have seen them. You do not need to upload a report.',
    payment_history: 'There is no penalty for answering honestly. Recent lates and current consistency stay together.',
    negative_items:
      'Select every item you believe applies. Choose None if you do not believe any apply. Do not enter creditor names or account numbers.',
    utilization: 'An estimate is enough. This does not calculate a bureau score impact.',
    credit_structure: 'Use your best estimate. Account numbers are never needed.',
    recent_credit: 'Hard inquiries are requests that can appear after new credit applications.',
    financial_stability: 'This is about current manageability, not a lending decision.',
    urgency_actions: 'Select every prior action that applies. Choose None if you have not tried any.',
    inaccuracy_belief:
      'Inaccurate, duplicated, outdated, or not-yours items are a review concern — not a promise that anything can be removed.',
  },
  fields: {
    credit_goal: 'Primary goal',
    self_reported_score: 'Self-reported score range',
    last_reviewed: 'When did you last review your credit reports?',
    inaccuracy_belief:
      'Do you believe anything on your reports may be inaccurate, duplicated, outdated, or not yours?',
    late_recent: 'Recent late-payment severity',
    payment_consistency: 'Current payment consistency',
    negative_items: 'Negative items',
    utilization: 'Approximate revolving utilization',
    open_revolving: 'Open revolving accounts',
    oldest_account: 'Oldest open account',
    hard_inquiries: 'Recent hard inquiries',
    new_accounts: 'Recently opened accounts',
    minimums: 'How manageable are your minimum payments?',
    current_status: 'Are any accounts currently past due?',
    urgency: 'How soon do you want a review?',
    prior_actions: 'Previous credit actions',
  },
  answers: {
    'credit_goal.buy_home': 'Buy a home',
    'credit_goal.vehicle': 'Finance or refinance a vehicle',
    'credit_goal.rent': 'Rent a home or apartment',
    'credit_goal.lower_rates': 'Qualify for better rates',
    'credit_goal.business_financing': 'Business financing',
    'credit_goal.rebuild_credit': 'Rebuild my credit',
    'credit_goal.general_health': 'Improve my overall credit health',
    'self_reported_score.740_plus': '740+',
    'self_reported_score.700_739': '700–739',
    'self_reported_score.660_699': '660–699',
    'self_reported_score.620_659': '620–659',
    'self_reported_score.580_619': '580–619',
    'self_reported_score.below_580': 'Below 580',
    'self_reported_score.not_sure': 'Not sure',
    'last_reviewed.last_30_days': 'In the last 30 days',
    'last_reviewed.last_6_months': 'In the last 6 months',
    'last_reviewed.last_year': 'In the last year',
    'last_reviewed.more_than_year': 'More than a year ago',
    'last_reviewed.never': 'Never',
    'last_reviewed.not_sure': 'Not sure',
    yes: 'Yes',
    no: 'No',
    not_sure: 'Not sure',
    'late_recent.none': 'None',
    'late_recent.30_days': 'About 30 days late',
    'late_recent.60_days': 'About 60 days late',
    'late_recent.90_plus': '90+ days late',
    'late_recent.not_sure': 'Not sure',
    'payment_consistency.on_time': 'On time',
    'payment_consistency.mostly_on_time': 'Mostly on time',
    'payment_consistency.missed_some': 'Missed some payments',
    'payment_consistency.currently_behind': 'Currently behind',
    'payment_consistency.not_sure': 'Not sure',
    'negative_items.collections': 'Collections',
    'negative_items.charge_offs': 'Charge-offs',
    'negative_items.repossession': 'Repossession',
    'negative_items.foreclosure': 'Foreclosure',
    'negative_items.bankruptcy': 'Bankruptcy',
    'negative_items.other_derogatory': 'Other derogatory items',
    'negative_items.none': 'None',
    'negative_items.not_sure': 'Not sure',
    'utilization.under_10': 'Under 10%',
    'utilization.10_30': '10–30%',
    'utilization.30_50': '30–50%',
    'utilization.50_75': '50–75%',
    'utilization.75_plus': '75%+',
    'utilization.maxed': 'Maxed out / near maxed',
    'utilization.not_sure': 'Not sure',
    'open_revolving.0': '0',
    'open_revolving.1_2': '1–2',
    'open_revolving.3_5': '3–5',
    'open_revolving.6_plus': '6+',
    'open_revolving.not_sure': 'Not sure',
    'oldest_account.under_2': 'Under 2 years',
    'oldest_account.2_5': '2–5 years',
    'oldest_account.5_10': '5–10 years',
    'oldest_account.10_plus': '10+ years',
    'oldest_account.not_sure': 'Not sure',
    'hard_inquiries.none': 'None',
    'hard_inquiries.1_2': '1–2',
    'hard_inquiries.3_5': '3–5',
    'hard_inquiries.6_plus': '6+',
    'hard_inquiries.not_sure': 'Not sure',
    'new_accounts.none': 'None',
    'new_accounts.one': 'One',
    'new_accounts.several': 'Several',
    'new_accounts.not_sure': 'Not sure',
    'minimums.comfortable': 'Comfortable',
    'minimums.sometimes_difficult': 'Sometimes difficult',
    'minimums.struggling': 'Struggling',
    'minimums.not_sure': 'Not sure',
    'current_status.current': 'No / current',
    'current_status.past_due': 'Yes / past due',
    'current_status.not_sure': 'Not sure',
    'urgency.asap': 'ASAP',
    'urgency.within_30_days': 'Within 30 days',
    'urgency.within_3_months': 'Within 3 months',
    'urgency.just_exploring': 'Just exploring',
    'prior_actions.self_disputes': 'Disputed items myself',
    'prior_actions.credit_counseling': 'Worked with credit counseling',
    'prior_actions.prior_repair_company': 'Worked with another credit repair company',
    'prior_actions.none': 'None',
    'prior_actions.not_sure': 'Not sure',
  },
  placeholders: {
    select: 'Select an option',
  },
  validation: {
    required: 'This field is required.',
    contact_required: 'Please complete your name, email, and phone number.',
  },
  ui: {
    welcomeTitle: 'Start Your Credit Report Card',
    welcomeBody:
      'Answer 10 focused questions about your credit profile and goals. Contact details come after the questions and are not part of the diagnostic.',
    welcomeNote:
      'We will never ask for your Social Security number, date of birth, bureau login, account numbers, or uploaded credit reports.',
    backToOverview: 'Back to Overview',
    back: 'Back',
    continue: 'Continue',
    viewResults: 'View My Credit Report Card',
    contactTitle: 'Contact & Acknowledgments',
    contactBody: 'Share how we can reach you. Required acknowledgments are marked with an asterisk.',
    firstName: 'First Name',
    lastName: 'Last Name',
    email: 'Email',
    phone: 'Phone',
    firstNamePlaceholder: 'First name',
    lastNamePlaceholder: 'Last name',
    emailPlaceholder: 'you@email.com',
    phonePlaceholder: '(555) 555-5555',
    consentIntro:
      'Your Credit Report Card is based on the information you shared. Required acknowledgments are marked with an asterisk.',
    ingestUnavailable:
      'Your answers were reviewed on this device. They were not sent to Valtoris CRM.',
    saving: 'Saving your Credit Report Card…',
    submitFailed: 'We could not save your Credit Report Card. Please try again.',
    resultsUnavailable: 'Your Credit Report Card results are not available yet.',
    resultsLead:
      'Complete the Credit Report Card assessment to see your educational score, grade, and review areas.',
    backToLanding: 'Back to Credit Report Card',
    retake: 'Return to assessment',
    retakeCta: 'Retake Assessment',
    preparedFor: 'Prepared for',
    scoreOutOf: '{score} out of 100',
    nextStepSupport: 'Optional. This does not enroll you in credit-repair servicing or create a CRM Opportunity.',
    startCta: 'Get My Credit Report Card',
    productTitle: 'Credit Report Card',
    storageResultName: 'Credit Report Card',
    languageGroupLabel: 'Language',
    languageEnglish: 'English',
    languageSpanish: 'Español',
    stepIndicator: 'Step {current} of {total}',
    consentRequired: 'Please confirm the required acknowledgments before continuing.',
    consentHeading: 'Acknowledgments',
    consentStorage:
      'I understand that Valtoris will use the information I provide to calculate and store my {storageResultName} and related results.',
    consentStorageHint: 'Required acknowledgment to save and calculate your diagnostic.',
    consentStorageError:
      'Please acknowledge that your information will be used to calculate and store your diagnostic.',
    consentContact: 'I give Valtoris permission to contact me about my results and possible next steps.',
    consentEmailMarketing:
      'I agree to receive occasional marketing emails from Valtoris. I can unsubscribe at any time.',
    consentSms:
      'I agree to receive recurring marketing text messages from Valtoris at the number provided. Consent is not a condition of receiving my report. Message and data rates may apply. Reply STOP to opt out.',
    consentSmsPhoneNote: 'Add a phone number earlier in the assessment to enable this option.',
    consentPrivacyBefore: 'I acknowledge that I have reviewed the',
    consentPrivacyLink: 'Valtoris Privacy Policy',
    consentPrivacyAfter: '.',
    consentPrivacyHint: 'Required privacy acknowledgment. Opens the Privacy Policy in a new tab.',
    consentPrivacyError: 'Please review and acknowledge the Privacy Policy before continuing.',
    consentDisclaimer:
      'Results are educational estimates based on self-reported information. They are not a FICO® score, VantageScore®, bureau score, or lending decision, and they are not a guarantee that any item can be removed or that your score will increase.',
    consentHoneypot: 'Company website',
    landingEyebrow: 'VALTORIS CREDIT REPORT CARD',
    landingTitle: 'See What Areas of Your Credit Profile Deserve Attention',
    landingHero1:
      'Take the Valtoris Credit Report Card to organize self-reported payment, utilization, derogatory, and goal details.',
    landingHero2:
      'This is an educational diagnostic. It is not a FICO® score, VantageScore®, credit-bureau score, or lending approval.',
    landingHeroMicrocopy:
      'About 3–5 minutes. 10 diagnostic questions. No Social Security number. No bureau login. No cost to start.',
    landingReceiveHeading: "What You'll Receive",
    landingReceiveLead: 'What this specialized Report Card is designed to deliver.',
    landingReceiveScoreTitle: 'Credit Report Card Score',
    landingReceiveScoreDescription:
      'A Valtoris Credit Report Card Score — an educational 0–100 diagnostic based on your answers, not a bureau score.',
    landingReceiveFlagsTitle: 'Credit-Health Review Areas',
    landingReceiveFlagsDescription:
      'Meaningful areas that may deserve attention, based on your answers — without deletion or approval promises.',
    landingReceiveGoalTitle: 'Goal-Aligned Next Step',
    landingReceiveGoalDescription:
      'Your primary goal frames the later review. Completing this diagnostic does not create a CRM Opportunity.',
    landingReceiveSessionTitle: 'Optional Strategy Conversation',
    landingReceiveSessionDescription:
      'You can optionally review your answers with Valtoris later. This page does not sell credit-repair packages.',
    landingSampleHeading: 'Sample Report Preview',
    landingSampleLead: 'A structural look at later results. No fabricated score is shown.',
    landingSampleEyebrow: 'What you will see later',
    landingSampleTitle: 'Reserved result slots',
    landingSampleItem1: 'Credit Report Card Score and letter grade',
    landingSampleItem2: 'Category scores and critical review flags',
    landingSampleItem3: 'Up to three review areas and your primary goal',
    landingSampleItem4: 'An educational disclaimer and optional review next step',
    landingSampleMicrocopy: 'No sample score, letter grade, or points gained are invented on this page.',
    landingCategoriesHeading: 'What the 10 Questions Cover',
    landingCategoriesLead: 'Each group counts as one diagnostic question, including grouped follow-ups.',
    landingCategoryGoalTitle: 'Primary Goal',
    landingCategoryGoalDescription: 'Home, vehicle, rent, rates, business, rebuild, or general credit health.',
    landingCategoryScoreTitle: 'Self-Reported Range',
    landingCategoryScoreDescription:
      'A range you believe you are in, if you know. Context only — not an official score.',
    landingCategoryReviewTitle: 'Report Awareness',
    landingCategoryReviewDescription: 'When you last reviewed reports and whether anything looks inaccurate.',
    landingCategoryPaymentTitle: 'Payment Health',
    landingCategoryPaymentDescription: 'Recent late-payment severity and current payment consistency.',
    landingCategoryNegativeTitle: 'Negative Items',
    landingCategoryNegativeDescription:
      'Collections, charge-offs, and other derogatory items — without account numbers.',
    landingCategoryUtilizationTitle: 'Utilization and Structure',
    landingCategoryUtilizationDescription: 'Revolving use, open accounts, age, inquiries, and new accounts.',
    landingHowHeading: 'How It Works',
    landingHowLead: 'From 10 questions to a later scored report — without creating a CRM Opportunity automatically.',
    landingHow1Title: 'Answer 10 Questions',
    landingHow1Description:
      'Share self-reported credit details and your goal. Contact information is collected after the diagnostic.',
    landingHow2Title: 'Acknowledge Privacy',
    landingHow2Description: 'Required storage and privacy acknowledgments use the existing public consent controls.',
    landingHow3Title: 'See Your Results',
    landingHow3Description:
      'You receive a Credit Report Card Score, grade, flags, and up to three review areas based on your answers. This is educational, not a bureau score.',
    landingHow4Title: 'Optional Review',
    landingHow4Description:
      'A later conversation can review actual credit reports before any repair recommendation. No Opportunity is created automatically.',
    landingFaqHeading: 'Frequently Asked Questions',
    landingFaqLead: 'Straightforward answers before you begin.',
    landingFaq1: 'How long does the Credit Report Card take?',
    landingFaqA1: 'Most people finish the 10 diagnostic questions plus contact details in about 3–5 minutes.',
    landingFaq2: 'Will you ask for my Social Security number or bureau login?',
    landingFaqA2:
      'No. We never collect SSN, date of birth, bureau usernames or passwords, bank credentials, full account numbers, or report uploads.',
    landingFaq3: 'Is this my FICO or VantageScore?',
    landingFaqA3:
      'No. The reserved Credit Report Card Score is a Valtoris educational diagnostic based on your answers. It is not a FICO® score, VantageScore®, or any credit-bureau score.',
    landingFaq4: 'Will items be deleted or will my score go up?',
    landingFaqA4:
      'No. This diagnostic does not guarantee deletion, a score increase, approval, or a successful dispute. Accurate negative information may remain.',
    landingFaq5: 'Will someone contact me automatically?',
    landingFaqA5:
      'No automatic messages are sent. If you finish the assessment and agree to be contacted, Valtoris may follow up about your results. Completing the questions does not enroll you in credit-repair servicing.',
    landingClosingTitle: 'Ready to Start Your Credit Report Card?',
    landingClosingCopy:
      'Answer 10 focused questions to see which areas of your credit profile may deserve attention.',
    landingClosingMicrocopy:
      'No bureau logins. No Social Security number. No deletion or score-increase promises.',
  },
  results: {
    score: 'Credit Report Card Score',
    grade: 'Grade',
    status: 'Status',
    categories: 'Category scores',
    flags: 'Critical review flags',
    topAreas: 'Top review areas',
    topAreas1: 'Top Area to Review',
    topAreas2: 'Top 2 Areas to Review',
    topAreas3: 'Top 3 Areas to Review',
    noReviewAreas: 'No immediate review areas were identified from your answers.',
    primaryGoal: 'Primary goal',
    bookingCta: 'Review My Results With Valtoris',
    reviewWithValtoris: 'Review My Results With Valtoris',
    unavailable: 'Your Credit Report Card results are not available yet.',
    disclaimer:
      'This Credit Report Card Score is a Valtoris educational assessment based on the answers you provided. It is not a FICO® score, VantageScore®, or any credit-bureau score, and it is not a lending decision. It does not guarantee that any item can be removed, that your score will increase, or that you will be approved for credit.',
    'status.strong': 'Strong',
    'status.solid': 'Solid',
    'status.review_recommended': 'Review Recommended',
    'status.needs_review': 'Needs Review',
    'status.high_priority': 'High Priority',
    'category.payment_history': 'Payment History',
    'category.negative_items': 'Negative Items',
    'category.utilization': 'Revolving Utilization',
    'category.financial_stability': 'Payment Manageability',
    'category.credit_structure': 'Credit Structure',
    'category.recent_credit': 'Recent Credit Activity',
    'category.report_review': 'Report Awareness',
    'category.self_reported_score': 'Self-Reported Range',
    'flag.immediate_review': 'Immediate Review',
    'flag.high_priority': 'High Priority',
    'flag.potential_opportunity': 'Potential Opportunity',
    'flag.review_recommended': 'Review Recommended',
    'review.flag_past_due.title': 'An account may currently be past due',
    'review.flag_past_due.body':
      'You reported that payments are currently behind or past due. This is a high-urgency review area based on your answers, not a lending decision.',
    'review.flag_severe_lates.title': 'Recent late payments deserve a closer look',
    'review.flag_severe_lates.body':
      'You reported a recent 60-day or 90+ day late payment. A review can help organize what to look at next on your actual reports.',
    'review.flag_recent_lates.title': 'Recent payment misses should be reviewed',
    'review.flag_recent_lates.body':
      'You reported a recent 30-day late payment or some missed payments. This flags the pattern for review.',
    'review.flag_severe_negatives.title': 'Serious negative items were reported',
    'review.flag_severe_negatives.body':
      'You reported repossession, foreclosure, or bankruptcy. These items deserve immediate review against your actual credit reports.',
    'review.flag_negative_items.title': 'Collections or charge-offs were reported',
    'review.flag_negative_items.body':
      'You reported collections or charge-offs. A review can help you understand which accounts to look at — without promising deletion or a score increase.',
    'review.flag_other_derogatory.title': 'Other derogatory items were reported',
    'review.flag_other_derogatory.body':
      'You reported other derogatory items. A review can help you identify what appears on your reports.',
    'review.flag_unknown_negatives.title': 'Negative-item status is unclear',
    'review.flag_unknown_negatives.body':
      'You are not sure whether negative items appear on your reports. Confirming that from the reports themselves is a useful next step.',
    'review.flag_high_utilization.title': 'Revolving utilization appears high',
    'review.flag_high_utilization.body':
      'You reported using a large share of available revolving credit. High utilization is a common review area and is not a bureau calculation.',
    'review.flag_elevated_utilization.title': 'Utilization may be elevated',
    'review.flag_elevated_utilization.body':
      'You reported revolving use in the 50–75% range. This is worth reviewing; it is not a predicted score change.',
    'review.flag_recent_applications.title': 'Recent applications or new accounts stand out',
    'review.flag_recent_applications.body':
      'You reported several hard inquiries or several recently opened accounts. Recent activity can be a useful review topic.',
    'review.flag_report_uncertainty.title': 'Credit-report awareness is limited',
    'review.flag_report_uncertainty.body':
      'You have not recently reviewed your credit reports, or you are not sure when you last did. Pulling your reports is a practical next step.',
    'review.flag_report_concern.title': 'A report-detail concern was noted',
    'review.flag_report_concern.body':
      'You believe something on your reports may need a closer look. This is a review opportunity, not a finding that any item is removable.',
    'review.flag_payment_strain.title': 'Minimum payments feel difficult',
    'review.flag_payment_strain.body':
      'You reported that minimum payments are currently a struggle. This is about manageability, not a lending decision.',
    'review.category.payment_history.title': 'Payment history should be reviewed',
    'review.category.payment_history.body':
      'Your reported late-payment or consistency details leave room for a closer look at payment history.',
    'review.category.negative_items.title': 'Negative items should be reviewed',
    'review.category.negative_items.body':
      'Your reported derogatory-item details should be checked against your actual reports.',
    'review.category.utilization.title': 'Utilization should be reviewed',
    'review.category.utilization.body':
      'Your reported revolving use leaves room to review balances relative to limits.',
    'review.category.financial_stability.title': 'Payment manageability should be reviewed',
    'review.category.financial_stability.body':
      'Your reported minimum-payment comfort or current status should be reviewed together.',
    'review.category.credit_structure.title': 'Account structure should be reviewed',
    'review.category.credit_structure.body':
      'Your mix of open revolving accounts or account age leaves room for a structural review.',
    'review.category.recent_credit.title': 'Recent credit activity should be reviewed',
    'review.category.recent_credit.body':
      'Recent inquiries or newly opened accounts should be reviewed against your reports.',
    'review.category.report_review.title': 'Report-review habits should be strengthened',
    'review.category.report_review.body':
      'More recent or more certain report review would make later recommendations more grounded.',
    'review.category.self_reported_score.title': 'Self-reported range is only context',
    'review.category.self_reported_score.body':
      'The range you reported is self-reported context only. It is not a FICO, Vantage, or bureau score.',
    'review.goal_timing.title': 'Your timing and goal should be reviewed together',
    'review.goal_timing.body':
      'You want a review soon for a time-sensitive goal. That timing is context for a conversation, not an approval or funding prediction.',
  },
}

const CREDIT_COPY_ES: SpecializedCopyCatalog = {
  questions: {
    credit_goal: '¿Cuál es el motivo principal por el que desea una revisión de crédito?',
    self_reported_score: '¿En qué rango de puntaje de crédito cree que está, si lo sabe?',
    report_review: '¿Cuándo revisó por última vez sus reportes de crédito y cree que algo está mal?',
    payment_history: '¿Cómo le han ido los pagos recientes?',
    negative_items: '¿Qué elementos negativos, si alguno, cree que aparecen en sus reportes?',
    utilization: '¿Aproximadamente cuánto de su crédito revolvente disponible está usando ahora?',
    credit_structure: '¿Cuántas cuentas revolventes abiertas tiene y aproximadamente qué tan antigua es la más vieja?',
    recent_credit: '¿Ha tenido consultas duras recientes o cuentas recién abiertas?',
    financial_stability: '¿Qué tan manejables son sus pagos mínimos y hay alguna cuenta atrasada?',
    urgency_actions: '¿Qué tan pronto desea una revisión y ya ha intentado alguna ayuda de crédito?',
  },
  helpers: {
    credit_goal: 'Elija el motivo principal. Esto ayuda a enmarcar las áreas de revisión posteriores.',
    self_reported_score:
      'Esto es un rango que usted informa. No es un puntaje oficial de una agencia de crédito, FICO® ni VantageScore®, y no es el Puntaje del Reporte de Crédito de Valtoris.',
    report_review:
      'Piense en Experian, Equifax y TransUnion si los ha visto. No necesita subir un reporte.',
    payment_history: 'No hay penalidad por responder con honestidad. Los atrasos recientes y la consistencia actual van juntos.',
    negative_items:
      'Seleccione cada elemento que crea que aplica. Elija Ninguna si no cree que aplique ninguno. No escriba nombres de acreedores ni números de cuenta.',
    utilization:
      'Una estimación es suficiente. Indique, de forma aproximada, qué porcentaje de su crédito revolvente disponible está usando. Esto no calcula el impacto en un puntaje de agencia.',
    credit_structure: 'Use su mejor estimación. Nunca se necesitan números de cuenta.',
    recent_credit:
      'Las consultas duras son solicitudes que pueden aparecer después de pedir crédito nuevo. No toda consulta es dañina; esto solo ayuda a revisar la actividad reciente.',
    financial_stability: 'Esto trata de qué tan manejables son sus pagos ahora, no de una decisión de préstamo.',
    urgency_actions: 'Seleccione cada medida anterior que aplique. Elija Ninguna si no ha intentado ninguna.',
    inaccuracy_belief:
      'Los elementos inexactos, duplicados, desactualizados o que no son suyos son una preocupación para revisar — no una promesa de que se pueda eliminar algo.',
  },
  fields: {
    credit_goal: 'Meta principal',
    self_reported_score: 'Rango de puntaje que usted informa',
    last_reviewed: '¿Cuándo revisó por última vez sus reportes de crédito?',
    inaccuracy_belief:
      '¿Cree que algo en sus reportes puede ser inexacto, estar duplicado, estar desactualizado o no ser suyo?',
    late_recent: 'Severidad de atrasos recientes',
    payment_consistency: 'Consistencia actual de pagos',
    negative_items: 'Elementos negativos',
    utilization: 'Uso aproximado del crédito revolvente',
    open_revolving: 'Cuentas revolventes abiertas',
    oldest_account: 'Cuenta abierta más antigua',
    hard_inquiries: 'Consultas duras recientes',
    new_accounts: 'Cuentas recién abiertas',
    minimums: '¿Qué tan manejables son sus pagos mínimos?',
    current_status: '¿Hay alguna cuenta atrasada actualmente?',
    urgency: '¿Qué tan pronto desea una revisión?',
    prior_actions: 'Medidas de crédito anteriores',
  },
  answers: {
    'credit_goal.buy_home': 'Comprar una casa',
    'credit_goal.vehicle': 'Financiar o refinanciar un vehículo',
    'credit_goal.rent': 'Alquilar una casa o apartamento',
    'credit_goal.lower_rates': 'Calificar para mejores tasas',
    'credit_goal.business_financing': 'Financiamiento para negocio',
    'credit_goal.rebuild_credit': 'Reconstruir mi crédito',
    'credit_goal.general_health': 'Mejorar mi salud crediticia general',
    'self_reported_score.740_plus': '740+',
    'self_reported_score.700_739': '700–739',
    'self_reported_score.660_699': '660–699',
    'self_reported_score.620_659': '620–659',
    'self_reported_score.580_619': '580–619',
    'self_reported_score.below_580': 'Menos de 580',
    'self_reported_score.not_sure': 'No lo sé',
    'last_reviewed.last_30_days': 'En los últimos 30 días',
    'last_reviewed.last_6_months': 'En los últimos 6 meses',
    'last_reviewed.last_year': 'En el último año',
    'last_reviewed.more_than_year': 'Hace más de un año',
    'last_reviewed.never': 'Nunca',
    'last_reviewed.not_sure': 'No lo sé',
    yes: 'Sí',
    no: 'No',
    not_sure: 'No lo sé',
    'late_recent.none': 'Ninguno',
    'late_recent.30_days': 'Atraso de unos 30 días',
    'late_recent.60_days': 'Atraso de unos 60 días',
    'late_recent.90_plus': 'Atraso de 90 días o más',
    'late_recent.not_sure': 'No lo sé',
    'payment_consistency.on_time': 'A tiempo',
    'payment_consistency.mostly_on_time': 'Casi siempre a tiempo',
    'payment_consistency.missed_some': 'Falté a algunos pagos',
    'payment_consistency.currently_behind': 'Actualmente atrasado',
    'payment_consistency.not_sure': 'No lo sé',
    'negative_items.collections': 'Cobranzas',
    'negative_items.charge_offs': 'Cuentas dadas de baja (charge-offs)',
    'negative_items.repossession': 'Recuperación de un vehículo o bien',
    'negative_items.foreclosure': 'Ejecución hipotecaria',
    'negative_items.bankruptcy': 'Quiebra',
    'negative_items.other_derogatory': 'Otros elementos negativos',
    'negative_items.none': 'Ninguna',
    'negative_items.not_sure': 'No lo sé',
    'utilization.under_10': 'Menos del 10%',
    'utilization.10_30': '10–30%',
    'utilization.30_50': '30–50%',
    'utilization.50_75': '50–75%',
    'utilization.75_plus': '75%+',
    'utilization.maxed': 'Al máximo o casi al máximo',
    'utilization.not_sure': 'No lo sé',
    'open_revolving.0': '0',
    'open_revolving.1_2': '1–2',
    'open_revolving.3_5': '3–5',
    'open_revolving.6_plus': '6+',
    'open_revolving.not_sure': 'No lo sé',
    'oldest_account.under_2': 'Menos de 2 años',
    'oldest_account.2_5': '2–5 años',
    'oldest_account.5_10': '5–10 años',
    'oldest_account.10_plus': '10 años o más',
    'oldest_account.not_sure': 'No lo sé',
    'hard_inquiries.none': 'Ninguna',
    'hard_inquiries.1_2': '1–2',
    'hard_inquiries.3_5': '3–5',
    'hard_inquiries.6_plus': '6+',
    'hard_inquiries.not_sure': 'No lo sé',
    'new_accounts.none': 'Ninguna',
    'new_accounts.one': 'Una',
    'new_accounts.several': 'Varias',
    'new_accounts.not_sure': 'No lo sé',
    'minimums.comfortable': 'Cómodos',
    'minimums.sometimes_difficult': 'A veces difíciles',
    'minimums.struggling': 'Me cuesta cubrirlos',
    'minimums.not_sure': 'No lo sé',
    'current_status.current': 'No / al día',
    'current_status.past_due': 'Sí / atrasada',
    'current_status.not_sure': 'No lo sé',
    'urgency.asap': 'Lo antes posible',
    'urgency.within_30_days': 'En 30 días',
    'urgency.within_3_months': 'En 3 meses',
    'urgency.just_exploring': 'Solo estoy explorando',
    'prior_actions.self_disputes': 'Disputé elementos por mi cuenta',
    'prior_actions.credit_counseling': 'Trabajé con asesoría de crédito',
    'prior_actions.prior_repair_company': 'Trabajé con otra empresa de reparación de crédito',
    'prior_actions.none': 'Ninguna',
    'prior_actions.not_sure': 'No lo sé',
  },
  placeholders: {
    select: 'Seleccione una opción',
  },
  validation: {
    required: 'Este campo es obligatorio.',
    contact_required: 'Complete su nombre, correo electrónico y teléfono.',
  },
  ui: {
    welcomeTitle: 'Comience su Reporte de Crédito™',
    welcomeBody:
      'Responda 10 preguntas concretas sobre su perfil de crédito y sus metas. Los datos de contacto se piden después y no forman parte del diagnóstico.',
    welcomeNote:
      'Nunca le pediremos su número de Seguro Social, fecha de nacimiento, acceso a una agencia de crédito, números de cuenta ni reportes de crédito subidos.',
    backToOverview: 'Volver al resumen',
    back: 'Atrás',
    continue: 'Continuar',
    viewResults: 'Ver mi Reporte de Crédito',
    contactTitle: 'Contacto y reconocimientos',
    contactBody: 'Indique cómo podemos comunicarnos con usted. Los reconocimientos obligatorios están marcados con un asterisco.',
    firstName: 'Nombre',
    lastName: 'Apellido',
    email: 'Correo electrónico',
    phone: 'Teléfono',
    firstNamePlaceholder: 'Nombre',
    lastNamePlaceholder: 'Apellido',
    emailPlaceholder: 'usted@email.com',
    phonePlaceholder: '(555) 555-5555',
    consentIntro:
      'Su Reporte de Crédito™ se basa en la información que compartió. Los reconocimientos obligatorios están marcados con un asterisco.',
    ingestUnavailable:
      'Sus respuestas se revisaron en este dispositivo. No se enviaron al CRM de Valtoris.',
    saving: 'Guardando su Reporte de Crédito…',
    submitFailed: 'No pudimos guardar su Reporte de Crédito. Inténtelo de nuevo.',
    resultsUnavailable: 'Los resultados de su Reporte de Crédito aún no están disponibles.',
    resultsLead:
      'Complete la evaluación del Reporte de Crédito para ver su puntaje educativo, calificación y áreas de revisión.',
    backToLanding: 'Volver al Reporte de Crédito',
    retake: 'Volver a la evaluación',
    retakeCta: 'Repetir evaluación',
    preparedFor: 'Preparado para',
    scoreOutOf: '{score} de 100',
    nextStepSupport: 'Opcional. Esto no lo inscribe en un servicio de reparación de crédito ni crea una Oportunidad en el CRM.',
    startCta: 'Obtener mi Reporte de Crédito™',
    productTitle: 'Reporte de Crédito™',
    storageResultName: 'Reporte de Crédito',
    languageGroupLabel: 'Idioma',
    languageEnglish: 'English',
    languageSpanish: 'Español',
    stepIndicator: 'Paso {current} de {total}',
    consentRequired: 'Confirme los reconocimientos obligatorios antes de continuar.',
    consentHeading: 'Reconocimientos',
    consentStorage:
      'Entiendo que Valtoris usará la información que proporcione para calcular y guardar mi {storageResultName} y los resultados relacionados.',
    consentStorageHint: 'Reconocimiento obligatorio para guardar y calcular su diagnóstico.',
    consentStorageError:
      'Reconozca que su información se usará para calcular y guardar su diagnóstico.',
    consentContact: 'Autorizo a Valtoris a comunicarse conmigo sobre mis resultados y posibles siguientes pasos.',
    consentEmailMarketing:
      'Acepto recibir correos de marketing ocasionales de Valtoris. Puedo cancelar la suscripción en cualquier momento.',
    consentSms:
      'Acepto recibir mensajes de texto de marketing recurrentes de Valtoris al número indicado. El consentimiento no es una condición para recibir mi reporte. Pueden aplicarse tarifas de mensajes y datos. Responda STOP para cancelar.',
    consentSmsPhoneNote: 'Agregue un número de teléfono más arriba en la evaluación para activar esta opción.',
    consentPrivacyBefore: 'Reconozco que he revisado la',
    consentPrivacyLink: 'Política de privacidad de Valtoris',
    consentPrivacyAfter: '.',
    consentPrivacyHint: 'Reconocimiento de privacidad obligatorio. Abre la Política de privacidad en una pestaña nueva.',
    consentPrivacyError: 'Revise y reconozca la Política de privacidad antes de continuar.',
    consentDisclaimer:
      'Los resultados son estimaciones educativas basadas en información que usted informó. No son un puntaje FICO®, VantageScore®, de una agencia de crédito ni una decisión de préstamo, y no son una garantía de que se pueda eliminar algún elemento o de que su puntaje suba.',
    consentHoneypot: 'Sitio web de la empresa',
    landingEyebrow: 'REPORTE DE CRÉDITO™ DE VALTORIS',
    landingTitle: 'Descubra qué áreas de su perfil de crédito merecen atención',
    landingHero1:
      'Haga el Reporte de Crédito™ de Valtoris para organizar los detalles de pagos, uso del crédito, elementos negativos y metas que usted informa.',
    landingHero2:
      'Este es un diagnóstico educativo. No es un puntaje FICO®, VantageScore®, de una agencia de crédito ni una aprobación de préstamo.',
    landingHeroMicrocopy:
      'Unos 3–5 minutos. 10 preguntas de diagnóstico. Sin número de Seguro Social. Sin acceso a una agencia de crédito. Sin costo para comenzar.',
    landingReceiveHeading: 'Qué recibirá',
    landingReceiveLead: 'Lo que este Reporte especializado está diseñado para entregar.',
    landingReceiveScoreTitle: 'Puntaje del Reporte de Crédito',
    landingReceiveScoreDescription:
      'Un Puntaje del Reporte de Crédito de Valtoris: un diagnóstico educativo de 0 a 100 basado en sus respuestas, no un puntaje de agencia.',
    landingReceiveFlagsTitle: 'Áreas de revisión de la salud crediticia',
    landingReceiveFlagsDescription:
      'Áreas importantes que pueden merecer atención, según sus respuestas, sin promesas de eliminación ni de aprobación.',
    landingReceiveGoalTitle: 'Siguiente paso alineado a su meta',
    landingReceiveGoalDescription:
      'Su meta principal enmarca la revisión posterior. Completar este diagnóstico no crea una Oportunidad en el CRM.',
    landingReceiveSessionTitle: 'Conversación opcional de estrategia',
    landingReceiveSessionDescription:
      'Si lo desea, puede revisar sus respuestas con Valtoris más adelante. Esta página no vende paquetes de reparación de crédito.',
    landingSampleHeading: 'Vista previa del reporte',
    landingSampleLead: 'Una mirada a la estructura de los resultados posteriores. No se muestra un puntaje inventado.',
    landingSampleEyebrow: 'Lo que verá más adelante',
    landingSampleTitle: 'Espacios reservados para resultados',
    landingSampleItem1: 'Puntaje del Reporte de Crédito y calificación con letra',
    landingSampleItem2: 'Puntajes por categoría y señales críticas de revisión',
    landingSampleItem3: 'Hasta tres áreas de revisión y su meta principal',
    landingSampleItem4: 'Un descargo educativo y un siguiente paso opcional de revisión',
    landingSampleMicrocopy: 'En esta página no se inventa un puntaje, una calificación ni puntos ganados de muestra.',
    landingCategoriesHeading: 'Qué cubren las 10 preguntas',
    landingCategoriesLead: 'Cada grupo cuenta como una pregunta de diagnóstico, incluidas las preguntas de seguimiento.',
    landingCategoryGoalTitle: 'Meta principal',
    landingCategoryGoalDescription: 'Casa, vehículo, alquiler, tasas, negocio, reconstruir o salud crediticia general.',
    landingCategoryScoreTitle: 'Rango que usted informa',
    landingCategoryScoreDescription:
      'Un rango en el que cree que está, si lo sabe. Solo contexto: no es un puntaje oficial.',
    landingCategoryReviewTitle: 'Conocimiento del reporte',
    landingCategoryReviewDescription: 'Cuándo revisó los reportes por última vez y si algo parece inexacto.',
    landingCategoryPaymentTitle: 'Salud de los pagos',
    landingCategoryPaymentDescription: 'Severidad de atrasos recientes y consistencia actual de pagos.',
    landingCategoryNegativeTitle: 'Elementos negativos',
    landingCategoryNegativeDescription:
      'Cobranzas, cuentas dadas de baja y otros elementos negativos, sin números de cuenta.',
    landingCategoryUtilizationTitle: 'Uso y estructura del crédito',
    landingCategoryUtilizationDescription: 'Uso revolvente, cuentas abiertas, antigüedad, consultas y cuentas nuevas.',
    landingHowHeading: 'Cómo funciona',
    landingHowLead: 'Desde 10 preguntas hasta un reporte con puntaje posterior, sin crear automáticamente una Oportunidad en el CRM.',
    landingHow1Title: 'Responda 10 preguntas',
    landingHow1Description:
      'Comparta detalles de crédito que usted informa y su meta. La información de contacto se pide después del diagnóstico.',
    landingHow2Title: 'Reconozca la privacidad',
    landingHow2Description: 'Los reconocimientos obligatorios de almacenamiento y privacidad usan los controles públicos actuales.',
    landingHow3Title: 'Vea sus resultados',
    landingHow3Description:
      'Recibe un Puntaje del Reporte de Crédito, calificación, señales y hasta tres áreas de revisión según sus respuestas. Esto es educativo, no un puntaje de agencia.',
    landingHow4Title: 'Revisión opcional',
    landingHow4Description:
      'Una conversación posterior puede revisar los reportes de crédito reales antes de cualquier recomendación de reparación. No se crea una Oportunidad automáticamente.',
    landingFaqHeading: 'Preguntas frecuentes',
    landingFaqLead: 'Respuestas claras antes de comenzar.',
    landingFaq1: '¿Cuánto tarda el Reporte de Crédito?',
    landingFaqA1: 'La mayoría de las personas termina las 10 preguntas de diagnóstico y los datos de contacto en unos 3–5 minutos.',
    landingFaq2: '¿Me pedirán mi número de Seguro Social o el acceso a una agencia de crédito?',
    landingFaqA2:
      'No. Nunca pedimos SSN, fecha de nacimiento, usuarios o contraseñas de agencias de crédito, credenciales bancarias, números de cuenta completos ni reportes subidos.',
    landingFaq3: '¿Este es mi FICO o VantageScore?',
    landingFaqA3:
      'No. El Puntaje del Reporte de Crédito es un diagnóstico educativo de Valtoris basado en sus respuestas. No es un puntaje FICO®, VantageScore® ni de una agencia de crédito.',
    landingFaq4: '¿Se eliminarán elementos o subirá mi puntaje?',
    landingFaqA4:
      'No. Este diagnóstico no garantiza eliminación, un aumento de puntaje, una aprobación ni el éxito de una disputa. La información negativa precisa puede permanecer.',
    landingFaq5: '¿Alguien me contactará automáticamente?',
    landingFaqA5:
      'No se envían mensajes automáticos. Si termina la evaluación y acepta que lo contactemos, Valtoris puede darle seguimiento sobre sus resultados. Completar las preguntas no lo inscribe en un servicio de reparación de crédito.',
    landingClosingTitle: '¿Listo para comenzar su Reporte de Crédito™?',
    landingClosingCopy:
      'Responda 10 preguntas concretas para ver qué áreas de su perfil de crédito pueden merecer atención.',
    landingClosingMicrocopy:
      'Sin accesos a agencias de crédito. Sin número de Seguro Social. Sin promesas de eliminación ni de aumento de puntaje.',
  },
  results: {
    score: 'Puntaje del Reporte de Crédito',
    grade: 'Calificación',
    status: 'Estado',
    categories: 'Puntajes por categoría',
    flags: 'Señales críticas de revisión',
    topAreas: 'Áreas principales de revisión',
    topAreas1: 'Área principal para revisar',
    topAreas2: '2 áreas principales para revisar',
    topAreas3: '3 áreas principales para revisar',
    noReviewAreas: 'No se identificaron áreas inmediatas que requieran revisión según sus respuestas.',
    primaryGoal: 'Meta principal',
    bookingCta: 'Revisar mis resultados con Valtoris',
    reviewWithValtoris: 'Revisar mis resultados con Valtoris',
    unavailable: 'Los resultados de su Reporte de Crédito aún no están disponibles.',
    disclaimer:
      'Este Puntaje del Reporte de Crédito es una evaluación educativa de Valtoris basada en las respuestas que usted dio. No es un puntaje FICO®, VantageScore® ni un puntaje de una agencia de crédito, y no es una decisión de préstamo. No garantiza que se pueda eliminar ningún elemento, que su puntaje suba, que lo aprueben para crédito ni que una disputa tenga éxito. La información negativa precisa puede permanecer. Se deben revisar los reportes de crédito reales antes de recomendar acciones de reparación. Valtoris no es una agencia de crédito.',
    'status.strong': 'Fuerte',
    'status.solid': 'Sólido',
    'status.review_recommended': 'Se recomienda revisión',
    'status.needs_review': 'Necesita revisión',
    'status.high_priority': 'Alta prioridad',
    'category.payment_history': 'Historial de pagos',
    'category.negative_items': 'Elementos negativos',
    'category.utilization': 'Uso del crédito',
    'category.financial_stability': 'Estabilidad financiera',
    'category.credit_structure': 'Estructura del crédito',
    'category.recent_credit': 'Crédito reciente',
    'category.report_review': 'Revisión del reporte',
    'category.self_reported_score': 'Puntaje reportado por usted',
    'flag.immediate_review': 'Revisión inmediata',
    'flag.high_priority': 'Alta prioridad',
    'flag.potential_opportunity': 'Oportunidad potencial',
    'flag.review_recommended': 'Se recomienda revisión',
    'review.flag_past_due.title': 'Una cuenta puede estar atrasada actualmente',
    'review.flag_past_due.body':
      'Usted indicó que los pagos están atrasados o vencidos ahora. Esta es un área de revisión de alta urgencia según sus respuestas, no una decisión de préstamo.',
    'review.flag_severe_lates.title': 'Los atrasos recientes merecen una mirada más cercana',
    'review.flag_severe_lates.body':
      'Usted indicó un atraso reciente de 60 días o de 90 días o más. Una revisión puede ayudar a organizar qué revisar después en sus reportes reales.',
    'review.flag_recent_lates.title': 'Los atrasos recientes de pago deben revisarse',
    'review.flag_recent_lates.body':
      'Usted indicó un atraso reciente de 30 días o algunos pagos faltantes. Esto señala el patrón para revisión.',
    'review.flag_severe_negatives.title': 'Se informaron elementos negativos serios',
    'review.flag_severe_negatives.body':
      'Usted indicó recuperación de un bien, ejecución hipotecaria o quiebra. Estos elementos merecen revisión inmediata frente a sus reportes de crédito reales.',
    'review.flag_negative_items.title': 'Se informaron cobranzas o cuentas dadas de baja',
    'review.flag_negative_items.body':
      'Usted indicó cobranzas o cuentas dadas de baja. Una revisión puede ayudar a entender qué cuentas revisar, sin prometer eliminación ni un aumento de puntaje.',
    'review.flag_other_derogatory.title': 'Se informaron otros elementos negativos',
    'review.flag_other_derogatory.body':
      'Usted indicó otros elementos negativos. Una revisión puede ayudar a identificar qué aparece en sus reportes.',
    'review.flag_unknown_negatives.title': 'El estado de los elementos negativos no está claro',
    'review.flag_unknown_negatives.body':
      'No está seguro de si aparecen elementos negativos en sus reportes. Confirmarlo en los reportes mismos es un siguiente paso útil.',
    'review.flag_high_utilization.title': 'El uso del crédito revolvente parece alto',
    'review.flag_high_utilization.body':
      'Usted indicó que usa una gran parte de su crédito revolvente disponible. El uso alto es un área común de revisión y no es un cálculo de agencia.',
    'review.flag_elevated_utilization.title': 'El uso del crédito puede estar elevado',
    'review.flag_elevated_utilization.body':
      'Usted indicó un uso revolvente en el rango de 50–75%. Vale la pena revisarlo; no es un cambio de puntaje previsto.',
    'review.flag_recent_applications.title': 'Las solicitudes o cuentas nuevas recientes destacan',
    'review.flag_recent_applications.body':
      'Usted indicó varias consultas duras o varias cuentas recién abiertas. La actividad reciente puede ser un tema útil de revisión.',
    'review.flag_report_uncertainty.title': 'El conocimiento de los reportes de crédito es limitado',
    'review.flag_report_uncertainty.body':
      'No ha revisado recientemente sus reportes de crédito o no está seguro de cuándo lo hizo por última vez. Obtener sus reportes es un siguiente paso práctico.',
    'review.flag_report_concern.title': 'Posible área del reporte para revisar',
    'review.flag_report_concern.body':
      'Usted cree que algo en sus reportes puede merecer una mirada más cercana. Esta es una oportunidad de revisión, no un hallazgo de que algún elemento se pueda eliminar.',
    'review.flag_payment_strain.title': 'Los pagos mínimos se sienten difíciles',
    'review.flag_payment_strain.body':
      'Usted indicó que ahora le cuesta cubrir los pagos mínimos. Esto trata de qué tan manejables son, no de una decisión de préstamo.',
    'review.category.payment_history.title': 'El historial de pagos debe revisarse',
    'review.category.payment_history.body':
      'Los atrasos o la consistencia que indicó dejan espacio para una mirada más cercana al historial de pagos.',
    'review.category.negative_items.title': 'Los elementos negativos deben revisarse',
    'review.category.negative_items.body':
      'Los elementos negativos que indicó deben comprobarse frente a sus reportes reales.',
    'review.category.utilization.title': 'El uso del crédito debe revisarse',
    'review.category.utilization.body':
      'El uso revolvente que indicó deja espacio para revisar los saldos en relación con los límites.',
    'review.category.financial_stability.title': 'La estabilidad financiera debe revisarse',
    'review.category.financial_stability.body':
      'La comodidad con los pagos mínimos o el estado actual que indicó deben revisarse juntos.',
    'review.category.credit_structure.title': 'La estructura de las cuentas debe revisarse',
    'review.category.credit_structure.body':
      'La mezcla de cuentas revolventes abiertas o la antigüedad deja espacio para una revisión estructural.',
    'review.category.recent_credit.title': 'La actividad reciente de crédito debe revisarse',
    'review.category.recent_credit.body':
      'Las consultas recientes o las cuentas recién abiertas deben revisarse frente a sus reportes.',
    'review.category.report_review.title': 'Los hábitos de revisión del reporte deben fortalecerse',
    'review.category.report_review.body':
      'Una revisión más reciente o más segura de los reportes haría que las recomendaciones posteriores estén mejor fundamentadas.',
    'review.category.self_reported_score.title': 'El rango que usted informa es solo contexto',
    'review.category.self_reported_score.body':
      'El rango que indicó es solo contexto que usted informa. No es un puntaje FICO, Vantage ni de una agencia de crédito.',
    'review.goal_timing.title': 'Su plazo y su meta deben revisarse juntos',
    'review.goal_timing.body':
      'Desea una revisión pronto por una meta con fecha. Ese plazo es contexto para una conversación, no una predicción de aprobación ni de financiamiento.',
  },
}

export const creditCopy: SpecializedProductCopy = {
  en: CREDIT_COPY_EN,
  es: CREDIT_COPY_ES,
}
