import type { SpecializedCopyCatalog, SpecializedProductCopy } from '../specialized/types'

const STUDENT_LOAN_COPY_EN: SpecializedCopyCatalog = {
  questions: {
    loan_types: 'What types of student loans do you have?',
    total_balance: 'What is your approximate total student loan balance?',
    loan_status: 'What is the current status of your student loans?',
    loan_servicer: 'Who services your student loans?',
    repayment_plan: 'What repayment plan are you on, if you know it?',
    income_household: 'What is your income and household size?',
    employment: 'What best describes your employment?',
    payment_history: 'How have your recent student loan payments gone?',
    previous_actions: 'Have you already taken any of these actions?',
    goal_urgency: 'What is your primary goal, and how soon do you want a review?',
  },
  helpers: {
    loan_types: 'Select every type that applies. Choose Not sure if you do not know.',
    total_balance: 'An estimate is enough. This does not change whether you can get a review.',
    loan_status: 'Choose the status that best matches most of your loans today.',
    loan_servicer:
      'Enter the name on your statements. Do not enter account numbers, passwords, or FSA login details.',
    repayment_plan:
      'If you know the plan name, we will ask which one. You can report a current plan or a legacy plan you are still associated with. You can also say you are not sure.',
    income_household: 'Use your best estimate of annual income and how many people you support.',
    employment: 'Employment type can help an advisor know which programs may be worth discussing later.',
    payment_history: 'There is no penalty for answering honestly. This helps flag urgent situations.',
    previous_actions: 'Select every action you have already tried. Choose None if you have not taken any.',
    goal_urgency: 'This helps an advisor start from what matters most to you.',
    servicer_name: 'Company name only — never an account number or login.',
    current_plan:
      'Choose the closest name on your account or statements. Selecting a plan does not mean you are eligible for it or that it is open for new enrollment.',
    employment_tenure: 'About how long have you been in this type of work?',
    payment_paused: 'Include any current pause, forbearance, or administrative forbearance.',
  },
  fields: {
    loan_types: 'Loan types',
    total_balance: 'Total balance',
    loan_status: 'Loan status',
    servicer_mode: 'Do you know your servicer?',
    servicer_name: 'Servicer name',
    knows_plan: 'Do you know your repayment plan?',
    current_plan: 'Current or recent repayment plan',
    income: 'Approximate annual income',
    household_size: 'Household size',
    employment_type: 'Employment type',
    employment_tenure: 'Time in this work',
    payment_recent: 'Recent payment history',
    payment_paused: 'Are your payments currently paused?',
    previous_actions: 'Previous actions',
    primary_goal: 'Primary goal',
    urgency: 'How soon do you want a review?',
  },
  answers: {
    'loan_types.direct': 'Federal Direct Loan',
    'loan_types.ffelp': 'FFELP (older federal loans)',
    'loan_types.parent_plus': 'Parent PLUS',
    'loan_types.private': 'Private student loan',
    'loan_types.not_sure': 'Not sure',
    'total_balance.under_25k': 'Under $25,000',
    'total_balance.25k_50k': '$25,000–$50,000',
    'total_balance.50k_100k': '$50,000–$100,000',
    'total_balance.over_100k': 'Over $100,000',
    'total_balance.not_sure': 'Not sure',
    'loan_status.repayment': 'In repayment',
    'loan_status.deferment_forbearance': 'Deferment or forbearance',
    'loan_status.delinquent': 'Delinquent',
    'loan_status.default': 'In default',
    'loan_status.not_sure': 'Not sure',
    'servicer_mode.named': 'I know the servicer name',
    'servicer_mode.not_sure': 'Not sure',
    yes: 'Yes',
    no: 'No',
    not_sure: 'Not sure',
    'current_plan.rap': 'Repayment Assistance Plan (RAP)',
    'current_plan.tiered_standard': 'Tiered Standard',
    'current_plan.standard': 'Standard repayment',
    'current_plan.ibr': 'Income-Based Repayment (IBR)',
    'current_plan.paye': 'Pay As You Earn (PAYE)',
    'current_plan.icr': 'Income-Contingent Repayment (ICR)',
    'current_plan.save': 'SAVE (legacy / transitioning)',
    'current_plan.repaye': 'REPAYE (legacy plan)',
    'current_plan.other': 'Other plan',
    'current_plan.not_sure': 'Not sure',
    'income.under_40k': 'Under $40,000',
    'income.40k_75k': '$40,000–$75,000',
    'income.75k_125k': '$75,000–$125,000',
    'income.125k_200k': '$125,000–$200,000',
    'income.200k_plus': '$200,000 or more',
    'income.not_sure': 'Not sure',
    'household_size.1': '1',
    'household_size.2': '2',
    'household_size.3': '3',
    'household_size.4': '4',
    'household_size.5_plus': '5 or more',
    'employment_type.government': 'Government',
    'employment_type.nonprofit': 'Nonprofit',
    'employment_type.private': 'Private sector',
    'employment_type.self_employed': 'Self-employed',
    'employment_type.not_employed': 'Not currently employed',
    'employment_tenure.under_1': 'Under 1 year',
    'employment_tenure.1_5': '1–5 years',
    'employment_tenure.5_10': '5–10 years',
    'employment_tenure.10_plus': '10 or more years',
    'payment_recent.consistent': 'Consistent on-time payments',
    'payment_recent.missed_some': 'Missed some payments',
    'payment_recent.difficult_to_afford': 'Difficult to afford',
    'payment_recent.not_currently_required': 'Payments not currently required',
    'payment_recent.have_not_been_paying': 'Have not been paying',
    'payment_recent.not_sure': 'Not sure',
    'previous_actions.idr': 'Income-driven repayment (IDR)',
    'previous_actions.pslf': 'Public Service Loan Forgiveness (PSLF)',
    'previous_actions.federal_consolidation': 'Federal consolidation',
    'previous_actions.private_refinancing': 'Private refinancing',
    'previous_actions.borrower_defense': 'Borrower defense to repayment',
    'previous_actions.none': 'None',
    'previous_actions.not_sure': 'Not sure',
    'primary_goal.lower_payment': 'Lower my payment',
    'primary_goal.forgiveness_review': 'Review forgiveness options',
    'primary_goal.exit_delinquency_default': 'Get out of delinquency or default',
    'primary_goal.pay_off_faster': 'Pay off faster',
    'primary_goal.prepare_home': 'Prepare for a home purchase',
    'primary_goal.understand_options': 'Understand my options',
    'urgency.asap': 'As soon as possible',
    'urgency.within_30_days': 'Within 30 days',
    'urgency.within_3_months': 'Within 3 months',
    'urgency.just_exploring': 'Just exploring',
  },
  placeholders: {
    select: 'Select an option',
    servicer_name: 'Servicer name',
  },
  validation: {
    required: 'This field is required.',
    servicer_length: 'Servicer name must be 80 characters or fewer.',
    contact_required: 'Please complete your name, email, and phone number.',
  },
  ui: {
    welcomeTitle: 'Start Your Student Loan Report Card™',
    welcomeBody:
      'Answer 10 focused questions about your loans, payments, and goals. Contact details come after the questions and are not part of the diagnostic.',
    welcomeNote:
      'We will never ask for your Social Security number, FSA login, date of birth, or loan account number.',
    backToOverview: 'Back to Overview',
    continue: 'Continue',
    viewResults: 'View My Student Loan Report Card',
    saving: 'Saving your Student Loan Report Card…',
    contactTitle: 'Contact & Acknowledgments',
    contactBody: 'Share how we can reach you. Required acknowledgments are marked with an asterisk.',
    firstName: 'First Name',
    lastName: 'Last Name',
    email: 'Email',
    phone: 'Phone',
    firstNamePlaceholder: 'First name',
    lastNamePlaceholder: 'Last name',
    emailPlaceholder: 'you@email.com',
    phonePlaceholder: '(555) 555-5555',
    consentIntro:
      'Your Student Loan Report Card™ is based on the information you shared. Required acknowledgments are marked with an asterisk.',
    ingestUnavailable:
      'Your results were calculated on this device. They were not sent to Valtoris CRM.',
    resultsUnavailable: 'Your Student Loan Report Card results are not available yet.',
    resultsLead:
      'Complete the Student Loan Report Card assessment to see your score, grade, and review areas.',
    backToLanding: 'Back to Student Loan Report Card',
    retake: 'Return to assessment',
    retakeCta: 'Retake Assessment',
    preparedFor: 'Prepared for',
    thanks: 'Thanks',
    informationalBalance: 'Reported balance range',
    servicer: 'Reported servicer',
    urgency: 'Review timing',
    nextStepSupport:
      'Review your Student Loan Report Card™ with Valtoris. A conversation can check these answers against your actual loan records and current federal rules.',
  },
  results: {
    score: 'Student Loan Report Card Score',
    grade: 'Grade',
    status: 'Status',
    categories: 'Category scores',
    flags: 'Critical review flags',
    topAreas: 'Top review areas',
    topAreas1: 'Top Area to Review',
    topAreas2: 'Top 2 Areas to Review',
    topAreas3: 'Top 3 Areas to Review',
    noReviewAreas: 'No immediate review areas were identified from your answers.',
    primaryGoal: 'Primary goal',
    bookingCta: 'Review My Results With Valtoris',
    reviewWithValtoris: 'Review My Results With Valtoris',
    unavailable: 'Your Student Loan Report Card results are not available yet.',
    disclaimer:
      'This Student Loan Report Card Score is a Valtoris educational assessment based on the answers you provided. It is not a government determination and does not guarantee eligibility, forgiveness, approval, savings, or a particular payment. Valtoris is not the U.S. Department of Education or a federal loan servicer. Program eligibility and repayment options depend on your actual loan records and current federal rules.',
    officialResourceLead: 'Official federal student-loan information is available at',
    officialResourceLink: 'StudentAid.gov',
    officialResourceAfter: '. Federal Student Aid operates that site; Valtoris does not.',
    'status.optimized': 'Optimized',
    'status.strong': 'Strong',
    'status.opportunities': 'Opportunities Exist',
    'status.needs_review': 'Needs Review',
    'status.high_priority': 'High Priority',
    'category.status_stability': 'Loan Status & Payment Stability',
    'category.repayment_strategy': 'Repayment Strategy',
    'category.forgiveness_optimization': 'Forgiveness / Program Review',
    'category.knowledge_structure': 'Loan Knowledge & Structure',
    'category.goal_alignment': 'Goal Alignment',
    'flag.immediate_review': 'Immediate Review',
    'flag.high_priority': 'High Priority',
    'flag.potential_opportunity': 'Potential Opportunity / Review Recommended',
    'flag.review_recommended': 'Review Recommended',
    'review.flag_default.title': 'Default status needs immediate review',
    'review.flag_default.body':
      'You reported that your loans are in default. This is a high-urgency situation and should be reviewed against your actual loan records.',
    'review.flag_delinquent.title': 'Delinquency is a high-priority review',
    'review.flag_delinquent.body':
      'You reported that your loans are delinquent. A review can help you understand current status and possible next steps.',
    'review.flag_difficult_payments.title': 'Current payments appear difficult to afford',
    'review.flag_difficult_payments.body':
      'You reported difficulty affording your current payments. This does not determine a new payment amount; it flags the situation for review.',
    'review.flag_pslf_unreviewed.title': 'Public-service employment without a PSLF review',
    'review.flag_pslf_unreviewed.body':
      'You reported public-service employment but no prior PSLF review. This is a review opportunity, not a determination that you qualify.',
    'review.flag_unknown_loan_type.title': 'Loan type is unclear',
    'review.flag_unknown_loan_type.body':
      'Your current loan type is unclear and should be reviewed. Knowing the loan type helps frame later options.',
    'review.flag_unknown_plan.title': 'Repayment plan is unclear',
    'review.flag_unknown_plan.body':
      'Your current repayment plan is unclear and should be reviewed.',
    'review.category.status_stability.title': 'Payment stability should be reviewed',
    'review.category.status_stability.body':
      'Your reported status or recent payment pattern leaves room for a closer look at stability.',
    'review.category.repayment_strategy.title': 'Repayment strategy should be reviewed',
    'review.category.repayment_strategy.body':
      'Your current repayment plan knowledge is incomplete and should be reviewed.',
    'review.category.forgiveness_optimization.title': 'Program-review awareness can be improved',
    'review.category.forgiveness_optimization.body':
      'A review can check whether any program options are relevant. This is not an eligibility finding.',
    'review.category.knowledge_structure.title': 'Loan details are incomplete',
    'review.category.knowledge_structure.body':
      'Some core loan details are unknown. Clearing those up helps a later review stay accurate.',
    'review.category.goal_alignment.title': 'Goal and current status should be reviewed together',
    'review.category.goal_alignment.body':
      'Your stated goal and current loan situation should be reviewed together. This does not predict approval or a specific outcome.',
  },
}

export const studentLoanCopy: SpecializedProductCopy = {
  en: STUDENT_LOAN_COPY_EN,
  es: null,
}
