import type { SpecializedCopyCatalog, SpecializedProductCopy } from '../specialized/types'

const STUDENT_LOAN_COPY_EN: SpecializedCopyCatalog = {
  questions: {
    loan_types: 'What types of student loans do you have?',
    total_balance: 'What is your approximate total student loan balance?',
    loan_status: 'What is the current status of your student loans?',
    loan_servicer: 'Who services your student loans?',
    repayment_plan: 'What repayment plan are you on, if you know it?',
    income_household: 'What is your income and household size?',
    employment: 'What best describes your employment?',
    payment_history: 'How have your recent student loan payments gone?',
    previous_actions: 'Have you already taken any of these actions?',
    goal_urgency: 'What is your primary goal, and how soon do you want a review?',
  },
  helpers: {
    loan_types: 'Select every type that applies. Choose Not sure if you do not know.',
    total_balance: 'An estimate is enough. This does not change whether you can get a review.',
    loan_status: 'Choose the status that best matches most of your loans today.',
    loan_servicer:
      'Enter the name on your statements. Do not enter account numbers, passwords, or FSA login details.',
    repayment_plan:
      'If you know the plan name, we will ask which one. You can report a current plan or a legacy plan you are still associated with. You can also say you are not sure.',
    income_household: 'Use your best estimate of annual income and how many people you support.',
    employment: 'Employment type can help an advisor know which programs may be worth discussing later.',
    payment_history: 'There is no penalty for answering honestly. This helps flag urgent situations.',
    previous_actions: 'Select every action you have already tried. Choose None if you have not taken any.',
    goal_urgency: 'This helps an advisor start from what matters most to you.',
    servicer_name: 'Company name only — never an account number or login.',
    current_plan:
      'Choose the closest name on your account or statements. Selecting a plan does not mean you are eligible for it or that it is open for new enrollment.',
    employment_tenure: 'About how long have you been in this type of work?',
    payment_paused: 'Include any current pause, forbearance, or administrative forbearance.',
  },
  fields: {
    loan_types: 'Loan types',
    total_balance: 'Total balance',
    loan_status: 'Loan status',
    servicer_mode: 'Do you know your servicer?',
    servicer_name: 'Servicer name',
    knows_plan: 'Do you know your repayment plan?',
    current_plan: 'Current or recent repayment plan',
    income: 'Approximate annual income',
    household_size: 'Household size',
    employment_type: 'Employment type',
    employment_tenure: 'Time in this work',
    payment_recent: 'Recent payment history',
    payment_paused: 'Are your payments currently paused?',
    previous_actions: 'Previous actions',
    primary_goal: 'Primary goal',
    urgency: 'How soon do you want a review?',
  },
  answers: {
    'loan_types.direct': 'Federal Direct Loan',
    'loan_types.ffelp': 'FFELP (older federal loans)',
    'loan_types.parent_plus': 'Parent PLUS',
    'loan_types.private': 'Private student loan',
    'loan_types.not_sure': 'Not sure',
    'total_balance.under_25k': 'Under $25,000',
    'total_balance.25k_50k': '$25,000–$50,000',
    'total_balance.50k_100k': '$50,000–$100,000',
    'total_balance.over_100k': 'Over $100,000',
    'total_balance.not_sure': 'Not sure',
    'loan_status.repayment': 'In repayment',
    'loan_status.deferment_forbearance': 'Deferment or forbearance',
    'loan_status.delinquent': 'Delinquent',
    'loan_status.default': 'In default',
    'loan_status.not_sure': 'Not sure',
    'servicer_mode.named': 'I know the servicer name',
    'servicer_mode.not_sure': 'Not sure',
    yes: 'Yes',
    no: 'No',
    not_sure: 'Not sure',
    'current_plan.rap': 'Repayment Assistance Plan (RAP)',
    'current_plan.tiered_standard': 'Tiered Standard',
    'current_plan.standard': 'Standard repayment',
    'current_plan.ibr': 'Income-Based Repayment (IBR)',
    'current_plan.paye': 'Pay As You Earn (PAYE)',
    'current_plan.icr': 'Income-Contingent Repayment (ICR)',
    'current_plan.save': 'SAVE (legacy / transitioning)',
    'current_plan.repaye': 'REPAYE (legacy plan)',
    'current_plan.other': 'Other plan',
    'current_plan.not_sure': 'Not sure',
    'income.under_40k': 'Under $40,000',
    'income.40k_75k': '$40,000–$75,000',
    'income.75k_125k': '$75,000–$125,000',
    'income.125k_200k': '$125,000–$200,000',
    'income.200k_plus': '$200,000 or more',
    'income.not_sure': 'Not sure',
    'household_size.1': '1',
    'household_size.2': '2',
    'household_size.3': '3',
    'household_size.4': '4',
    'household_size.5_plus': '5 or more',
    'employment_type.government': 'Government',
    'employment_type.nonprofit': 'Nonprofit',
    'employment_type.private': 'Private sector',
    'employment_type.self_employed': 'Self-employed',
    'employment_type.not_employed': 'Not currently employed',
    'employment_tenure.under_1': 'Under 1 year',
    'employment_tenure.1_5': '1–5 years',
    'employment_tenure.5_10': '5–10 years',
    'employment_tenure.10_plus': '10 or more years',
    'payment_recent.consistent': 'Consistent on-time payments',
    'payment_recent.missed_some': 'Missed some payments',
    'payment_recent.difficult_to_afford': 'Difficult to afford',
    'payment_recent.not_currently_required': 'Payments not currently required',
    'payment_recent.have_not_been_paying': 'Have not been paying',
    'payment_recent.not_sure': 'Not sure',
    'previous_actions.idr': 'Income-driven repayment (IDR)',
    'previous_actions.pslf': 'Public Service Loan Forgiveness (PSLF)',
    'previous_actions.federal_consolidation': 'Federal consolidation',
    'previous_actions.private_refinancing': 'Private refinancing',
    'previous_actions.borrower_defense': 'Borrower defense to repayment',
    'previous_actions.none': 'None',
    'previous_actions.not_sure': 'Not sure',
    'primary_goal.lower_payment': 'Lower my payment',
    'primary_goal.forgiveness_review': 'Review forgiveness options',
    'primary_goal.exit_delinquency_default': 'Get out of delinquency or default',
    'primary_goal.pay_off_faster': 'Pay off faster',
    'primary_goal.prepare_home': 'Prepare for a home purchase',
    'primary_goal.understand_options': 'Understand my options',
    'urgency.asap': 'As soon as possible',
    'urgency.within_30_days': 'Within 30 days',
    'urgency.within_3_months': 'Within 3 months',
    'urgency.just_exploring': 'Just exploring',
  },
  placeholders: {
    select: 'Select an option',
    servicer_name: 'Servicer name',
  },
  validation: {
    required: 'This field is required.',
    servicer_length: 'Servicer name must be 80 characters or fewer.',
    contact_required: 'Please complete your name, email, and phone number.',
  },
  ui: {
    welcomeTitle: 'Start Your Student Loan Report Card™',
    welcomeBody:
      'Complete the Student Loan Report Card about your loans, payments, and goals. Contact details come after the diagnostic and are not part of the score.',
    backToOverview: 'Back to Overview',
    back: 'Back',
    continue: 'Continue',
    viewResults: 'View My Student Loan Report Card',
    saving: 'Saving your Student Loan Report Card…',
    contactTitle: 'Contact & Acknowledgments',
    contactBody: 'Share how we can reach you. Required acknowledgments are marked with an asterisk.',
    firstName: 'First Name',
    lastName: 'Last Name',
    email: 'Email',
    phone: 'Phone',
    firstNamePlaceholder: 'First name',
    lastNamePlaceholder: 'Last name',
    emailPlaceholder: 'you@email.com',
    phonePlaceholder: '(555) 555-5555',
    consentIntro:
      'Your Student Loan Report Card™ is based on the information you shared. Required acknowledgments are marked with an asterisk.',
    ingestUnavailable:
      'Your results were calculated on this device. They were not sent to Valtoris CRM.',
    resultsUnavailable: 'Your Student Loan Report Card results are not available yet.',
    resultsLead:
      'Complete the Student Loan Report Card assessment to see your score, grade, and review areas.',
    backToLanding: 'Back to Student Loan Report Card',
    retake: 'Return to assessment',
    retakeCta: 'Retake Assessment',
    preparedFor: 'Prepared for',
    thanks: 'Thanks',
    informationalBalance: 'Reported balance range',
    servicer: 'Reported servicer',
    urgency: 'Review timing',
    nextStepSupport:
      'Review your Student Loan Report Card™ with Valtoris. A conversation can check these answers against your actual loan records and current federal rules.',
    startCta: 'Start My Student Loan Report Card™',
    productTitle: 'Student Loan Report Card™',
    storageResultName: 'Student Loan Report Card',
    languageGroupLabel: 'Language',
    languageEnglish: 'English',
    languageSpanish: 'Español',
    stepIndicator: 'Step {current} of {total}',
    scoreOutOf: '{score} out of 100',
    consentRequired: 'Please confirm the required acknowledgments before viewing your report.',
    submitFailed: 'We could not save your Student Loan Report Card. Please try again.',
    consentHeading: 'Acknowledgments',
    consentStorage:
      'I understand that Valtoris will use the information I provide to calculate and store my {storageResultName} and related results.',
    consentStorageHint: 'Required acknowledgment to save and calculate your diagnostic.',
    consentStorageError:
      'Please acknowledge that your information will be used to calculate and store your diagnostic.',
    consentContact: 'I give Valtoris permission to contact me about my results and possible next steps.',
    consentEmailMarketing:
      'I agree to receive occasional marketing emails from Valtoris. I can unsubscribe at any time.',
    consentSms:
      'I agree to receive recurring marketing text messages from Valtoris at the number provided. Consent is not a condition of receiving my report. Message and data rates may apply. Reply STOP to opt out.',
    consentSmsPhoneNote: 'Add a phone number earlier in the assessment to enable this option.',
    consentPrivacyBefore: 'I acknowledge that I have reviewed the',
    consentPrivacyLink: 'Valtoris Privacy Policy',
    consentPrivacyAfter: '.',
    consentPrivacyHint: 'Required privacy acknowledgment. Opens the Privacy Policy in a new tab.',
    consentPrivacyError: 'Please review and acknowledge the Privacy Policy before continuing.',
    consentDisclaimer:
      'Results are educational estimates based on self-reported information. They are not financial, legal, tax, investment, credit, or insurance advice, and they are not a guarantee. An advisor review may reach different conclusions.',
    consentHoneypot: 'Company website',
    landingEyebrow: 'VALTORIS STUDENT LOAN REPORT CARD™',
    landingTitle: 'Get Clarity on Your Student Loans',
    landingHero1:
      'Understand where you stand with your student loans and what areas may deserve attention.',
    landingHero2:
      'The Student Loan Report Card™ helps organize your repayment situation, identify potential concerns, and prepare you for a more informed strategy conversation.',
    landingReceiveHeading: "What You'll Receive",
    landingReceiveLead: 'What this specialized Report Card is designed to deliver.',
    landingReceiveScoreTitle: 'Student Loan Report Card Score',
    landingReceiveScoreDescription:
      'A 0–100 Valtoris Student Loan Report Card Score and letter grade that summarize loan status, repayment strategy, and review priorities. Large balances are not penalized.',
    landingReceiveFlagsTitle: 'Review Flags and Top Areas',
    landingReceiveFlagsDescription:
      'Critical situations such as default or delinquency appear as review flags, separately from the numeric score.',
    landingReceiveGoalTitle: 'Goal-Aligned Next Step',
    landingReceiveGoalDescription:
      'Your primary goal and urgency frame the recommended review. This is educational, not an eligibility determination.',
    landingReceiveSessionTitle: 'Optional Strategy Conversation',
    landingReceiveSessionDescription:
      'You can optionally review your results in a complimentary conversation. Completing the assessment does not create a CRM Opportunity.',
    landingSampleHeading: 'Sample Report Preview',
    landingSampleLead:
      'An example of the report layout. Sample values are labeled as examples and are not your results.',
    landingSampleBadge: 'Sample / Example',
    landingSampleAriaLabel: 'Example Student Loan Report Card preview',
    landingSampleFlagHeading: 'Example review flag',
    landingSampleFlagTitle: 'Repayment plan knowledge may need a closer look',
    landingSampleReviewHeading: 'Example review areas',
    landingSampleReview1: 'Repayment strategy may deserve a closer look',
    landingSampleReview2: 'Program options may be worth reviewing',
    landingSampleReview3: 'Loan details may be incomplete',
    landingSampleDisclaimer:
      'Example only. These sample values are not your Student Loan Report Card Score and do not diagnose your loans.',
    landingCompliance:
      'Valtoris is not the U.S. Department of Education and is not affiliated with or endorsed by the federal government. This diagnostic is educational and does not guarantee eligibility, forgiveness, approval, savings, or a particular payment. Official federal student-loan information is available at StudentAid.gov.',
    landingCategoriesHeading: 'What the Report Card Covers',
    landingCategoriesLead: 'Each group counts as one diagnostic question, including grouped follow-ups.',
    landingCategoryStructureTitle: 'Loan Structure',
    landingCategoryStructureDescription:
      'Loan types, balance range, and servicer awareness — without account numbers or FSA credentials.',
    landingCategoryStatusTitle: 'Status and Stability',
    landingCategoryStatusDescription:
      'Repayment, deferment, delinquency, or default status, weighted for stability — not loan size.',
    landingCategoryRepaymentTitle: 'Repayment Strategy',
    landingCategoryRepaymentDescription:
      'Whether you know your current or recent repayment plan, using current federal plan names plus legacy options borrowers may still report.',
    landingCategoryIncomeTitle: 'Income and Household',
    landingCategoryIncomeDescription: 'Income band and household size for later income-driven review context.',
    landingCategoryEmploymentTitle: 'Employment Context',
    landingCategoryEmploymentDescription:
      'Government, nonprofit, private, self-employed, or not employed — plus tenure when relevant.',
    landingCategoryPaymentTitle: 'Payment History',
    landingCategoryPaymentDescription: 'Recent payment pattern and whether payments are currently paused.',
    landingHowHeading: 'How It Works',
    landingHowLead:
      'From your first answers to a scored report — without creating a CRM Opportunity automatically.',
    landingHow1Title: 'Complete the Assessment',
    landingHow1Description:
      'Share loan, payment, and goal details. Contact information is collected after the diagnostic.',
    landingHow2Title: 'Acknowledge Privacy',
    landingHow2Description: 'Required storage and privacy acknowledgments use the existing public consent controls.',
    landingHow3Title: 'See Your Results',
    landingHow3Description:
      'Your score, grade, flags, and top review areas are calculated from your answers on this device.',
    landingHow4Title: 'Optional Review',
    landingHow4Description:
      'Book a complimentary review if you want to walk through the results. No Opportunity is created automatically.',
    landingFaqHeading: 'Frequently Asked Questions',
    landingFaqLead: 'Straightforward answers before you begin.',
    landingFaq1: 'How long does the Student Loan Report Card take?',
    landingFaqA1: 'Most people finish the assessment, including contact details, in a few minutes.',
    landingFaq2: 'Will you ask for my FSA login or Social Security number?',
    landingFaqA2:
      'No. We never collect SSN, date of birth, FSA credentials, loan account numbers, or document uploads.',
    landingFaq3: 'Do I get a score today?',
    landingFaqA3:
      'Yes. You receive a Valtoris Student Loan Report Card Score, grade, flags, and review areas after you complete the assessment and acknowledgments.',
    landingFaq4: 'Is this an eligibility or forgiveness approval?',
    landingFaqA4:
      'No. This is an educational diagnostic. Valtoris is not the U.S. Department of Education or a federal loan servicer, and it is not affiliated with or endorsed by the federal government. It does not determine eligibility, payment amounts, forgiveness, or savings. Official federal student-loan information is available at StudentAid.gov.',
    landingFaq5: 'Will someone contact me automatically?',
    landingFaqA5:
      'No automatic messages are sent. If you finish the assessment and agree to be contacted, Valtoris may follow up about your results. Completing the questions does not enroll you in a federal program.',
    landingClosingTitle: 'Ready to Start Your Student Loan Report Card™?',
    landingClosingCopy: 'Complete the Student Loan Report Card and receive your Valtoris Student Loan Report Card Score.',
    landingClosingMicrocopy:
      'No account numbers. No FSA credentials. Required privacy acknowledgments stay explicit.',
  },
  results: {
    score: 'Student Loan Report Card Score',
    grade: 'Grade',
    status: 'Status',
    categories: 'Category scores',
    flags: 'Critical review flags',
    topAreas: 'Top review areas',
    topAreas1: 'Top Area to Review',
    topAreas2: 'Top 2 Areas to Review',
    topAreas3: 'Top 3 Areas to Review',
    noReviewAreas: 'No immediate review areas were identified from your answers.',
    primaryGoal: 'Primary goal',
    bookingCta: 'Review My Results With Valtoris',
    reviewWithValtoris: 'Review My Results With Valtoris',
    unavailable: 'Your Student Loan Report Card results are not available yet.',
    disclaimer:
      'This Student Loan Report Card Score is a Valtoris educational assessment based on the answers you provided. It is not a government determination and does not guarantee eligibility, forgiveness, approval, savings, or a particular payment. Valtoris is not the U.S. Department of Education or a federal loan servicer. Program eligibility and repayment options depend on your actual loan records and current federal rules.',
    officialResourceLead: 'Official federal student-loan information is available at',
    officialResourceLink: 'StudentAid.gov',
    officialResourceAfter: '. Federal Student Aid operates that site; Valtoris does not.',
    'status.optimized': 'Optimized',
    'status.strong': 'Strong',
    'status.opportunities': 'Opportunities Exist',
    'status.needs_review': 'Needs Review',
    'status.high_priority': 'High Priority',
    'category.status_stability': 'Loan Status & Payment Stability',
    'category.repayment_strategy': 'Repayment Strategy',
    'category.forgiveness_optimization': 'Forgiveness / Program Review',
    'category.knowledge_structure': 'Loan Knowledge & Structure',
    'category.goal_alignment': 'Goal Alignment',
    'flag.immediate_review': 'Immediate Review',
    'flag.high_priority': 'High Priority',
    'flag.potential_opportunity': 'Potential Opportunity / Review Recommended',
    'flag.review_recommended': 'Review Recommended',
    'review.flag_default.title': 'Default status needs immediate review',
    'review.flag_default.body':
      'You reported that your loans are in default. This is a high-urgency situation and should be reviewed against your actual loan records.',
    'review.flag_delinquent.title': 'Delinquency is a high-priority review',
    'review.flag_delinquent.body':
      'You reported that your loans are delinquent. A review can help you understand current status and possible next steps.',
    'review.flag_difficult_payments.title': 'Current payments appear difficult to afford',
    'review.flag_difficult_payments.body':
      'You reported difficulty affording your current payments. This does not determine a new payment amount; it flags the situation for review.',
    'review.flag_pslf_unreviewed.title': 'Public-service employment without a PSLF review',
    'review.flag_pslf_unreviewed.body':
      'You reported public-service employment but no prior PSLF review. This is a review opportunity, not a determination that you qualify.',
    'review.flag_unknown_loan_type.title': 'Loan type is unclear',
    'review.flag_unknown_loan_type.body':
      'Your current loan type is unclear and should be reviewed. Knowing the loan type helps frame later options.',
    'review.flag_unknown_plan.title': 'Repayment plan is unclear',
    'review.flag_unknown_plan.body':
      'Your current repayment plan is unclear and should be reviewed.',
    'review.category.status_stability.title': 'Payment stability should be reviewed',
    'review.category.status_stability.body':
      'Your reported status or recent payment pattern leaves room for a closer look at stability.',
    'review.category.repayment_strategy.title': 'Repayment strategy should be reviewed',
    'review.category.repayment_strategy.body':
      'Your current repayment plan knowledge is incomplete and should be reviewed.',
    'review.category.forgiveness_optimization.title': 'Program-review awareness can be improved',
    'review.category.forgiveness_optimization.body':
      'A review can check whether any program options are relevant. This is not an eligibility finding.',
    'review.category.knowledge_structure.title': 'Loan details are incomplete',
    'review.category.knowledge_structure.body':
      'Some core loan details are unknown. Clearing those up helps a later review stay accurate.',
    'review.category.goal_alignment.title': 'Goal and current status should be reviewed together',
    'review.category.goal_alignment.body':
      'Your stated goal and current loan situation should be reviewed together. This does not predict approval or a specific outcome.',
  },
}

const STUDENT_LOAN_COPY_ES: SpecializedCopyCatalog = {
  questions: {
    loan_types: '¿Qué tipos de préstamos estudiantiles tiene?',
    total_balance: '¿Cuál es el saldo aproximado total de sus préstamos estudiantiles?',
    loan_status: '¿Cuál es el estado actual de sus préstamos estudiantiles?',
    loan_servicer: '¿Quién administra sus préstamos estudiantiles?',
    repayment_plan: '¿En qué plan de pago está, si lo sabe?',
    income_household: '¿Cuáles son sus ingresos y el tamaño de su hogar?',
    employment: '¿Qué describe mejor su empleo?',
    payment_history: '¿Cómo le han ido los pagos recientes de sus préstamos estudiantiles?',
    previous_actions: '¿Ya ha tomado alguna de estas medidas?',
    goal_urgency: '¿Cuál es su meta principal y qué tan pronto desea una revisión?',
  },
  helpers: {
    loan_types: 'Seleccione todos los tipos que correspondan. Elija No lo sé si no está seguro.',
    total_balance: 'Una estimación es suficiente. Esto no cambia si puede obtener una revisión.',
    loan_status: 'Elija el estado que mejor describa la mayoría de sus préstamos hoy.',
    loan_servicer:
      'Escriba el nombre que aparece en sus estados de cuenta. No escriba números de cuenta, contraseñas ni datos de acceso de FSA.',
    repayment_plan:
      'Si conoce el nombre del plan, le preguntaremos cuál es. Puede indicar un plan actual o un plan anterior con el que todavía esté asociado. También puede decir que no lo sabe.',
    income_household: 'Use su mejor estimación de ingresos anuales y de cuántas personas depende.',
    employment: 'El tipo de empleo puede ayudar a un asesor a saber qué programas convendría revisar más adelante.',
    payment_history: 'No hay penalidad por responder con honestidad. Esto ayuda a identificar situaciones urgentes.',
    previous_actions: 'Seleccione cada medida que ya haya intentado. Elija Ninguna si no ha tomado ninguna.',
    goal_urgency: 'Esto ayuda a un asesor a comenzar por lo que más le importa.',
    servicer_name: 'Solo el nombre de la empresa — nunca un número de cuenta ni un acceso.',
    current_plan:
      'Elija el nombre más cercano al de su cuenta o estados de cuenta. Elegir un plan no significa que usted califique para él ni que esté abierto a nuevas inscripciones.',
    employment_tenure: '¿Aproximadamente cuánto tiempo lleva en este tipo de trabajo?',
    payment_paused: 'Incluya cualquier pausa actual, forbearance o forbearance administrativo.',
  },
  fields: {
    loan_types: 'Tipos de préstamo',
    total_balance: 'Saldo total',
    loan_status: 'Estado del préstamo',
    servicer_mode: '¿Conoce a su administrador de préstamos?',
    servicer_name: 'Nombre del administrador',
    knows_plan: '¿Conoce su plan de pago?',
    current_plan: 'Plan de pago actual o reciente',
    income: 'Ingresos anuales aproximados',
    household_size: 'Tamaño del hogar',
    employment_type: 'Tipo de empleo',
    employment_tenure: 'Tiempo en este trabajo',
    payment_recent: 'Historial de pagos recientes',
    payment_paused: '¿Están sus pagos pausados actualmente?',
    previous_actions: 'Medidas anteriores',
    primary_goal: 'Meta principal',
    urgency: '¿Qué tan pronto desea una revisión?',
  },
  answers: {
    'loan_types.direct': 'Préstamo Directo Federal',
    'loan_types.ffelp': 'FFELP (préstamos federales anteriores)',
    'loan_types.parent_plus': 'Parent PLUS',
    'loan_types.private': 'Préstamo estudiantil privado',
    'loan_types.not_sure': 'No lo sé',
    'total_balance.under_25k': 'Menos de $25,000',
    'total_balance.25k_50k': '$25,000–$50,000',
    'total_balance.50k_100k': '$50,000–$100,000',
    'total_balance.over_100k': 'Más de $100,000',
    'total_balance.not_sure': 'No lo sé',
    'loan_status.repayment': 'En pago',
    'loan_status.deferment_forbearance': 'Aplazamiento o forbearance',
    'loan_status.delinquent': 'En mora',
    'loan_status.default': 'En incumplimiento (default)',
    'loan_status.not_sure': 'No lo sé',
    'servicer_mode.named': 'Conozco el nombre del administrador',
    'servicer_mode.not_sure': 'No lo sé',
    yes: 'Sí',
    no: 'No',
    not_sure: 'No lo sé',
    'current_plan.rap': 'Repayment Assistance Plan (RAP)',
    'current_plan.tiered_standard': 'Tiered Standard',
    'current_plan.standard': 'Standard repayment',
    'current_plan.ibr': 'Income-Based Repayment (IBR)',
    'current_plan.paye': 'Pay As You Earn (PAYE)',
    'current_plan.icr': 'Income-Contingent Repayment (ICR)',
    'current_plan.save': 'SAVE (programa anterior / en transición)',
    'current_plan.repaye': 'REPAYE (plan anterior)',
    'current_plan.other': 'Otro plan',
    'current_plan.not_sure': 'No lo sé',
    'income.under_40k': 'Menos de $40,000',
    'income.40k_75k': '$40,000–$75,000',
    'income.75k_125k': '$75,000–$125,000',
    'income.125k_200k': '$125,000–$200,000',
    'income.200k_plus': '$200,000 o más',
    'income.not_sure': 'No lo sé',
    'household_size.1': '1',
    'household_size.2': '2',
    'household_size.3': '3',
    'household_size.4': '4',
    'household_size.5_plus': '5 o más',
    'employment_type.government': 'Gobierno',
    'employment_type.nonprofit': 'Organización sin fines de lucro',
    'employment_type.private': 'Sector privado',
    'employment_type.self_employed': 'Trabajador independiente',
    'employment_type.not_employed': 'Sin empleo actualmente',
    'employment_tenure.under_1': 'Menos de 1 año',
    'employment_tenure.1_5': '1–5 años',
    'employment_tenure.5_10': '5–10 años',
    'employment_tenure.10_plus': '10 años o más',
    'payment_recent.consistent': 'Pagos puntuales y constantes',
    'payment_recent.missed_some': 'Falté a algunos pagos',
    'payment_recent.difficult_to_afford': 'Difíciles de pagar',
    'payment_recent.not_currently_required': 'Pagos no requeridos actualmente',
    'payment_recent.have_not_been_paying': 'No he estado pagando',
    'payment_recent.not_sure': 'No lo sé',
    'previous_actions.idr': 'Pago según ingresos (IDR)',
    'previous_actions.pslf': 'Public Service Loan Forgiveness (PSLF)',
    'previous_actions.federal_consolidation': 'Consolidación federal',
    'previous_actions.private_refinancing': 'Refinanciamiento privado',
    'previous_actions.borrower_defense': 'Borrower defense to repayment',
    'previous_actions.none': 'Ninguna',
    'previous_actions.not_sure': 'No lo sé',
    'primary_goal.lower_payment': 'Bajar mi pago',
    'primary_goal.forgiveness_review': 'Revisar opciones de condonación',
    'primary_goal.exit_delinquency_default': 'Salir de mora o incumplimiento',
    'primary_goal.pay_off_faster': 'Pagar más rápido',
    'primary_goal.prepare_home': 'Prepararme para comprar una vivienda',
    'primary_goal.understand_options': 'Entender mis opciones',
    'urgency.asap': 'Lo antes posible',
    'urgency.within_30_days': 'En 30 días',
    'urgency.within_3_months': 'En 3 meses',
    'urgency.just_exploring': 'Solo estoy explorando',
  },
  placeholders: {
    select: 'Seleccione una opción',
    servicer_name: 'Nombre del administrador',
  },
  validation: {
    required: 'Este campo es obligatorio.',
    servicer_length: 'El nombre del administrador debe tener 80 caracteres o menos.',
    contact_required: 'Complete su nombre, correo electrónico y teléfono.',
  },
  ui: {
    welcomeTitle: 'Comience su Reporte de Préstamos Estudiantiles™',
    welcomeBody:
      'Complete el Reporte de Préstamos Estudiantiles sobre sus préstamos, pagos y metas. Los datos de contacto se piden después del diagnóstico y no forman parte del puntaje.',
    backToOverview: 'Volver al resumen',
    back: 'Atrás',
    continue: 'Continuar',
    viewResults: 'Ver mi Reporte de Préstamos Estudiantiles',
    saving: 'Guardando su Reporte de Préstamos Estudiantiles…',
    contactTitle: 'Contacto y reconocimientos',
    contactBody: 'Indique cómo podemos comunicarnos con usted. Los reconocimientos obligatorios están marcados con un asterisco.',
    firstName: 'Nombre',
    lastName: 'Apellido',
    email: 'Correo electrónico',
    phone: 'Teléfono',
    firstNamePlaceholder: 'Nombre',
    lastNamePlaceholder: 'Apellido',
    emailPlaceholder: 'usted@email.com',
    phonePlaceholder: '(555) 555-5555',
    consentIntro:
      'Su Reporte de Préstamos Estudiantiles™ se basa en la información que compartió. Los reconocimientos obligatorios están marcados con un asterisco.',
    ingestUnavailable:
      'Sus resultados se calcularon en este dispositivo. No se enviaron al CRM de Valtoris.',
    resultsUnavailable: 'Los resultados de su Reporte de Préstamos Estudiantiles aún no están disponibles.',
    resultsLead:
      'Complete la evaluación del Reporte de Préstamos Estudiantiles para ver su puntaje, calificación y áreas de revisión.',
    backToLanding: 'Volver al Reporte de Préstamos Estudiantiles',
    retake: 'Volver a la evaluación',
    retakeCta: 'Repetir evaluación',
    preparedFor: 'Preparado para',
    thanks: 'Gracias',
    informationalBalance: 'Rango de saldo informado',
    servicer: 'Administrador informado',
    urgency: 'Plazo de revisión',
    nextStepSupport:
      'Revise su Reporte de Préstamos Estudiantiles™ con Valtoris. Una conversación puede comparar estas respuestas con sus registros reales de préstamo y las reglas federales vigentes.',
    startCta: 'Comenzar mi Reporte de Préstamos Estudiantiles™',
    productTitle: 'Reporte de Préstamos Estudiantiles™',
    storageResultName: 'Reporte de Préstamos Estudiantiles',
    languageGroupLabel: 'Idioma',
    languageEnglish: 'English',
    languageSpanish: 'Español',
    stepIndicator: 'Paso {current} de {total}',
    scoreOutOf: '{score} de 100',
    consentRequired: 'Confirme los reconocimientos obligatorios antes de ver su reporte.',
    submitFailed: 'No pudimos guardar su Reporte de Préstamos Estudiantiles. Inténtelo de nuevo.',
    consentHeading: 'Reconocimientos',
    consentStorage:
      'Entiendo que Valtoris usará la información que proporcione para calcular y guardar mi {storageResultName} y los resultados relacionados.',
    consentStorageHint: 'Reconocimiento obligatorio para guardar y calcular su diagnóstico.',
    consentStorageError:
      'Reconozca que su información se usará para calcular y guardar su diagnóstico.',
    consentContact: 'Autorizo a Valtoris a comunicarse conmigo sobre mis resultados y posibles siguientes pasos.',
    consentEmailMarketing:
      'Acepto recibir correos de marketing ocasionales de Valtoris. Puedo cancelar la suscripción en cualquier momento.',
    consentSms:
      'Acepto recibir mensajes de texto de marketing recurrentes de Valtoris al número indicado. El consentimiento no es una condición para recibir mi reporte. Pueden aplicarse tarifas de mensajes y datos. Responda STOP para cancelar.',
    consentSmsPhoneNote: 'Agregue un número de teléfono más arriba en la evaluación para activar esta opción.',
    consentPrivacyBefore: 'Reconozco que he revisado la',
    consentPrivacyLink: 'Política de privacidad de Valtoris',
    consentPrivacyAfter: '.',
    consentPrivacyHint: 'Reconocimiento de privacidad obligatorio. Abre la Política de privacidad en una pestaña nueva.',
    consentPrivacyError: 'Revise y reconozca la Política de privacidad antes de continuar.',
    consentDisclaimer:
      'Los resultados son estimaciones educativas basadas en información que usted informó. No son asesoría financiera, legal, fiscal, de inversión, de crédito ni de seguros, y no son una garantía. Una revisión con un asesor puede llegar a conclusiones distintas.',
    consentHoneypot: 'Sitio web de la empresa',
    landingEyebrow: 'REPORTE DE PRÉSTAMOS ESTUDIANTILES™ DE VALTORIS',
    landingTitle: 'Tenga más claridad sobre sus préstamos estudiantiles',
    landingHero1:
      'Entienda en qué punto está con sus préstamos estudiantiles y qué áreas pueden merecer atención.',
    landingHero2:
      'El Reporte de Préstamos Estudiantiles™ ayuda a organizar su situación de pago, identificar posibles inquietudes y prepararlo para una conversación de estrategia más informada.',
    landingReceiveHeading: 'Qué recibirá',
    landingReceiveLead: 'Lo que este Reporte especializado está diseñado para entregar.',
    landingReceiveScoreTitle: 'Puntaje del Reporte de Préstamos Estudiantiles',
    landingReceiveScoreDescription:
      'Un Puntaje del Reporte de Préstamos Estudiantiles de Valtoris de 0 a 100 y una calificación que resumen el estado del préstamo, la estrategia de pago y las prioridades de revisión. Los saldos altos no se penalizan.',
    landingReceiveFlagsTitle: 'Señales de revisión y áreas principales',
    landingReceiveFlagsDescription:
      'Situaciones críticas como el incumplimiento o la mora aparecen como señales de revisión, aparte del puntaje numérico.',
    landingReceiveGoalTitle: 'Siguiente paso alineado a su meta',
    landingReceiveGoalDescription:
      'Su meta principal y su urgencia enmarcan la revisión recomendada. Esto es educativo, no una determinación de elegibilidad.',
    landingReceiveSessionTitle: 'Conversación opcional de estrategia',
    landingReceiveSessionDescription:
      'Si lo desea, puede revisar sus resultados en una conversación sin costo. Completar la evaluación no crea una Oportunidad en el CRM.',
    landingSampleHeading: 'Vista previa del reporte',
    landingSampleLead:
      'Un ejemplo de la presentación del reporte. Los valores de muestra están marcados como ejemplo y no son sus resultados.',
    landingSampleBadge: 'Muestra / Ejemplo',
    landingSampleAriaLabel: 'Vista previa de ejemplo del Reporte de Préstamos Estudiantiles',
    landingSampleFlagHeading: 'Señal de revisión de ejemplo',
    landingSampleFlagTitle: 'El conocimiento del plan de pago puede merecer una revisión más de cerca',
    landingSampleReviewHeading: 'Áreas de revisión de ejemplo',
    landingSampleReview1: 'La estrategia de pago puede merecer una revisión más de cerca',
    landingSampleReview2: 'Puede valer la pena revisar las opciones de programas',
    landingSampleReview3: 'Puede faltar detalle sobre los préstamos',
    landingSampleDisclaimer:
      'Solo un ejemplo. Estos valores de muestra no son su Puntaje del Reporte de Préstamos Estudiantiles y no diagnostican sus préstamos.',
    landingCompliance:
      'Valtoris no es el Departamento de Educación de EE. UU. y no está afiliado ni respaldado por el gobierno federal. Este diagnóstico es educativo y no garantiza elegibilidad, condonación, aprobación, ahorros ni un pago en particular. La información oficial federal sobre préstamos estudiantiles está disponible en StudentAid.gov.',
    landingCategoriesHeading: 'Qué cubre el Reporte',
    landingCategoriesLead: 'Cada grupo cuenta como una pregunta de diagnóstico, incluidas las preguntas de seguimiento.',
    landingCategoryStructureTitle: 'Estructura del préstamo',
    landingCategoryStructureDescription:
      'Tipos de préstamo, rango de saldo y conocimiento del administrador — sin números de cuenta ni credenciales de FSA.',
    landingCategoryStatusTitle: 'Estado y estabilidad',
    landingCategoryStatusDescription:
      'Estado de pago, aplazamiento, mora o incumplimiento, ponderado por estabilidad — no por el tamaño del préstamo.',
    landingCategoryRepaymentTitle: 'Estrategia de pago',
    landingCategoryRepaymentDescription:
      'Si conoce su plan de pago actual o reciente, usando los nombres federales vigentes y las opciones anteriores que todavía puede reportar.',
    landingCategoryIncomeTitle: 'Ingresos y hogar',
    landingCategoryIncomeDescription: 'Rango de ingresos y tamaño del hogar para un contexto posterior de planes según ingresos.',
    landingCategoryEmploymentTitle: 'Contexto laboral',
    landingCategoryEmploymentDescription:
      'Gobierno, organización sin fines de lucro, sector privado, trabajo independiente o sin empleo — más antigüedad cuando corresponda.',
    landingCategoryPaymentTitle: 'Historial de pagos',
    landingCategoryPaymentDescription: 'Patrón reciente de pagos y si los pagos están pausados actualmente.',
    landingHowHeading: 'Cómo funciona',
    landingHowLead: 'Desde sus primeras respuestas hasta un reporte con puntaje — sin crear automáticamente una Oportunidad en el CRM.',
    landingHow1Title: 'Complete la evaluación',
    landingHow1Description:
      'Comparta datos de préstamo, pagos y metas. La información de contacto se pide después del diagnóstico.',
    landingHow2Title: 'Reconozca la privacidad',
    landingHow2Description: 'Los reconocimientos obligatorios de almacenamiento y privacidad usan los controles públicos actuales.',
    landingHow3Title: 'Vea sus resultados',
    landingHow3Description:
      'Su puntaje, calificación, señales y áreas principales de revisión se calculan a partir de sus respuestas en este dispositivo.',
    landingHow4Title: 'Revisión opcional',
    landingHow4Description:
      'Reserve una revisión sin costo si desea revisar los resultados juntos. No se crea una Oportunidad automáticamente.',
    landingFaqHeading: 'Preguntas frecuentes',
    landingFaqLead: 'Respuestas claras antes de comenzar.',
    landingFaq1: '¿Cuánto tarda el Reporte de Préstamos Estudiantiles?',
    landingFaqA1: 'La mayoría de las personas termina la evaluación, incluidos los datos de contacto, en unos minutos.',
    landingFaq2: '¿Me pedirán acceso a FSA o mi número de Seguro Social?',
    landingFaqA2:
      'No. Nunca pedimos SSN, fecha de nacimiento, credenciales de FSA, números de cuenta ni documentos.',
    landingFaq3: '¿Recibo un puntaje hoy?',
    landingFaqA3:
      'Sí. Recibe un Puntaje del Reporte de Préstamos Estudiantiles de Valtoris, calificación, señales y áreas de revisión después de completar la evaluación y los reconocimientos.',
    landingFaq4: '¿Esto aprueba elegibilidad o condonación?',
    landingFaqA4:
      'No. Este es un diagnóstico educativo. Valtoris no es el Departamento de Educación de EE. UU. ni un administrador federal de préstamos, y no está afiliado ni respaldado por el gobierno federal. No determina elegibilidad, montos de pago, condonación ni ahorros. La información oficial federal sobre préstamos estudiantiles está disponible en StudentAid.gov.',
    landingFaq5: '¿Alguien me contactará automáticamente?',
    landingFaqA5:
      'No se envían mensajes automáticos. Si termina la evaluación y acepta que lo contactemos, Valtoris puede darle seguimiento sobre sus resultados. Completar las preguntas no lo inscribe en un programa federal.',
    landingClosingTitle: '¿Listo para comenzar su Reporte de Préstamos Estudiantiles™?',
    landingClosingCopy: 'Complete el Reporte de Préstamos Estudiantiles y reciba su Puntaje del Reporte de Préstamos Estudiantiles de Valtoris.',
    landingClosingMicrocopy:
      'Sin números de cuenta. Sin credenciales de FSA. Los reconocimientos de privacidad obligatorios siguen siendo explícitos.',
  },
  results: {
    score: 'Puntaje del Reporte de Préstamos Estudiantiles',
    grade: 'Calificación',
    status: 'Estado',
    categories: 'Puntajes por categoría',
    flags: 'Señales críticas de revisión',
    topAreas: 'Áreas principales de revisión',
    topAreas1: 'Área principal para revisar',
    topAreas2: '2 áreas principales para revisar',
    topAreas3: '3 áreas principales para revisar',
    noReviewAreas: 'No se identificaron áreas de revisión inmediata a partir de sus respuestas.',
    primaryGoal: 'Meta principal',
    bookingCta: 'Revisar mis resultados con Valtoris',
    reviewWithValtoris: 'Revisar mis resultados con Valtoris',
    unavailable: 'Los resultados de su Reporte de Préstamos Estudiantiles aún no están disponibles.',
    disclaimer:
      'Este Puntaje del Reporte de Préstamos Estudiantiles es una evaluación educativa de Valtoris basada en las respuestas que usted dio. No es una determinación del gobierno y no garantiza elegibilidad, condonación, aprobación, ahorros ni un pago en particular. Valtoris no es el Departamento de Educación de EE. UU. ni un administrador federal de préstamos. La elegibilidad de los programas y las opciones de pago dependen de sus registros reales de préstamo y de las reglas federales vigentes.',
    officialResourceLead: 'La información oficial federal sobre préstamos estudiantiles está disponible en',
    officialResourceLink: 'StudentAid.gov',
    officialResourceAfter: '. Federal Student Aid opera ese sitio; Valtoris no.',
    'status.optimized': 'Optimizado',
    'status.strong': 'Sólido',
    'status.opportunities': 'Hay oportunidades',
    'status.needs_review': 'Necesita revisión',
    'status.high_priority': 'Alta prioridad',
    'category.status_stability': 'Estado del préstamo y estabilidad de pagos',
    'category.repayment_strategy': 'Estrategia de pago',
    'category.forgiveness_optimization': 'Revisión de condonación / programas',
    'category.knowledge_structure': 'Conocimiento y estructura del préstamo',
    'category.goal_alignment': 'Alineación con la meta',
    'flag.immediate_review': 'Revisión inmediata',
    'flag.high_priority': 'Alta prioridad',
    'flag.potential_opportunity': 'Oportunidad potencial / se recomienda revisión',
    'flag.review_recommended': 'Se recomienda revisión',
    'review.flag_default.title': 'El incumplimiento (default) necesita revisión inmediata',
    'review.flag_default.body':
      'Usted indicó que sus préstamos están en incumplimiento (default). Esta es una situación de alta urgencia y debe revisarse con sus registros reales de préstamo.',
    'review.flag_delinquent.title': 'La mora es una revisión de alta prioridad',
    'review.flag_delinquent.body':
      'Usted indicó que sus préstamos están en mora. Una revisión puede ayudarle a entender el estado actual y los posibles siguientes pasos.',
    'review.flag_difficult_payments.title': 'Los pagos actuales parecen difíciles de cubrir',
    'review.flag_difficult_payments.body':
      'Usted indicó dificultad para pagar sus cuotas actuales. Esto no determina un nuevo monto de pago; señala la situación para revisión.',
    'review.flag_pslf_unreviewed.title': 'Empleo de servicio público sin una revisión de PSLF',
    'review.flag_pslf_unreviewed.body':
      'Usted indicó empleo de servicio público, pero ninguna revisión previa de PSLF. Esto es una oportunidad de revisión, no una determinación de que califique.',
    'review.flag_unknown_loan_type.title': 'El tipo de préstamo no está claro',
    'review.flag_unknown_loan_type.body':
      'El tipo actual de su préstamo no está claro y debe revisarse. Conocer el tipo ayuda a enmarcar las opciones posteriores.',
    'review.flag_unknown_plan.title': 'El plan de pago no está claro',
    'review.flag_unknown_plan.body':
      'Su plan de pago actual no está claro y debe revisarse.',
    'review.category.status_stability.title': 'La estabilidad de pagos debe revisarse',
    'review.category.status_stability.body':
      'El estado o el patrón de pagos que indicó deja espacio para revisar la estabilidad con más detalle.',
    'review.category.repayment_strategy.title': 'La estrategia de pago debe revisarse',
    'review.category.repayment_strategy.body':
      'El conocimiento de su plan de pago actual está incompleto y debe revisarse.',
    'review.category.forgiveness_optimization.title': 'Se puede mejorar el conocimiento de programas',
    'review.category.forgiveness_optimization.body':
      'Una revisión puede comprobar si alguna opción de programa es pertinente. Esto no es un hallazgo de elegibilidad.',
    'review.category.knowledge_structure.title': 'Faltan detalles del préstamo',
    'review.category.knowledge_structure.body':
      'Algunos datos básicos del préstamo no se conocen. Aclararlos ayuda a que una revisión posterior sea más precisa.',
    'review.category.goal_alignment.title': 'La meta y el estado actual deben revisarse juntos',
    'review.category.goal_alignment.body':
      'Su meta declarada y su situación actual de préstamo deben revisarse juntas. Esto no predice una aprobación ni un resultado específico.',
  },
}

export const studentLoanCopy: SpecializedProductCopy = {
  en: STUDENT_LOAN_COPY_EN,
  es: STUDENT_LOAN_COPY_ES,
}
