/** Shared, versioned insurance intake contract. No browser persistence or external I/O. */
export const QUOTE_KINDS = ['auto', 'home', 'commercial'] as const
export type QuoteKind = typeof QUOTE_KINDS[number]
export type QuoteValue = string | string[] | Record<string, string>[]
export type QuoteAnswers = Record<string, QuoteValue>
export type QuoteField = {
  id: string; label: string; type?: 'text' | 'email' | 'tel' | 'date' | 'number' | 'select' | 'multi' | 'rows'
  options?: string[]; fields?: QuoteField[]; required?: boolean; max?: number; maxLength?: number
  when?: { field: string; includes: string[] }
}
export type QuoteSection = { id: string; title: string; description?: string; fields: QuoteField[]; lines?: string[] }
export const QUOTE_LABELS: Record<QuoteKind, string> = { auto: 'Auto Insurance Quote', home: 'Home Insurance Quote', commercial: 'Commercial Insurance Quote' }
export const QUOTE_LEAD_TYPES = QUOTE_KINDS.map(kind => QUOTE_LABELS[kind])
export const QUOTE_CONSENT_VERSION = 'insurance-quote-v1'
export const QUOTE_STORAGE_COPY = 'I authorize Valtoris Financial to store and review this information to respond to my insurance quote request. I have permission to provide information about the people or business listed.'
export const QUOTE_CONTACT_COPY = 'I authorize Valtoris Financial to contact me about this quote request by my selected contact method. This does not enroll me in automated marketing.'
const yesNo = ['Yes', 'No', 'Not sure']
const preference = ['Yes', 'No', 'Advisor recommendation']
const t = (id: string, label: string, required = false): QuoteField => ({ id, label, required, maxLength: 300 })
const n = (id: string, label: string, max = 1000000000): QuoteField => ({ id, label, type: 'number', max })
const d = (id: string, label: string): QuoteField => ({ id, label, type: 'date' })
const s = (id: string, label: string, options = yesNo, required = false): QuoteField => ({ id, label, type: 'select', options, required })
const multi = (id: string, label: string, options: string[], required = false): QuoteField => ({ id, label, type: 'multi', options, required })
const conditional = (field: QuoteField, key: string, ...includes: string[]): QuoteField => ({ ...field, when: { field: key, includes } })
const rows = (id: string, label: string, fields: QuoteField[], required = false): QuoteField => ({ id, label, type: 'rows', fields, required })
export const CONTACT_FIELDS: QuoteField[] = [
  t('firstName', 'First name', true), t('lastName', 'Last name', true),
  { ...t('email', 'Email', true), type: 'email' }, { ...t('phone', 'Phone', true), type: 'tel' },
  s('preferredContact', 'Preferred contact method', ['Email', 'Phone'], true),
]
const carrier = [t('currentCarrier', 'Current insurance carrier (or “None”)'), d('policyExpiration', 'Current policy expiration')]
const driverFields = [t('name', 'Driver full name', true), d('birthDate', 'Date of birth'), t('relationship', 'Relationship to you'), s('licensed', 'Licensed?')]
const vehicleFields = [n('year', 'Model year', 2100), t('makeModel', 'Make and model', true), t('vin', 'VIN (if known)'), s('use', 'Vehicle use', ['Personal', 'Commute', 'Business', 'Delivery / rideshare', 'Other']), s('ownership', 'Ownership', ['Owned', 'Financed', 'Leased'])]
export const QUOTE_SECTIONS: Record<QuoteKind, QuoteSection[]> = {
  auto: [
    { id: 'applicant', title: 'About you', fields: [d('birthDate', 'Date of birth'), s('maritalStatus', 'Marital status', ['Single', 'Married', 'Divorced', 'Widowed', 'Prefer to discuss']), t('address', 'Home address — street, city, state and ZIP', true), n('yearsLicensed', 'Years licensed', 100), s('incidents', 'Tickets or accidents in the last five years?'), ...carrier] },
    { id: 'drivers', title: 'Household drivers', description: 'Include yourself and everyone in your household who drives.', fields: [rows('drivers', 'Drivers', driverFields, true)] },
    { id: 'vehicles', title: 'Vehicles to insure', fields: [rows('vehicles', 'Vehicles', vehicleFields, true)] },
    { id: 'coverage', title: 'Coverage preferences', description: 'Not sure? Select advisor recommendation. Your advisor will review coverage availability and limits with you.', fields: [s('liability', 'Bodily injury liability preference', ['State minimum', '50/100', '100/300', '250/500', 'Advisor recommendation']), s('uninsured', 'Uninsured motorist', preference), s('comprehensive', 'Comprehensive', preference), s('collision', 'Collision', preference), s('deductible', 'Deductible preference', ['$250', '$500', '$1,000', 'Advisor recommendation']), s('rental', 'Rental reimbursement', preference), s('roadside', 'Roadside / towing', preference), s('gap', 'Gap coverage', ['Yes', 'No', 'Not applicable', 'Advisor recommendation'])] },
  ],
  home: [
    { id: 'applicant', title: 'You and your property', fields: [d('birthDate', 'Date of birth'), t('address', 'Property address — street, city, state and ZIP', true), t('mailingAddress', 'Mailing address, if different'), s('occupancy', 'Occupancy', ['Owner-occupied', 'Tenant-occupied', 'Seasonal / secondary', 'Vacant'], true), s('policyType', 'Policy requested', ['Homeowners (HO-3)', 'Condo / co-op (HO-6)', 'Renters (HO-4)', 'Landlord / dwelling fire (DP-3)', 'Advisor recommendation'], true), s('claims', 'Insurance claims in the last five years?'), ...carrier] },
    { id: 'property', title: 'Property details', description: 'Leave details you do not know blank; your advisor can help verify them.', fields: [n('yearBuilt', 'Year built', 2100), n('squareFeet', 'Square footage', 10000000), n('stories', 'Number of stories', 200), t('bedroomsBaths', 'Bedrooms / bathrooms'), s('construction', 'Construction', ['Frame', 'Masonry', 'Masonry veneer', 'Other', 'Not sure']), s('roofType', 'Roof type', ['Asphalt', 'Metal', 'Tile', 'Flat', 'Other', 'Not sure']), n('roofAge', 'Roof age in years', 200), s('heating', 'Heating system', ['Gas forced air', 'Electric', 'Oil', 'Heat pump', 'Other', 'Not sure']), multi('risks', 'Property features', ['Pool', 'Trampoline', 'Dog', 'Oil tank', 'None', 'Not sure']), conditional(t('dogBreed', 'Dog breed(s)'), 'risks', 'Dog'), conditional(s('poolType', 'Pool type', ['Below ground', 'Above ground', 'Not sure']), 'risks', 'Pool'), conditional(s('poolFence', 'Pool fenced?'), 'risks', 'Pool'), conditional(s('divingBoard', 'Pool has a diving board?'), 'risks', 'Pool'), conditional(s('oilTankLocation', 'Oil tank location', ['Basement / above ground', 'Below ground / buried', 'Outside above ground', 'Crawlspace', 'Not sure']), 'risks', 'Oil tank')] },
    { id: 'protection', title: 'Protection and updates', fields: [s('smokeDetectors', 'Smoke detectors?'), s('burglarAlarm', 'Burglar alarm', ['None', 'Local', 'Central station', 'Not sure']), s('fireAlarm', 'Fire alarm / sprinklers', ['None', 'Local', 'Central station', 'Sprinklers', 'Not sure']), s('fireDistance', 'Fire-service distance (select closest known description)', ['Hydrant within 1,000 feet', 'Station within 5 miles', 'Station 5 miles or more', 'Not sure']), t('electricalUpdated', 'Electrical last updated (year or “Original”)'), t('heatingUpdated', 'HVAC / heating last updated'), t('plumbingUpdated', 'Plumbing last updated')] },
    { id: 'coverage', title: 'Coverage amounts and options', description: 'Requested amounts are optional. Your advisor will confirm appropriate coverages for your policy type.', fields: [n('dwelling', 'Coverage A — dwelling ($)'), n('otherStructures', 'Coverage B — other structures ($)'), n('personalProperty', 'Coverage C — personal property ($)'), n('lossOfUse', 'Coverage D — loss of use ($)'), n('liability', 'Coverage E — personal liability ($)'), n('medicalPayments', 'Coverage F — medical payments ($)'), t('deductible', 'All-perils deductible preference'), t('windDeductible', 'Wind / hail deductible preference'), s('dwellingValuation', 'Dwelling valuation', ['Replacement cost', 'Actual cash value', 'Advisor recommendation']), s('propertyValuation', 'Personal property valuation', ['Replacement cost', 'Actual cash value', 'Advisor recommendation']), s('waterBackup', 'Water / sewer backup', preference), s('extendedReplacement', 'Extended / guaranteed replacement cost', preference), s('scheduledItems', 'Items to schedule (jewelry, art, firearms)?'), s('flood', 'Would you like a flood insurance review?', preference)] },
  ],
  commercial: [
    { id: 'business', title: 'About your business', fields: [t('businessName', 'Legal business name / DBA', true), t('contactTitle', 'Your title / role'), t('address', 'Business mailing address — street, city, state and ZIP', true), t('premisesAddress', 'Premises address, if different'), t('website', 'Business website'), n('yearsInBusiness', 'Years in business', 300), t('fein', 'FEIN (optional; do not enter a Social Security number)'), s('entityType', 'Entity type', ['Sole proprietor', 'LLC', 'Corporation', 'Partnership', 'Other'], true), { ...t('operations', 'Describe what your business does', true), maxLength: 1500 }, n('annualRevenue', 'Annual revenue / sales ($)'), n('annualPayroll', 'Annual payroll ($)'), n('fullTimeEmployees', 'Full-time employees', 1000000), n('partTimeEmployees', 'Part-time employees', 1000000), n('owners', 'Number of owners', 100000)] },
    { id: 'risk', title: 'Coverage requested and history', fields: [multi('lines', 'Which coverages would you like quoted?', ['General Liability', 'Property', 'Workers’ Compensation', 'Commercial Auto', 'Umbrella', 'BOP'], true), s('priorCoverage', 'Current or prior business coverage?'), ...carrier, s('claims', 'Losses or claims in the last five years?'), conditional({ ...t('claimDetails', 'Briefly describe claims (no medical or financial account details)'), maxLength: 1500 }, 'claims', 'Yes'), s('declined', 'Coverage declined, cancelled or non-renewed?')] },
    { id: 'gl', title: 'General liability', lines: ['General Liability', 'BOP'], fields: [s('classification', 'Business classification', ['Contractor', 'Retail', 'Office', 'Restaurant', 'Wholesale', 'Service', 'Other']), t('specificOperations', 'Specific operations'), n('occupiedSquareFeet', 'Square feet occupied'), n('locations', 'Number of locations', 100000), s('premisesOwnership', 'Own or lease premises?', ['Own', 'Lease']), s('subcontractors', 'Use subcontractors?'), conditional(t('subcontractorDetails', 'Annual subcontractor cost and certificates of insurance collected?'), 'subcontractors', 'Yes'), s('offPremises', 'Work at client sites / off-premises?'), s('products', 'Manufacture, sell or distribute products?'), conditional(t('productDetails', 'Describe products'), 'products', 'Yes'), multi('exposures', 'Additional exposures', ['Liquor', 'Pool / spa', 'Firearms', 'Aviation', 'Heavy equipment', 'None', 'Not sure']), n('occurrenceLimit', 'Requested occurrence limit ($)'), n('aggregateLimit', 'Requested aggregate limit ($)')] },
    { id: 'property', title: 'Commercial property', lines: ['Property', 'BOP'], fields: [n('buildingValue', 'Building value, if owned ($)'), n('yearBuilt', 'Year built', 2100), s('construction', 'Construction', ['Frame', 'Joisted masonry', 'Masonry noncombustible', 'Fire resistive', 'Other', 'Not sure']), n('squareFeet', 'Total square footage'), n('stories', 'Number of stories', 200), t('roofType', 'Roof type'), s('roofAge', 'Roof age', ['Under 10 years', '10–20 years', 'Over 20 years', 'Not sure']), s('systemsUpdated', 'Electrical / plumbing / HVAC updated?', ['Yes', 'No', 'Partial', 'Not sure']), multi('protectiveDevices', 'Protective devices', ['Sprinklers', 'Central alarm', 'Local alarm', 'Extinguishers', 'None', 'Not sure']), n('contentsLimit', 'Business personal property / contents limit ($)'), n('businessIncomeLimit', 'Business income / extra expense limit ($)'), n('equipmentLimit', 'Equipment / inventory limit ($)'), s('valuation', 'Property valuation', ['Replacement cost', 'Actual cash value', 'Advisor recommendation'])] },
    { id: 'wc', title: 'Workers’ compensation', lines: ['Workers’ Compensation'], fields: [t('operatingStates', 'States of operation'), t('classCodes', 'Governing class codes, if known'), rows('payrollClasses', 'Payroll by job duties', [t('duties', 'Job classification / duties', true), n('employees', 'Employees', 1000000), n('payroll', 'Annual payroll ($)')]), s('officers', 'Owners / officers included or excluded?', ['Included', 'Excluded', 'Mixed', 'Advisor recommendation']), s('travel', 'Employees travel out of state or drive for work?'), s('wcClaims', 'Prior or open workers’ compensation claims?'), n('experienceMod', 'Current experience modification factor', 100), d('modEffectiveDate', 'Modification effective date'), s('safetyProgram', 'Safety program / employee handbook in place?')] },
    { id: 'commercialAuto', title: 'Commercial auto', lines: ['Commercial Auto'], fields: [s('vehicleUse', 'Vehicle use', ['Business use', 'Delivery', 'Hauling', 'Service / repair', 'Livery', 'Other']), rows('commercialVehicles', 'Business vehicles', [n('year', 'Model year', 2100), t('makeModel', 'Make and model', true), t('vin', 'VIN'), t('weightType', 'Gross vehicle weight / type'), t('radius', 'Operating radius')]), rows('commercialDrivers', 'Business drivers', [t('name', 'Driver full name', true), d('birthDate', 'Date of birth'), t('licenseNumber', 'License number (optional)'), t('licenseState', 'License state'), n('experience', 'Years of experience', 100)]), s('youngOrViolations', 'Drivers under 21 or with violations?'), n('autoLiability', 'Requested combined single liability limit ($)'), s('hiredNonOwned', 'Hired / non-owned auto coverage?', preference), s('physicalDamage', 'Comprehensive / collision?', preference), t('autoDeductibles', 'Comprehensive / collision deductibles')] },
  ],
}
export function isQuoteKind(value: unknown): value is QuoteKind { return QUOTE_KINDS.includes(value as QuoteKind) }
export function isQuoteLead(value: string): boolean { return QUOTE_LEAD_TYPES.includes(value) }
export function activeSections(kind: QuoteKind, answers: QuoteAnswers): QuoteSection[] {
  const lines = Array.isArray(answers.lines) ? answers.lines : []
  return QUOTE_SECTIONS[kind].filter(section => !section.lines || section.lines.some(line => lines.some(value => value === line)))
}
export function activeFields(fields: QuoteField[], answers: QuoteAnswers): QuoteField[] {
  return fields.filter(field => !field.when || field.when.includes.some(value => {
    const selected = answers[field.when!.field]
    return Array.isArray(selected) ? selected.some(item => item === value) : selected === value
  }))
}
/** Never retain answers hidden by a coverage or risk change. */
export function pruneAnswers(kind: QuoteKind, answers: QuoteAnswers): QuoteAnswers {
  const allowed = new Set(activeSections(kind, answers).flatMap(section => activeFields(section.fields, answers).map(field => field.id)))
  return Object.fromEntries(Object.entries(answers).filter(([key]) => allowed.has(key)))
}
