-- Synthetic records only; fixtures and all writes rolled back.
BEGIN;
CREATE FUNCTION pg_temp.expect_rejection(statement text, expected text) RETURNS void LANGUAGE plpgsql AS $$
BEGIN
 BEGIN EXECUTE statement; EXCEPTION WHEN OTHERS THEN
  IF SQLERRM LIKE '%'||expected||'%' THEN RETURN; END IF;
  RAISE EXCEPTION 'Unexpected rejection: %',SQLERRM;
 END;
 RAISE EXCEPTION 'Expected rejection missing: %',expected;
END $$;
DO $$
DECLARE owner_id uuid; au uuid:=extensions.gen_random_uuid(); ai uuid:=extensions.gen_random_uuid(); h uuid:=extensions.gen_random_uuid(); otherh uuid:=extensions.gen_random_uuid(); c uuid:=extensions.gen_random_uuid(); oldc uuid:=extensions.gen_random_uuid(); pipeline uuid; stage uuid; r jsonb; n integer; m uuid:=extensions.gen_random_uuid(); facts jsonb; saved jsonb; intake jsonb; sections jsonb:='{}'; sec jsonb; fields jsonb; draft jsonb; other_member uuid:=extensions.gen_random_uuid(); protected_row jsonb; revealed jsonb; field jsonb;
BEGIN
 SELECT id INTO owner_id FROM public.profiles WHERE role='owner' AND is_active AND deleted_at IS NULL LIMIT 1;
 IF owner_id IS NULL THEN RAISE EXCEPTION 'Owner fixture context missing'; END IF;
 SELECT p.id,s.id INTO pipeline,stage FROM public.pipelines p JOIN public.pipeline_stages s ON s.pipeline_id=p.id WHERE p.pipeline_type='relationship' ORDER BY s.sort_order LIMIT 1;
 INSERT INTO auth.users(id,email,raw_user_meta_data) VALUES(au,'archive-qa-'||au||'@example.invalid','{"full_name":"Synthetic archive QA"}');
 INSERT INTO public.profiles(id,email,full_name,role) VALUES(au,'archive-qa-'||au||'@example.invalid','Synthetic archive QA','advisor') ON CONFLICT(id) DO NOTHING;
 INSERT INTO public.advisor_profiles(id,user_id,display_name,slug) VALUES(ai,au,'Synthetic archive QA','archive-qa-'||ai);
 PERFORM set_config('crm.rpc_context','quick_add_contact',true);
 INSERT INTO public.households(id,display_name,relationship_pipeline_id,relationship_stage_id,assigned_advisor_id,lead_source) VALUES(h,'Synthetic archive QA',pipeline,stage,ai,'manual_contact'),(otherh,'Synthetic other QA',pipeline,stage,NULL,'manual_contact');
 INSERT INTO public.household_members(id,household_id,first_name,last_name) VALUES(m,h,'Synthetic','Profile');
 INSERT INTO public.household_members(id,household_id,first_name,last_name) VALUES(other_member,otherh,'Synthetic','Other Insured');
 INSERT INTO public.leads(id,household_id,lead_type) VALUES(c,h,'Manual Contact'),(oldc,h,'Manual Contact');
 UPDATE public.leads SET deleted_at=now() WHERE id=oldc;
 PERFORM set_config('crm.rpc_context','',true);
 IF has_function_privilege('anon','public.archive_crm_record(text,uuid)','EXECUTE') OR has_function_privilege('authenticated','public.crm_archive_access(uuid)','EXECUTE') THEN RAISE EXCEPTION 'Invalid grants'; END IF;
 PERFORM pg_temp.expect_rejection(format('SELECT public.archive_crm_record(''household'',%L)',h),'not_authorized');
 PERFORM set_config('request.jwt.claim.sub',au::text,true);
 PERFORM set_config('request.jwt.claims',jsonb_build_object('sub',au,'role','authenticated')::text,true);
 SET LOCAL ROLE authenticated;
 PERFORM pg_temp.expect_rejection(format('SELECT public.archive_crm_record(''household'',%L)',otherh),'not_authorized');
 PERFORM pg_temp.expect_rejection(format('SELECT public.restore_crm_record(''lead'',%L)',oldc),'not_recoverable');

 SELECT jsonb_object_agg(k,'') INTO facts FROM unnest(ARRAY['firstName','lastName','email','phone','birthDate','address','city','state','postalCode','employmentStatus','employer','occupation','annualIncome','incomeAsOf','preferredLanguage']) k;
 facts:=facts||'{"firstName":"Synthetic","lastName":"Profile"}'::jsonb;
 saved:=public.save_client_intake_profile(h,m,NULL,facts);
 IF saved->>'member_id'<>m::text THEN RAISE EXCEPTION 'Profile acknowledgement failed'; END IF;
 PERFORM pg_temp.expect_rejection(format('SELECT public.save_client_intake_profile(%L,%L,NULL,%L::jsonb)',h,m,facts),'INTAKE:conflict');
 PERFORM pg_temp.expect_rejection(format('SELECT public.save_client_intake_profile(%L,%L,NULL,%L::jsonb)',otherh,m,facts),'INTAKE:unavailable');
 PERFORM pg_temp.expect_rejection(format('SELECT public.save_client_intake_profile(%L,%L,%L,%L::jsonb)',h,m,saved->>'updated_at',facts||'{"ssn":"forbidden"}'::jsonb),'INTAKE:invalid_fields');
 RESET ROLE;
 FOR sec IN SELECT value FROM jsonb_array_elements(public.life_insurance_intake_contract()->'sections') LOOP
  SELECT jsonb_object_agg(value->>'id','') INTO fields FROM jsonb_array_elements(sec->'fields');
  sections:=sections||jsonb_build_object(sec->>'id',CASE WHEN coalesce((sec->>'repeatable')::boolean,false) THEN '[]'::jsonb ELSE jsonb_build_array(fields) END);
 END LOOP;
 intake:=jsonb_build_object('version',1,'tracks','["Life insurance planning"]'::jsonb,'sections',sections);
 SET LOCAL ROLE authenticated;
 draft:=public.save_life_insurance_intake(h,'member',m,NULL,NULL,intake,false);
 IF draft#>>'{derived_metrics,intake_origin,id}'<>m::text OR draft->>'lead_id' IS NOT NULL THEN RAISE EXCEPTION 'Member origin incorrect'; END IF;
 PERFORM pg_temp.expect_rejection(format('SELECT public.save_life_insurance_intake(%L,''member'',%L,NULL,NULL,%L::jsonb,false)',otherh,m,intake),'INTAKE:unavailable');
 PERFORM pg_temp.expect_rejection(format('SELECT public.read_life_intake_sensitive(%L,%L,%L,true)',au,draft->>'id',m),'permission denied');
 PERFORM pg_temp.expect_rejection('SELECT * FROM public.life_intake_sensitive_records','permission denied');
 RESET ROLE;
 SET LOCAL ROLE service_role;
 PERFORM pg_temp.expect_rejection('SELECT * FROM public.life_intake_sensitive_records','permission denied');
 PERFORM pg_temp.expect_rejection(format('SELECT public.read_life_intake_sensitive(%L,%L,%L,true)',extensions.gen_random_uuid(),draft->>'id',m),'SENSITIVE:unavailable');
 PERFORM pg_temp.expect_rejection(format('SELECT public.read_life_intake_sensitive(%L,%L,%L,true)',au,draft->>'id',other_member),'SENSITIVE:unavailable');
 protected_row:=public.save_life_intake_sensitive(au,(draft->>'id')::uuid,m,NULL,repeat('A',80),true);
 revealed:=public.read_life_intake_sensitive(au,(draft->>'id')::uuid,m,false);
 IF revealed ? 'ciphertext' THEN RAISE EXCEPTION 'Status exposed encrypted payload'; END IF;
 revealed:=public.read_life_intake_sensitive(au,(draft->>'id')::uuid,m,true);
 IF revealed->>'ciphertext'<>repeat('A',80) THEN RAISE EXCEPTION 'Authorized read missing'; END IF;
 PERFORM pg_temp.expect_rejection(format('SELECT public.save_life_intake_sensitive(%L,%L,%L,NULL,%L,true)',au,draft->>'id',m,repeat('B',80)),'SENSITIVE:conflict');
 RESET ROLE;
 FOR sec IN SELECT value FROM jsonb_array_elements(public.life_insurance_intake_contract()->'sections') WHERE NOT coalesce((value->>'repeatable')::boolean,false) LOOP
  fields:=intake#>ARRAY['sections',sec->>'id','0'];
  FOR field IN SELECT value FROM jsonb_array_elements(sec->'fields') WHERE value->>'required'='true' LOOP
   fields:=fields||jsonb_build_object(field->>'id',CASE field->>'kind' WHEN 'select' THEN field->'options'->>0 WHEN 'date' THEN '2000-01-01' WHEN 'email' THEN 'synthetic@example.invalid' ELSE 'Synthetic' END);
  END LOOP;
  intake:=jsonb_set(intake,ARRAY['sections',sec->>'id','0'],fields);
 END LOOP;
 intake:=jsonb_set(intake,'{sections,review,0,coverageStatus}','"No existing coverage"');
 intake:=jsonb_set(intake,'{sections,review,0,beneficiaryStatus}','"To be decided"');
 intake:=jsonb_set(intake,'{sections,review,0,unresolved}','"Follow up on beneficiaries"');
 SET LOCAL ROLE authenticated;
 PERFORM public.save_life_insurance_intake(h,'member',m,(draft->>'id')::uuid,(draft->>'updated_at')::timestamptz,intake,true);
 RESET ROLE;
 SET LOCAL ROLE service_role;
 PERFORM pg_temp.expect_rejection(format('SELECT public.save_life_intake_sensitive(%L,%L,%L,%L,%L,true)',au,draft->>'id',m,protected_row->>'updated_at',repeat('B',80)),'SENSITIVE:preserved_record');
 RESET ROLE;
 IF NOT EXISTS(SELECT 1 FROM public.activities WHERE assessment_id=(draft->>'id')::uuid AND title='Protected Life intake opened' AND actor_user_id=au) THEN RAISE EXCEPTION 'Reveal audit missing'; END IF;
 SET LOCAL ROLE authenticated;
 IF (SELECT count(*) FROM public.client_intake_profiles WHERE member_id=m)<>1 THEN RAISE EXCEPTION 'Profile read denied'; END IF;
 PERFORM pg_temp.expect_rejection(format('UPDATE public.client_intake_profiles SET facts=%L WHERE member_id=%L',facts,m),'permission denied');
 r:=public.archive_crm_record('lead',c);
 IF r->>'id'<>c::text OR r->>'archived'<>'true' THEN RAISE EXCEPTION 'Archive acknowledgement failed'; END IF;
 IF EXISTS(SELECT 1 FROM public.leads WHERE id=c) THEN RAISE EXCEPTION 'Archived row visible via normal RLS'; END IF;
 SELECT count(*) INTO n FROM public.list_archived_crm_records('lead') WHERE id=c;
 IF n<>1 THEN RAISE EXCEPTION 'Recovery list missing row'; END IF;
 PERFORM pg_temp.expect_rejection(format('SELECT public.archive_crm_record(''lead'',%L)',c),'record_unavailable');
 PERFORM public.archive_crm_record('household',h);
 RESET ROLE;
 SET LOCAL ROLE service_role;
 PERFORM pg_temp.expect_rejection(format('SELECT public.read_life_intake_sensitive(%L,%L,%L,true)',au,draft->>'id',m),'SENSITIVE:unavailable');
 RESET ROLE;
 SET LOCAL ROLE authenticated;
 PERFORM pg_temp.expect_rejection(format('SELECT public.restore_crm_record(''lead'',%L)',c),'restore_household_first');
 PERFORM public.restore_crm_record('household',h);
 RESET ROLE;
 SET LOCAL ROLE service_role;
 revealed:=public.read_life_intake_sensitive(au,(draft->>'id')::uuid,m,false);
 IF revealed->>'exists'<>'true' THEN RAISE EXCEPTION 'Protected record not preserved through recovery'; END IF;
 RESET ROLE;
 SET LOCAL ROLE authenticated;
 PERFORM public.restore_crm_record('lead',c);
 IF NOT EXISTS(SELECT 1 FROM public.leads WHERE id=c AND deleted_at IS NULL) THEN RAISE EXCEPTION 'Restore missing'; END IF;
 PERFORM pg_temp.expect_rejection(format('SELECT public.restore_crm_record(''lead'',%L)',c),'not_recoverable');
 PERFORM pg_temp.expect_rejection('SELECT * FROM public.list_archived_crm_records(''lead'',0,101)','invalid_page');
 RESET ROLE;
 PERFORM set_config('request.jwt.claim.sub',owner_id::text,true);
 UPDATE public.profiles SET is_active=false WHERE id=au;
 SET LOCAL ROLE service_role;
 PERFORM pg_temp.expect_rejection(format('SELECT public.read_life_intake_sensitive(%L,%L,%L,true)',au,draft->>'id',m),'SENSITIVE:unavailable');
 RESET ROLE;
 PERFORM set_config('request.jwt.claim.sub',au::text,true);
 SET LOCAL ROLE authenticated;
 PERFORM pg_temp.expect_rejection(format('SELECT public.archive_crm_record(''household'',%L)',h),'not_authorized');
 PERFORM pg_temp.expect_rejection('SELECT * FROM public.list_archived_crm_records(''lead'')','not_authorized');
 RESET ROLE;
 PERFORM set_config('request.jwt.claim.sub',owner_id::text,true);
 PERFORM set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated')::text,true);
 SET LOCAL ROLE authenticated;
 PERFORM public.archive_crm_record('household',otherh);
 PERFORM public.restore_crm_record('household',otherh);
 RESET ROLE;
 IF (SELECT count(*) FROM public.activities WHERE household_id=h AND metadata->>'crm_archive_version'='1')<>2 THEN RAISE EXCEPTION 'Missing audit records'; END IF;
 IF NOT EXISTS(SELECT 1 FROM public.leads WHERE id=oldc AND deleted_at IS NOT NULL) THEN RAISE EXCEPTION 'Unrelated archived row changed'; END IF;
END $$;
SELECT 'protected Life storage authorization and audit checks passed' AS verification;
ROLLBACK;
