/** Static contract markers for Migration 031 Quick Add Contact foundation. */

export const MIGRATION_031_FILENAME = '031_quick_add_contact_foundation.sql'

export const MIGRATION_031_CONTRACT_MARKERS = [
  'CREATE TYPE public.contact_category AS ENUM',
  'potential_client',
  'household_members_website_scheme_check',
  'CREATE TABLE IF NOT EXISTS public.quick_add_duplicate_tokens',
  'operation text NOT NULL',
  'subject_lead_id uuid',
  'subject_household_id uuid',
  'subject_fingerprint text',
  "operation IN ('create', 'update')",
  'FORCE ROW LEVEL SECURITY',
  'enforce_manual_contact_lead_integrity',
  'enforce_manual_contact_member_integrity',
  'enforce_manual_contact_household_integrity',
  'BEFORE INSERT OR UPDATE OR DELETE ON public.leads',
  'BEFORE INSERT OR UPDATE OR DELETE ON public.household_members',
  'BEFORE INSERT OR UPDATE OR DELETE ON public.households',
  "set_config('crm.rpc_context', 'quick_add_contact', true)",
  "set_config('crm.rpc_context', 'update_manual_contact', true)",
  'crm_clear_rpc_context',
  'quick_add_assert_object_keys',
  'quick_add_assert_payload_size',
  'quick_add_cleanup_tokens',
  'preview_quick_add_contact_duplicates',
  'quick_add_contact',
  'update_manual_contact',
  "'Manual Contact'",
  "'manual_contact'",
  'create_separate',
  'update_separate',
  'QUICK_ADD:invalid_token',
  'QUICK_ADD:manual_contact_rpc_required',
  'pg_advisory_xact_lock',
  'REVOKE ALL ON TABLE public.quick_add_duplicate_tokens FROM authenticated',
  'GRANT EXECUTE ON FUNCTION public.preview_quick_add_contact_duplicates(jsonb)',
  'GRANT EXECUTE ON FUNCTION public.quick_add_contact(jsonb, text, text)',
  'GRANT EXECUTE ON FUNCTION public.update_manual_contact(uuid, jsonb)',
  'leads_normalized_phone_idx',
  'household_members_company_lower_idx',
  'quick-add-contact-consent-v1',
] as const

export const MIGRATION_031_FORBIDDEN_MARKERS = [
  'complete_task',
  'CREATE TABLE public.cases',
  'record_crm_activity',
  'crm_write_activity',
  'CREATE TABLE public.contacts',
  "'exclude_household_id'",
] as const
