/** Static contract markers for Migration 044 policy application requirements. */

export const MIGRATION_044_FILENAME = '044_policy_application_requirements.sql'

export const MIGRATION_044_CONTRACT_MARKERS = [
  'CREATE TABLE IF NOT EXISTS public.policy_application_requirements',
  'CREATE TABLE IF NOT EXISTS public.policy_application_requirement_history',
  'policy_application_requirement_code',
  'policy_application_requirement_status',
  "'signature'",
  "'replacement_form'",
  "'delivery'",
  "'other'",
  "'paramed_exam'",
  "'aps'",
  "'illustration'",
  "'initial_premium'",
  "'suitability'",
  "'exchange_1035'",
  "'funds'",
  "'open'",
  "'scheduled'",
  "'complete'",
  "'waived'",
  "'cancelled'",
  'custom_label',
  'scheduled_for',
  'completed_at',
  'waived_at',
  'created_by_user_id',
  'updated_by_user_id',
  'deleted_at',
  'from_status',
  'to_status',
  'changed_by_user_id',
  'FORCE ROW LEVEL SECURITY',
  'pp_assert_authenticated',
  'pp_assert_can_access_application',
  'pp_assert_owner()',
  "set_config('crm.rpc_context', 'create_policy_application_requirement', true)",
  "set_config('crm.rpc_context', 'update_policy_application_requirement', true)",
  "set_config('crm.rpc_context', 'transition_policy_application_requirement_status', true)",
  "set_config('crm.rpc_context', 'soft_delete_policy_application_requirement', true)",
  'SET search_path = pg_catalog, public, extensions',
  'GRANT SELECT ON TABLE public.policy_application_requirements TO authenticated',
  'REVOKE INSERT, UPDATE, DELETE ON TABLE public.policy_application_requirements FROM authenticated',
  'GRANT SELECT ON TABLE public.policy_application_requirement_history TO authenticated',
  'REVOKE INSERT, UPDATE, DELETE ON TABLE public.policy_application_requirement_history FROM authenticated',
  'GRANT EXECUTE ON FUNCTION public.create_policy_application_requirement(uuid, text, text, date, date)',
  'GRANT EXECUTE ON FUNCTION public.update_policy_application_requirement(uuid, jsonb)',
  'GRANT EXECUTE ON FUNCTION public.transition_policy_application_requirement_status(uuid, text, date, text)',
  'GRANT EXECUTE ON FUNCTION public.soft_delete_policy_application_requirement(uuid)',
  'This migration creates ZERO requirement rows',
  'No notes column',
  'Not for medical details',
] as const

export const MIGRATION_044_FORBIDDEN_MARKERS = [
  '045_',
  'CREATE TABLE public.cases',
  'CREATE TABLE IF NOT EXISTS public.cases',
  'CREATE TABLE public.policy_requirements',
  'CREATE TABLE IF NOT EXISTS public.policy_requirements',
  'ALTER TABLE public.tasks ADD',
  'ALTER TABLE public.documents ADD',
  'ALTER TABLE public.notes ADD',
  'ALTER TABLE public.activities ADD',
  'tasks.application_id',
  'documents.application_id',
  'notes.application_id',
  'activities.application_id',
  'notes text',
  'metadata jsonb',
  'unconstrained metadata',
  'assigned_user_id',
  'carrier_reference',
  'document_id',
  'requested_at',
  'received_at',
  'INSERT INTO public.policy_application_requirements SELECT',
  'INSERT INTO public.policy_application_requirement_history SELECT',
  'UPDATE public.policy_applications',
  'INSERT INTO public.policy_applications',
  'INSERT INTO public.tasks',
  'INSERT INTO public.activities',
  'INSERT INTO public.notes',
  'INSERT INTO public.documents',
  'transition_policy_application_stage',
  'record_policy_writing_commission_event',
  'pp_refresh_application_expected_compensation',
  'writing_receivable_expected',
  'CREATE TABLE public.commission',
  "'pending'",
  "'requested'",
  "'in_progress'",
  "'received'",
  "'not_required'",
] as const

export const MIGRATION_044_APPROVED_RPCS = [
  'create_policy_application_requirement',
  'update_policy_application_requirement',
  'transition_policy_application_requirement_status',
  'soft_delete_policy_application_requirement',
] as const
