/** Static contract markers for Migration 040 Experior Pending import staging. */

export const MIGRATION_040_FILENAME = '040_commission_pending_import.sql'

export const MIGRATION_040_CONTRACT_MARKERS = [
  'CREATE TABLE IF NOT EXISTS public.commission_pending_import_batches',
  'CREATE TABLE IF NOT EXISTS public.commission_pending_import_rows',
  "source_type IN ('experior_pending_report')",
  'statement_amount_cents',
  'escrow_cents',
  'file_sha256',
  'source_row_key',
  'transaction_fingerprint',
  'source_income_cents',
  'pending_review_status',
  'accepted_pending',
  'review_duplicate_candidate',
  'ignored_nonwriting',
  'ignored_nonpolicy',
  'review_policy_match',
  'review_advisor_match',
  'review_split_attribution',
  'create_commission_pending_import_batch',
  'stage_commission_pending_import_rows',
  'pp_commission_pending_import_classify_row',
  'enforce_commission_pending_accepted_safety',
  'commission_pending_rows_current_alloc_idx',
  'FORCE ROW LEVEL SECURITY',
  'SET search_path = pg_catalog, public, extensions',
  'pp_assert_owner',
  'crm_write_audit',
  'crm_is_owner()',
  'Type Override is ignored_nonwriting',
  'statement_amount_cents and escrow_cents are statement metadata only',
  'Never posts 035',
  'Source Income is the Pending amount',
] as const

export const MIGRATION_040_FORBIDDEN_MARKERS = [
  '041_',
  'posted_commission_event_id',
  'CREATE OR REPLACE FUNCTION public.review_commission_pending',
  'CREATE OR REPLACE FUNCTION public.post_commission_pending',
  'CREATE OR REPLACE FUNCTION public.review_commission_import_row(',
  'CREATE OR REPLACE FUNCTION public.post_commission_import_row(',
  'CREATE OR REPLACE FUNCTION public.create_commission_import_batch(',
  'CREATE OR REPLACE FUNCTION public.stage_commission_import_rows(',
  'CREATE OR REPLACE FUNCTION public.record_policy_writing_commission_event',
  'CREATE OR REPLACE FUNCTION public.pp_refresh_application_expected_compensation',
  'ALTER TABLE public.commission_import_batches',
  'ALTER TABLE public.commission_import_rows',
  'ALTER TABLE public.policy_writing_commission_events',
  'ALTER TABLE public.policy_application_expected_compensations',
  'ALTER TABLE public.policy_writing_commission_accounts',
  "source_type IN ('experior_paid_report', 'experior_pending_report')",
  "event_type IN ('pending'",
  'upline_id',
  'override_rate',
  'generational_rate',
  'pdf parser',
  'OCR',
  'TO anon',
] as const
