/** Static contract markers for Migration 032 Policy Production P1A foundation. */

export const MIGRATION_032_FILENAME = '032_policy_production_foundation.sql'

export const MIGRATION_032_CONTRACT_MARKERS = [
  'CREATE TYPE public.policy_application_stage AS ENUM',
  'CREATE TYPE public.policy_underwriting_disposition AS ENUM',
  'CREATE TYPE public.policy_delivery_status AS ENUM',
  'CREATE TYPE public.insurance_product_line AS ENUM',
  'CREATE TYPE public.policy_allocation_role AS ENUM',
  'CREATE TYPE public.policy_allocation_recipient_type AS ENUM',
  'CREATE TYPE public.policy_participant_role AS ENUM',
  'CREATE TABLE IF NOT EXISTS public.carriers',
  'CREATE TABLE IF NOT EXISTS public.insurance_products',
  'CREATE TABLE IF NOT EXISTS public.policy_applications',
  'CREATE TABLE IF NOT EXISTS public.policy_application_participants',
  'CREATE TABLE IF NOT EXISTS public.policy_application_stage_history',
  'CREATE TABLE IF NOT EXISTS public.policy_agent_allocations',
  'source_application_id',
  'policy_number_normalized',
  'SET search_path = pg_catalog, public, extensions',
  'CRM_PP:',
  'duplicate_link',
  'create_carrier',
  'update_carrier',
  'create_insurance_product',
  'update_insurance_product',
  'create_policy_application',
  'update_policy_application',
  'set_policy_application_participants',
  'set_policy_application_allocations',
  'transition_policy_application_stage',
  'set_policy_application_number',
  'correct_policy_application_number',
  'soft_delete_policy_application',
  'enforce_policies_pp_link_guard',
  'enforce_pp_history_append_only',
  'enforce_pp_allocation_immutability',
  'enforce_pp_participant_immutability',
  'pp_assert_allocations_valid',
  'pp_assert_participants_for_submit',
  'pp_assert_premium_for_submit',
  'pp_assert_in_force_delivery',
  'policies_source_application_unique_idx',
  'policy_applications_carrier_policy_number_unique_idx',
  'recipient_type',
  "'house'",
  'FORCE ROW LEVEL SECURITY',
  'GRANT SELECT ON TABLE',
  'REVOKE INSERT, UPDATE, DELETE ON TABLE',
  'crm_write_audit',
  'annuity_deposit_cents',
  'submitted_premium_cents',
] as const

export const MIGRATION_032_FORBIDDEN_MARKERS = [
  '033_',
  'issued_policy_id',
  'CREATE TABLE public.commission_expectations',
  'CREATE TABLE public.commission_transactions',
  'CREATE TABLE IF NOT EXISTS public.commission_expectations',
  'CREATE TABLE IF NOT EXISTS public.commission_transactions',
  'CREATE TABLE public.cases',
  'CREATE TABLE IF NOT EXISTS public.cases',
  'CREATE TABLE public.workflow_runs',
  'CREATE TABLE IF NOT EXISTS public.policy_requirements',
  'estimated_commission',
  'estimated_cash_flow',
  'commission_lifecycle_status',
  'INSERT INTO public.activities',
  'CREATE OR REPLACE FUNCTION public.record_crm_activity',
  'CREATE OR REPLACE FUNCTION public.crm_write_activity',
] as const
