/** Static contract markers for Migration 053 owner-only bulk lead import writer
 *  plus the narrow archive_intake_lead allowlist update. */

export const MIGRATION_053_FILENAME = '053_bulk_lead_import_writer.sql'

export const MIGRATION_053_RPC = 'import_bulk_lead_consumer'

export const MIGRATION_053_ARCHIVE_RPC = 'archive_intake_lead'

export const MIGRATION_053_HELPERS = [
  'bulk_lead_import_collect_candidates',
  'bulk_lead_import_classify_match',
] as const

export const MIGRATION_053_INTAKE_LEAD_TYPES = [
  'Family Report Card',
  'Business Report Card',
  'Retirement Report Card',
  'Protection Gap',
  'Student Loan Report Card',
  'Credit Report Card',
  'Digital Identity',
  'Bulk Lead Import',
] as const

export const MIGRATION_053_CONTRACT_MARKERS = [
  'CREATE OR REPLACE FUNCTION public.bulk_lead_import_collect_candidates(',
  'CREATE OR REPLACE FUNCTION public.bulk_lead_import_classify_match(',
  'CREATE OR REPLACE FUNCTION public.import_bulk_lead_consumer(p_payload jsonb)',
  'RETURNS jsonb',
  'SECURITY DEFINER',
  'SET search_path = pg_catalog, public, extensions',
  'PERFORM public.pp_assert_owner()',
  'PERFORM public.pp_assert_payload_size(p_payload)',
  "RAISE EXCEPTION 'BULK_IMPORT:protected_field'",
  "RAISE EXCEPTION 'BULK_IMPORT:unsupported_batch'",
  "RAISE EXCEPTION 'BULK_IMPORT:missing_last_name'",
  "RAISE EXCEPTION 'BULK_IMPORT:malformed_contact'",
  "v_lock_key := 'bulk_import_row:' || v_batch_id || ':' || v_row_ref",
  'PERFORM pg_advisory_xact_lock(hashtext(v_lock_key))',
  'PERFORM public.quick_add_acquire_identity_locks(v_email, v_phone)',
  "v_batch_id text := 'bulk_lead_import_2026_leads_crm_v1'",
  "v_lead_type text := 'Bulk Lead Import'",
  "v_lead_source text := 'bulk_lead_import_2026_leads_crm'",
  "v_source_page text := 'bulk_import:2026_leads_crm:Leads'",
  "v_pipeline_id uuid := '22222222-2222-2222-2222-222222222201'::uuid",
  "v_stage_id uuid := '33333333-3333-3333-3333-333333333001'::uuid",
  "consent_snapshot",
  "'{}'::jsonb",
  "sheets_sync_status",
  "'skipped'",
  "attribution_method",
  "'unknown'",
  "status",
  "'lead'",
  "'unassigned'",
  "'duplicate_review'",
  'exact_trusted_match',
  'possible_match',
  'new_prospect',
  'already_exists',
  'review_required',
  'INSERT INTO public.duplicate_reviews (',
  'ALTER FUNCTION public.import_bulk_lead_consumer(jsonb) OWNER TO postgres',
  'REVOKE ALL ON FUNCTION public.import_bulk_lead_consumer(jsonb) FROM PUBLIC',
  'REVOKE ALL ON FUNCTION public.import_bulk_lead_consumer(jsonb) FROM anon',
  'GRANT EXECUTE ON FUNCTION public.import_bulk_lead_consumer(jsonb) TO authenticated',
  'REVOKE ALL ON FUNCTION public.bulk_lead_import_collect_candidates(extensions.citext, text) FROM PUBLIC, anon, authenticated',
  'REVOKE ALL ON FUNCTION public.bulk_lead_import_classify_match(extensions.citext, text, text, text, jsonb) FROM PUBLIC, anon, authenticated',
  'CREATE OR REPLACE FUNCTION public.archive_intake_lead(',
  'ALTER FUNCTION public.archive_intake_lead(uuid, text) OWNER TO postgres',
  'REVOKE ALL ON FUNCTION public.archive_intake_lead(uuid, text) FROM PUBLIC',
  'REVOKE ALL ON FUNCTION public.archive_intake_lead(uuid, text) FROM anon',
  'REVOKE ALL ON FUNCTION public.archive_intake_lead(uuid, text) FROM authenticated',
  'GRANT EXECUTE ON FUNCTION public.archive_intake_lead(uuid, text) TO authenticated',
  "CRM_INTAKE:not_authenticated",
  "CRM_INTAKE:invalid_reason",
  "CRM_INTAKE:not_authorized",
  "CRM_INTAKE:already_archived",
  "CRM_INTAKE:not_intake_lead",
  "CRM_INTAKE:duplicate_review_pending",
  "'Family Report Card'",
  "'Business Report Card'",
  "'Retirement Report Card'",
  "'Protection Gap'",
  "'Student Loan Report Card'",
  "'Credit Report Card'",
  "'Digital Identity'",
  "'Bulk Lead Import'",
  'public.crm_is_owner()',
  'public.crm_can_access_household(v_lead.household_id)',
  'PERFORM public.crm_write_activity(',
  "'Intake archived'",
  'UPDATE public.leads',
  'SET deleted_at = now()',
] as const

export const MIGRATION_053_FORBIDDEN_MARKERS = [
  '054_',
  'CREATE TABLE',
  'CREATE TABLE IF NOT EXISTS',
  'ALTER TABLE',
  'ALTER TYPE',
  'CREATE TYPE',
  'ADD COLUMN',
  'CREATE INDEX',
  'CREATE POLICY',
  'ENABLE ROW LEVEL SECURITY',
  'CREATE TRIGGER',
  'TO anon',
  'GRANT EXECUTE ON FUNCTION public.import_bulk_lead_consumer(jsonb) TO anon',
  'INSERT INTO public.opportunities',
  'INSERT INTO public.activities',
  'INSERT INTO public.tasks',
  'INSERT INTO public.assessments',
  'INSERT INTO public.policy_applications',
  'INSERT INTO public.policies',
  'INSERT INTO public.cases',
  'INSERT INTO public.commissions',
  'emptyConsentSnapshot',
  'assign_household',
  'quick_add_contact',
  'ingest_public_report_card',
  'ingest_digital_identity_connect',
  'create_canonical_client',
  'CREATE TABLE public.contacts',
  'credit_repair',
] as const
