/** Static contract markers for Migration 035 writing-advisor actual commission ledger. */

export const MIGRATION_035_FILENAME = '035_writing_advisor_actual_commission_ledger.sql'

export const MIGRATION_035_CONTRACT_MARKERS = [
  'CREATE TABLE IF NOT EXISTS public.policy_writing_commission_accounts',
  'CREATE TABLE IF NOT EXISTS public.policy_writing_commission_events',
  'expected_cents_pinned',
  'attribution_status',
  "event_type IN ('paid', 'adjustment', 'chargeback', 'recovery', 'reversal')",
  'amount_cents bigint NOT NULL',
  'reversed_event_id',
  'idempotency_key',
  'record_policy_writing_commission_event',
  'record_policy_writing_commission_event_pre_issue',
  'reverse_policy_writing_commission_event',
  'attribute_unattributed_commission_event',
  'pp_writing_commission_snapshot',
  'pp_writing_commission_reconcile_sums',
  'FORCE ROW LEVEL SECURITY',
  'SET search_path = pg_catalog, public, extensions',
  'advisor_id = public.crm_advisor_id()',
  'crm_write_audit',
  'writing-advisor actual compensation only',
  'Never fabricate $0',
  'statement_identifier',
  'Never randomly generated',
  'API/request idempotency',
  'idempotency_conflict',
] as const

export const MIGRATION_035_FORBIDDEN_MARKERS = [
  '036_',
  'CREATE TYPE public.advisor_contract_level',
  'CREATE TYPE public.commission_event_type',
  'CREATE TABLE public.commission_expectations',
  'CREATE TABLE public.commission_transactions',
  'CREATE TABLE IF NOT EXISTS public.commission_ledger',
  'CREATE TABLE IF NOT EXISTS public.import_batches',
  'upline_id',
  'override_rate',
  'generational_rate',
  'hierarchy_rate',
  'spread_rate',
  'recruiter_id',
  "event_type IN ('paid', 'adjustment', 'chargeback', 'recovery', 'reversal', 'pending'",
  "event_type IN ('pending'",
  'Excel Empire',
  'TrusteeFriend',
  'product_compensation_schedules_source_legacy',
  '03-Experior',
  "date_part('year', age(",
  'v_key := extensions.gen_random_uuid()',
] as const
