/** Static contract markers for Migration 045 post-placement policy lifecycle. */

export const MIGRATION_045_FILENAME = '045_policy_post_placement_lifecycle.sql'

export const MIGRATION_045_CONTRACT_MARKERS = [
  'terminated_on date',
  'termination_reason text',
  'policies_termination_reason_len_check',
  'policies_pp_linked_lifecycle_check',
  "'issued', 'in_force', 'canceled', 'surrendered'",
  'record_policy_post_placement_outcome',
  'pp_assert_owner()',
  "set_config('crm.rpc_context', 'record_policy_post_placement_outcome', true)",
  'SET search_path = pg_catalog, public, extensions',
  'crm_write_audit',
  "'record_policy_post_placement_outcome'",
  'CREATE OR REPLACE FUNCTION public.enforce_policies_pp_link_guard()',
  "v_is_lifecycle_ctx boolean := (v_ctx = 'record_policy_post_placement_outcome')",
  "v_is_issue_ctx boolean := (v_ctx = 'transition_policy_application_stage')",
  'GRANT EXECUTE ON FUNCTION public.record_policy_post_placement_outcome(uuid, text, text, date)',
  'REVOKE ALL ON FUNCTION public.record_policy_post_placement_outcome(uuid, text, text, date)',
  'FROM PUBLIC, anon',
  'This migration creates ZERO production rows',
  'performs ZERO backfill',
  'interval \'12 months\'',
] as const

export const MIGRATION_045_FORBIDDEN_MARKERS = [
  '046_',
  'ALTER TYPE public.policy_application_stage',
  'ADD VALUE',
  "'chargeback'",
  'CREATE TABLE public.cases',
  'CREATE TABLE IF NOT EXISTS public.cases',
  'record_policy_writing_commission_event',
  'pp_refresh_application_expected_compensation',
  'set_policy_application_writing_receivable_expected',
  'UPDATE public.policy_applications',
  'INSERT INTO public.policy_applications',
  'INSERT INTO public.policies',
  'INSERT INTO public.tasks',
  'INSERT INTO public.activities',
  'INSERT INTO public.notes',
  'CREATE TABLE public.commission',
  'GRANT INSERT',
  'GRANT UPDATE',
  'GRANT DELETE',
  'TO anon',
] as const

export const EXPECTED_NUMBERED_MIGRATIONS = [
  '001_extensions_and_enums.sql',
  '002_profiles_roles_settings_audit.sql',
  '003_verticals_pipelines_stages.sql',
  '004_referral_sources_households_members_duplicates.sql',
  '005_leads_assessments_recommendations.sql',
  '006_opportunities_assignments.sql',
  '007_tasks_notes_activities.sql',
  '008_policies_appointments_reviews.sql',
  '009_documents_portal.sql',
  '010_rls_policies.sql',
  '011_seed_pipelines.sql',
  '012_secure_rpcs.sql',
  '013_storage_policies.sql',
  '014_security_hardening.sql',
  '015_member_relationship_enum_values.sql',
  '016_household_members_soft_delete_rpc.sql',
  '017_soft_delete_note_rpc.sql',
  '018_assessment_type_household_onboarding.sql',
  '019_assessment_lifecycle_status.sql',
  '020_public_family_diagnostic_ingest.sql',
  '021_public_family_duplicate_resolution.sql',
  '022_public_family_task_automation.sql',
  '023_confirm_same_allows_ingest_resolve_task.sql',
  '024_authenticated_crm_privileges_and_duplicate_notes_fix.sql',
  '025_digital_identity_cards.sql',
  '026_digital_identity_connect_ingest.sql',
  '027_digital_identity_relationship_photo.sql',
  '028_digital_identity_campaign_attribution.sql',
  '029_security_hardening_opportunities_and_relationships.sql',
  '030_revoke_authenticated_activity_inserts.sql',
  '031_quick_add_contact_foundation.sql',
  '032_policy_production_foundation.sql',
  '033_writing_advisor_compensation_foundation.sql',
  '034_writing_advisor_expected_compensation.sql',
  '035_writing_advisor_actual_commission_ledger.sql',
  '036_commission_import_reconciliation.sql',
  '037_client_production_workflow_extensions.sql',
  '038_historical_import_support.sql',
  '039_commission_import_review_post_hardening.sql',
  '040_commission_pending_import.sql',
  '041_commission_pending_review.sql',
  '042_writing_receivable_eligibility.sql',
  '043_public_report_card_ingest.sql',
  '044_policy_application_requirements.sql',
  '045_policy_post_placement_lifecycle.sql',
  '046_opportunity_case_conversion.sql',
  '047_credit_repair_student_loan_sales_catalog.sql',
  '048_student_loan_report_card_ingest.sql',
  '049_specialize_public_report_card_follow_up_copy.sql',
  '050_credit_report_card_ingest.sql',
  '051_intake_archive_workflow.sql',
  '052_fix_intake_archive_activity_order.sql',
] as const
