/** Static contract markers for Migration 036 commission import reconciliation. */

export const MIGRATION_036_FILENAME = '036_commission_import_reconciliation.sql'

export const MIGRATION_036_CONTRACT_MARKERS = [
  'CREATE TABLE IF NOT EXISTS public.commission_import_batches',
  'CREATE TABLE IF NOT EXISTS public.commission_import_rows',
  'CREATE TABLE IF NOT EXISTS public.commission_import_carrier_aliases',
  "source_type IN ('experior_paid_report')",
  'file_sha256',
  'source_row_key',
  'transaction_fingerprint',
  'source_income_cents',
  'posted_commission_event_id',
  "review_status IN (",
  'ready_to_post',
  'review_duplicate_candidate',
  'ignored_nonwriting',
  'ignored_nonpolicy',
  'review_policy_match',
  'review_advisor_match',
  'review_split_attribution',
  'create_commission_import_batch',
  'stage_commission_import_rows',
  'review_commission_import_row',
  'post_commission_import_row',
  'record_policy_writing_commission_event',
  '036:',
  "036:' || v_batch.id::text || ':' || v_row.source_row_key",
  'pp_commission_import_transaction_fingerprint',
  'FORCE ROW LEVEL SECURITY',
  'SET search_path = pg_catalog, public, extensions',
  'pp_assert_owner',
  'crm_write_audit',
  'crm_is_owner()',
  'Type Override is never auto-posted',
  'Advance % is never re-applied',
  'Writing-advisor compensation only',
] as const

export const MIGRATION_036_FORBIDDEN_MARKERS = [
  '037_',
  'CREATE TYPE public.commission_event_type',
  'CREATE TYPE public.commission_import_status',
  'CREATE TABLE public.commission_expectations',
  'CREATE TABLE public.commission_transactions',
  'CREATE TABLE IF NOT EXISTS public.commission_ledger',
  'upline_id',
  'override_rate',
  'generational_rate',
  'hierarchy_rate',
  'spread_rate',
  'recruiter_id',
  "event_type IN ('pending'",
  'pending_eligible_released',
  'Excel Empire',
  'TrusteeFriend',
  'product_compensation_schedules_source_legacy',
  'pdf parser',
  'OCR',
  'carrier scraping',
  'v_key := extensions.gen_random_uuid()',
  'carrier_transaction_id is invented',
  'UNIQUE (transaction_fingerprint)',
  'commission_import_rows_live_key_uidx',
] as const
