import { existsSync, readdirSync, readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

const here = dirname(fileURLToPath(import.meta.url))
const queuePage = readFileSync(join(here, '../../pages/crm/CrmProductionPage.tsx'), 'utf8')
const board = readFileSync(join(here, 'ProductionBoard.tsx'), 'utf8')
const card = readFileSync(join(here, 'ProductionBoardCard.tsx'), 'utf8')
const moveMenu = readFileSync(join(here, 'ProductionBoardMoveMenu.tsx'), 'utf8')
const movement = readFileSync(join(here, 'boardMovement.ts'), 'utf8')
const dialog = readFileSync(join(here, 'StageTransitionConfirmDialog.tsx'), 'utf8')
const applicationApi = readFileSync(join(here, 'applicationApi.ts'), 'utf8')
const styles = readFileSync(join(here, '../../src/styles.css'), 'utf8')
const packageJson = readFileSync(join(here, '../../package.json'), 'utf8')
const packageLock = existsSync(join(here, '../../package-lock.json'))
  ? readFileSync(join(here, '../../package-lock.json'), 'utf8')
  : ''
const migrationsDir = join(here, '../../supabase/migrations')

describe('Phase C board movement contracts', () => {
  it('keeps drag and Move to on the same helper and the existing transition RPC', () => {
    expect(movement).toContain('allowedNextStages')
    expect(movement).toContain('stageTransitionAction')
    expect(movement).not.toContain('shortestStagePath')
    expect(card).toContain('boardMoveDestinations(item, role)')
    expect(moveMenu).toContain('destinations.map')
    expect(board).toContain('resolveBoardDropDestination')
    expect(queuePage).toContain('beginBoardMove')
    expect(queuePage).toContain('defaultBoardStageTransitionReason')
    expect(queuePage).not.toContain('defaultStageTransitionReason')
    expect(movement).toContain('Updated from Production board')
    expect(movement).not.toContain('Updated from Production detail')
    expect(queuePage).toContain('transitionPolicyApplicationStage')
    expect(queuePage).toContain('buildBoardTransitionRpcArgs')
    expect(board).not.toContain('transitionPolicyApplicationStage')
    expect(card).not.toContain('transitionPolicyApplicationStage')
    expect(applicationApi).toContain("transition: 'transition_policy_application_stage'")
    expect(queuePage).not.toContain("from('policy_applications')")
    expect(queuePage).not.toContain('.update(')
    expect(board).not.toContain('.update(')
    expect(card).not.toContain('.update(')
  })

  it('reuses StageTransitionConfirmDialog for gated board moves', () => {
    expect(queuePage).toContain('StageTransitionConfirmDialog')
    expect(queuePage).toContain('crm-production-review-overlay')
    expect(dialog).toContain('{action.confirmTitle}')
    expect(dialog).toContain('Policy number')
    expect(dialog).toContain('Reason')
    expect(queuePage).toContain('pendingMove.item.policy_number')
    expect(movement).toContain("kind: 'confirm'")
    expect(movement).toContain('needsPolicyNumber')
    expect(movement).toContain('needsReason')
  })

  it('refetches through reloadKey and does not invent local stage truth', () => {
    expect(queuePage).toContain('setReloadKey((n) => n + 1)')
    expect(queuePage).toContain('interpretBoardMoveResult')
    expect(queuePage).toContain('setBoardFocusStage(action.toStage)')
    expect(queuePage).toMatch(/useEffect\([\s\S]*, \[reloadKey\]\)/)
    expect(queuePage).toContain('buildProductionDashboard(filteredItems')
    expect(board).not.toContain('setItems')
    expect(card).not.toContain('production_stage:')
    expect(movement).toContain('STALE_BOARD_REFRESH_MESSAGE')
    expect(queuePage).toContain("outcome.kind === 'stale'")
  })

  it('separates detail, notes, Move to, and drag interactions', () => {
    expect(card).toContain('crmProductionPath(item.id)')
    expect(card).toContain('className="crm-production-board-card-link"')
    expect(card.indexOf('crm-production-board-card-link')).toBeLessThan(
      card.indexOf('crm-production-board-card-actions'),
    )
    expect(card).toContain('Operational notes for')
    expect(card).toContain('ProductionBoardMoveMenu')
    expect(moveMenu).toContain('Move to...')
    expect(moveMenu).toContain('aria-haspopup="listbox"')
    expect(card).toContain('crm-production-board-drag-handle')
    expect(card).toContain('tabIndex={-1}')
    expect(card).toContain('onClick={(event) => event.stopPropagation()}')
    expect(card).toContain('Edit Application')
    expect(card).toContain('crmProductionEditPath(item.id)')
    expect(card).toContain('canShowProductionEditAction')
    expect(card).not.toContain('fetchHouseholdNotes')
    expect(board).not.toContain('fetchHouseholdNotes')
  })

  it('makes Move to the keyboard and mobile path and does not force eight-column drag', () => {
    expect(board).toContain('PointerSensor')
    expect(board).not.toContain('KeyboardSensor')
    expect(board).toContain("layout === 'horizontal' && Boolean(onRequestMove)")
    expect(board).toContain('enableDrag={false}')
    expect(board).toContain("layout === 'stacked'")
    expect(board).toContain('role="tablist"')
    expect(board).toContain('focusStage')
    expect(moveMenu).toContain('role="listbox"')
    expect(moveMenu).toContain('role="option"')
    expect(styles).toContain('.crm-production-board-drop-hint')
    expect(board).toContain('Not a valid next stage')
    expect(board).toContain('{column.label}')
  })

  it('installs only the approved dnd-kit packages and keeps in-memory ids', () => {
    expect(packageJson).toContain('"@dnd-kit/core"')
    expect(packageJson).toContain('"@dnd-kit/utilities"')
    expect(packageJson).not.toContain('@dnd-kit/sortable')
    expect(packageLock).not.toContain('"@dnd-kit/sortable"')
    expect(packageJson).not.toMatch(/react-beautiful-dnd|hello-pangea|"react-dnd"/)
    expect(board).toContain('@dnd-kit/core')
    expect(board).not.toContain('@dnd-kit/sortable')
    expect(movement).toContain('app:${applicationId}')
    expect(movement).toContain('stage:${stage}')
    expect(card).toContain('data: { applicationId: item.id }')
    expect(card).not.toContain('dataTransfer')
    expect(board).not.toContain('dataTransfer')
  })

  it('does not add Migration 039, notes schema, or service-role board writes', () => {
    const files = readdirSync(migrationsDir).filter((name) => name.endsWith('.sql'))
    expect(files).toContain('039_commission_import_review_post_hardening.sql')
    expect(existsSync(join(migrationsDir, '039_production_board.sql'))).toBe(false)
    expect(queuePage).not.toContain('SERVICE_ROLE')
    expect(board).not.toContain('createSupabaseBrowserClient')
    expect(card).not.toContain('createSupabaseBrowserClient')
    expect(movement).not.toContain('createSupabaseBrowserClient')
    expect(queuePage).not.toContain('policy_notes')
    expect(queuePage).not.toContain('createHouseholdNote')
  })
})
